import { useState } from 'react';
import { App, Button, Checkbox, Input, InputNumber, Modal, Select, Space, Table, Tabs, Tag } from 'antd';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { AS_OF_DATE, mockUsers } from '@/mock';
import { useBusinessStore } from '@/mock/business';
import { ticketLabels, ticketMeta, ticketTable, type TicketKind } from '@/mock/tickets';
import { visibleProjects } from '@/mock/selectors';
import { useAppStore } from '@/store/useAppStore';
import { PageHeader } from '@/components/common/PageHeader';

export function TicketsPage({ family }: { family: 'quality' | 'risk' }) {
  const { data, dispatch } = useBusinessStore(); const { currentRole, currentUser } = useAppStore(); const { message } = App.useApp();
  const [params, setParams] = useSearchParams(); const navigate = useNavigate();
  const kinds: TicketKind[] = family === 'quality' ? ['requirement', 'bug'] : ['issue', 'risk']; const base = family === 'quality' ? '/requirements-bugs' : '/issues-risks';
  const projects = visibleProjects(currentRole, data.projects, data); const ids = new Set(projects.map((p) => p.id));
  const [open, setOpen] = useState(false); const [kind, setKind] = useState<TicketKind>(kinds[0]); const [projectId, setProjectId] = useState(params.get('projectId') ?? projects[0]?.id);
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState(''); const [rank, setRank] = useState(''); const [owner, setOwner] = useState(currentUser.id); const [deadline, setDeadline] = useState('2026-09-20'); const [product, setProduct] = useState(''); const [impactBaseline, setImpactBaseline] = useState(false); const [probability, setProbability] = useState(3); const [impact, setImpact] = useState(3); const [measures, setMeasures] = useState('');
  const all = kinds.flatMap((kind) => ticketTable(data, kind).filter((t) => ids.has(t.projectId)).map((t) => ({ ...t, kind, meta: ticketMeta(data, kind, t.id), rank: 'priority' in t ? t.priority : 'severity' in t ? t.severity : t.level })));
  const filtered = all.filter((t) => (!params.get('projectId') || t.projectId === params.get('projectId')) && (!params.get('kind') || t.kind === params.get('kind')) && (!params.get('status') || t.status === params.get('status')) && (!params.get('owner') || t.meta.ownerId === params.get('owner')) && (!params.get('rank') || t.rank === params.get('rank')) && (!params.get('search') || `${t.id} ${t.title}`.includes(params.get('search')!)) && (params.get('overdue') !== 'true' || !['已关闭', '已缓解', '已转问题'].includes(t.status) && t.meta.deadline < AS_OF_DATE));
  const update = (key: string, value?: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.delete('page'); setParams(next); };
  const writers = family === 'quality' ? ['project-manager', 'solution-tech'] : ['project-manager'];
  const ranks = kind === 'requirement' ? ['高', '中', '低'] : kind === 'bug' ? ['致命', '严重', '一般', '轻微'] : ['重大', '重要', '一般'];
  return <><PageHeader title={family === 'quality' ? 'HS-05 需求BUG台账' : 'HS-07 问题风险台账'} description={`原业务闭环 · 项目权限范围 · ${AS_OF_DATE}`} breadcrumbs={[{ title: '首页', href: '/' }, { title: '业务台账' }]} extra={<Button type="primary" disabled={!writers.includes(currentRole)} onClick={() => { setKind(kinds[0]); setRank(''); setOpen(true); }}>新建事项</Button>} />
    <Space wrap style={{ marginBottom: 16 }}><Select aria-label="事项项目" placeholder="全部项目" allowClear showSearch optionFilterProp="label" style={{ width: 250 }} value={params.get('projectId') ?? undefined} options={projects.map((p) => ({ value: p.id, label: p.name }))} onChange={(v) => update('projectId', v)} /><Select aria-label="事项状态" placeholder="全部状态" allowClear style={{ width: 140 }} value={params.get('status') ?? undefined} options={[...new Set(all.map((t) => t.status))].map((value) => ({ value, label: value }))} onChange={(v) => update('status', v)} /><Select aria-label="事项等级" placeholder="优先级 / 等级" allowClear style={{ width: 160 }} value={params.get('rank') ?? undefined} options={[...new Set(all.map((t) => t.rank))].map((value) => ({ value, label: value }))} onChange={(v) => update('rank', v)} /><Select aria-label="事项责任人" placeholder="责任人" allowClear showSearch optionFilterProp="label" style={{ width: 140 }} value={params.get('owner') ?? undefined} options={mockUsers.map((u) => ({ value: u.id, label: u.name }))} onChange={(v) => update('owner', v)} /><Input aria-label="事项搜索" placeholder="编号或标题" style={{ width: 200 }} value={params.get('search') ?? ''} onChange={(e) => update('search', e.target.value)} /><Checkbox checked={params.get('overdue') === 'true'} onChange={(e) => update('overdue', e.target.checked ? 'true' : undefined)}>仅超期未关闭</Checkbox><Button onClick={() => setParams({})}>重置筛选</Button></Space>
    <Tabs activeKey={params.get('kind') ?? 'all'} onChange={(key) => update('kind', key === 'all' ? undefined : key)} items={[{ key: 'all', label: '全部事项' }, ...kinds.map((kind) => ({ key: kind, label: ticketLabels[kind] }))]} />
    <p>共{filtered.length}项。{family === 'quality' ? '需求按优先级、BUG按严重性跟踪；责任人处理后由发起人验证关闭或退回。超期提醒按期望解决日期计算。' : '演示规则 CASE-1：风险评分=概率×影响，6/12/20分对应中等/重大/特大；重大事项进入PMO视野。问题风险超期1/3/7天依次提示部门负责人/PMO/PMC；已解决问题仍须PM确认。'}</p>
    <Table rowKey="id" size="small" dataSource={filtered} scroll={{ x: 1350 }} pagination={{ pageSize: 10, current: Number(params.get('page')) || 1, showSizeChanger: false, onChange: (page) => { const next = new URLSearchParams(params); next.set('page', String(page)); setParams(next); } }} columns={[
      { title: '编号 / 事项', width: 300, fixed: 'left', render: (_, t) => <Button type="link" style={{ whiteSpace: 'normal', textAlign: 'left', display: 'block', height: 'auto', padding: 0 }} onClick={() => navigate(`${base}/${t.id}?${params}`)}>{t.id}<div>{t.title}</div></Button> }, { title: '项目', width: 250, render: (_, t) => projects.find((p) => p.id === t.projectId)?.name },
      { title: '类型 / 等级', width: 110, render: (_, t) => <>{ticketLabels[t.kind]}<div>{t.rank}</div></> }, { title: '状态 / 责任人', width: 140, render: (_, t) => <><Tag>{t.status}</Tag><div>{t.owner}</div></> },
      { title: '目标时间 / 提醒', width: 170, render: (_, t) => <>{t.meta.deadline}<div>{!['已关闭', '已缓解', '已转问题'].includes(t.status) && t.meta.deadline < AS_OF_DATE ? '已超期，持续督办' : '按目标跟踪'}</div></> },
      { title: family === 'quality' ? '最新进展' : '升级 / 最新进展', width: 260, render: (_, t) => <>{t.meta.escalatedTo ?? (t.kind === 'risk' && ['重大', '特大'].includes(t.rank) || t.kind === 'issue' && t.rank === '重大' ? 'PMO' : '项目内跟踪')}<div>{t.meta.history.at(-1)?.detail}</div></> },
    ]} />
    <Modal title={`新建${ticketLabels[kind]}`} width={650} open={open} onCancel={() => setOpen(false)} onOk={() => {
      try { if (!projectId) throw new Error('请选择项目'); const prefix = ({ requirement: 'REQ', bug: 'BUG', issue: 'ISSUE', risk: 'RSK' })[kind]; const id = `${prefix}-NEW-${ticketTable(data, kind).length + 1}`; dispatch({ type: 'create-ticket', kind, projectId, title, rank, ownerId: owner, description, category, deadline, product, baselineImpact: impactBaseline, probability, impact, measures }, { id: currentUser.id, name: currentUser.name, role: currentRole }); setOpen(false); navigate(`${base}/${id}?${params}`); message.success('原事项已提交责任人'); } catch (error) { message.error((error as Error).message); }
    }}><Space direction="vertical" style={{ width: '100%' }}><Select aria-label="新建事项类型" value={kind} options={kinds.map((value) => ({ value, label: ticketLabels[value] }))} onChange={(v) => { setKind(v); setRank(''); }} /><Select aria-label="新建事项项目" style={{ width: '100%' }} value={projectId} options={projects.filter((p) => !data.lockedProjects.includes(p.id) && (p.pmId === currentUser.id || p.memberIds?.includes(currentUser.id))).map((p) => ({ value: p.id, label: p.name }))} onChange={setProjectId} /><Input aria-label="事项标题" placeholder="标题（必填）" value={title} onChange={(e) => setTitle(e.target.value)} /><Input aria-label="事项类别" placeholder={kind === 'bug' ? '缺陷类别：功能/性能/兼容/安全等（必填）' : '业务类别（必填）'} value={category} onChange={(e) => setCategory(e.target.value)} /><Input.TextArea aria-label="事项描述" placeholder="描述、复现步骤或影响（必填）" rows={3} value={description} onChange={(e) => setDescription(e.target.value)} /><Select aria-label="新建责任人" value={owner} showSearch optionFilterProp="label" options={mockUsers.map((u) => ({ value: u.id, label: u.name }))} onChange={setOwner} /><Input aria-label="期望解决日期" value={deadline} placeholder="YYYY-MM-DD" onChange={(e) => setDeadline(e.target.value)} />{kind !== 'risk' ? <Select aria-label="新建优先级" placeholder="优先级 / 等级（必填）" value={rank || undefined} options={ranks.map((value) => ({ value, label: value }))} onChange={setRank} /> : <><label>概率评分 <InputNumber aria-label="风险概率" min={1} max={5} value={probability} onChange={(v) => setProbability(v ?? 1)} /></label><label>影响评分 <InputNumber aria-label="风险影响" min={1} max={5} value={impact} onChange={(v) => setImpact(v ?? 1)} /></label><Input.TextArea aria-label="风险措施" placeholder="应对措施（必填）" value={measures} onChange={(e) => setMeasures(e.target.value)} /></>}{kind === 'requirement' && <><Input aria-label="产品名称" placeholder="产品线 / 产品名称" value={product} onChange={(e) => setProduct(e.target.value)} /><Checkbox checked={impactBaseline} onChange={(e) => setImpactBaseline(e.target.checked)}>影响进度基线，须先关联计划变更</Checkbox></>}</Space></Modal>
  </>;
}
