import { describe,it,expect } from 'vitest';
import { mockProjects } from '@/mock';
import {createBusinessState,transition,type Actor,type BusinessState} from '@/mock/business-domain';
import {acceptanceConditions,acceptanceDetail,checkNames,confirmedReportedAmount,reportAmount,supplierSources} from '@/mock/acceptance';
import type { AcceptanceRecord } from '@/models/types';
import type {AcceptanceReport} from '@/models/settlement';
const pm:Actor={id:'U-001',name:'张建国',role:'project-manager'};
const pmo:Actor={id:'U-002',name:'李主任',role:'pmo'};
const finance:Actor={id:'U-004',name:'刘敏',role:'finance'};
function repeatCustomer(){let s=createBusinessState();const old=s.acceptances.find((a)=>a.projectId==='P-006'&&a.type==='客户终验')!;s=transition(s,{type:'reply-acceptance',id:old.id,reply:'已完成接口联调并补齐培训记录'},pm);const d=acceptanceDetail(s,old);s=transition(s,{type:'submit-acceptance',projectId:'P-006',kind:'客户终验',id:old.id,detail:{scope:d.scope,plannedDate:'2026-09-10',method:'现场验收',customerContact:d.customerContact,participants:d.participants,contractId:d.contractId}},pm);return {s,old,next:s.acceptances.at(-1)!};}
function passCustomer(){const initial=repeatCustomer();let s=initial.s;const next=initial.next;s=transition(s,{type:'review-acceptance',id:next.id,passed:true,checks:checkNames(next.type).map((name)=>({name,passed:true,note:'现场复验确认'})),opinion:'客户同意验收',process:'客户与项目组现场逐项复验'},pm);return {s,next:s.acceptances.find((a)=>a.id===next.id)!};}
function reportDraft(s:BusinessState,a:AcceptanceRecord,batch='B01',amount=100):Omit<AcceptanceReport,'id'|'status'|'submittedBy'>{return {projectId:a.projectId,contractId:acceptanceDetail(s,a).contractId!,acceptanceId:a.id,batchNo:batch,reportType:'阶段报验',date:'2026-09-09',taxLines:[{taxRate:6,amount}],materials:['园区验收报告.pdf'],note:'第一批范围计量'};}
describe('验收与报验业务约束',()=>{
 it('P006可复验，真实缺件与质量失败仍阻断；P001保留原故事',()=>{const s=createBusinessState();expect(acceptanceConditions(s,'P-006','客户终验').every((c)=>c.passed)).toBe(true);expect(s.projects.find((p)=>p.id==='P-001')).toEqual({...mockProjects.find((p)=>p.id==='P-001'),frozenEstimateVersionId:'EST-VER-001'});s.materials.find((m)=>m.projectId==='P-006'&&m.name==='测试报告')!.status='驳回';expect(acceptanceConditions(s,'P-006','客户终验').find((c)=>c.name==='必交材料')?.passed).toBe(false);s.qualityPlans['P-006'].checks.at(-1)!.passed=false;expect(acceptanceConditions(s,'P-006','客户终验').find((c)=>c.name==='质量检查')?.passed).toBe(false);});
 it('整改必须先回复；复验新轮次保留原结论',()=>{const {s,old,next}=repeatCustomer();expect(next.round).toBe(old.round+1);expect(s.acceptances.find((a)=>a.id===old.id)?.status).toBe('整改中');expect(s.acceptanceDetails[next.id].previousId).toBe(old.id);expect(acceptanceDetail(s,old).corrections[0].reply).toContain('联调');});
 it('无权限及不完整检查不能通过；错误提交不改变原状态',()=>{const {s,next}=repeatCustomer();const before=structuredClone(s);const action={type:'review-acceptance' as const,id:next.id,passed:true,checks:[],opinion:'通过',process:'现场'};expect(()=>transition(s,action,pmo)).toThrow('主PM');expect(()=>transition(s,action,pm)).toThrow('逐项');expect(s).toEqual(before);});
 it('客户通过、签署证明、PMO最终确认独立，确认不能重复',()=>{const initial=passCustomer();let s=initial.s;const next=initial.next;expect(s.acceptanceDetails[next.id].confirmedAt).toBeUndefined();expect(()=>transition(s,{type:'confirm-acceptance',id:next.id,proofFiles:[],opinion:'确认'},pmo)).toThrow('签署');s=transition(s,{type:'save-acceptance-proof',id:next.id,proofFiles:['园区客户签署确认函.pdf']},pm);s=transition(s,{type:'confirm-acceptance',id:next.id,proofFiles:['园区客户签署确认函.pdf'],opinion:'签章与范围核验一致'},pmo);expect(s.acceptanceDetails[next.id].confirmedBy).toBe('李主任');expect(s.projects.find((p)=>p.id==='P-006')?.subPhase).toBe('项目结算');expect(()=>transition(s,{type:'confirm-acceptance',id:next.id,proofFiles:['确认函.pdf'],opinion:'再次确认'},pmo)).toThrow('尚未最终确认');});
 it('分批分税点按原单累计，重复审批与超合同被拒绝',()=>{const initial=passCustomer();let s=initial.s;const next=initial.next;let draft=reportDraft(s,next);draft.taxLines=[{taxRate:6,amount:100},{taxRate:13,amount:200}];s=transition(s,{type:'save-acceptance-report',report:draft,submit:true},pm);const id=s.acceptanceReports[0].id;expect(confirmedReportedAmount(s,draft.contractId)).toBe(0);s=transition(s,{type:'confirm-acceptance-report',id,approve:true,opinion:'按合同核对通过'},finance);expect(confirmedReportedAmount(s,draft.contractId)).toBe(300);expect(()=>transition(s,{type:'confirm-acceptance-report',id,approve:true,opinion:'重复'},finance)).toThrow();draft=reportDraft(s,next,'B02',2000);expect(()=>transition(s,{type:'save-acceptance-report',report:draft,submit:true},pm)).toThrow('超过合同');draft=reportDraft(s,next,'B02',100);s=transition(s,{type:'save-acceptance-report',report:draft,submit:true},pm);s=transition(s,{type:'confirm-acceptance-report',id:s.acceptanceReports[1].id,approve:true,opinion:'通过'},finance);expect(confirmedReportedAmount(s,draft.contractId)).toBe(400);expect(reportAmount(s.acceptanceReports[0])).toBe(300);});
 it('报验批次唯一、税点唯一，待确认占用额度，退回后可编辑',()=>{const initial=passCustomer();let s=initial.s;const next=initial.next;const draft=reportDraft(s,next,'A',1800);s=transition(s,{type:'save-acceptance-report',report:draft,submit:true},pm);expect(()=>transition(s,{type:'save-acceptance-report',report:draft,submit:true},pm)).toThrow('重复');expect(()=>transition(s,{type:'save-acceptance-report',report:reportDraft(s,next,'B',100),submit:true},pm)).toThrow('超过合同');const id=s.acceptanceReports[0].id;s=transition(s,{type:'confirm-acceptance-report',id,approve:false,opinion:'补充范围'},finance);s=transition(s,{type:'save-acceptance-report',id,report:reportDraft(s,next,'A',1500),submit:false},pm);expect(s.acceptanceReports).toHaveLength(1);expect(s.acceptanceReports[0].status).toBe('草稿');});
 it('无供应商项目明确不适用；历史来源与动态来源均保留',()=>{const s=createBusinessState();const absent='P-EXTRA';expect(supplierSources(s,absent)).toEqual([]);expect(supplierSources(s,'P-006').length).toBeGreaterThan(0);expect(s.acceptances.filter((a)=>a.projectId==='P-006'&&a.type==='供应商验收').every((a)=>!!s.acceptanceDetails[a.id].supplierSourceId)).toBe(true);});
 it('已锁定项目禁止新增验收，草稿不改变财务成本',()=>{const {s,next}=passCustomer();const costs=structuredClone(s.costs);const draft=reportDraft(s,next);const edited=transition(s,{type:'save-acceptance-report',report:draft,submit:false},pm);expect(edited.costs).toEqual(costs);s.lockedProjects.push('P-006');expect(()=>transition(s,{type:'save-acceptance-report',report:draft,submit:true},pm)).toThrow('建设期已结束');});
 it('供应商验收绑定原合同，证明必填，通过只更新履约不增加成本',()=>{let s=createBusinessState();s.costOrders.push({id:'CO-ACCEPT-TEST',projectId:'P-006',kind:'outsource',subjectId:'SUB-02',subjectName:'外包',title:'园区联调服务',amount:20,supplier:'园区服务商',contractNo:'TEST-VENDOR-001',scope:'接口联调',baselineId:s.baselines.find((b)=>b.projectId==='P-006'&&b.status==='已生效')!.id,dueDate:'2026-09-09',applicant:pm.name,applicantId:pm.id,submittedAt:'2026-09-01',status:'已批准',progress:100,recognized:0,history:[]});const priorCosts=structuredClone(s.costs);s=transition(s,{type:'submit-acceptance',projectId:'P-006',kind:'供应商验收',detail:{scope:'接口联调',plannedDate:'2026-09-10',method:'现场验收',customerContact:'',participants:'采购、技术验收组',supplierSourceId:'CO-ACCEPT-TEST'}},pm);const id=s.acceptances.at(-1)!.id;const review={type:'review-acceptance' as const,id,passed:true,checks:checkNames('供应商验收').map((name)=>({name,passed:true,note:'合同逐项核对符合'})),opinion:'通过',process:'采购组织现场验收'};expect(()=>transition(s,review,pmo)).toThrow('证明');s=transition(s,{...review,proofFiles:['供应商履约验收.pdf']},pmo);expect(s.costOrders.find((o)=>o.id==='CO-ACCEPT-TEST')?.status).toBe('验收通过');expect(s.costs).toEqual(priorCosts);expect(s.acceptanceDetails[id].supplierSourceId).toBe('CO-ACCEPT-TEST');});

});
