import { describe, expect, it } from 'vitest';
import { createBusinessState, createDemoBusinessState, transition, type Actor } from '@/mock/business';
import { PLANNING_PROJECT_ID as id, validatePlanning } from '@/mock/budget';
const pm:Actor={id:'U-001',name:'张建国',role:'project-manager'};const pmo:Actor={id:'U-002',name:'李主任',role:'pmo'};const leader:Actor={id:'U-003',name:'王总',role:'executive'};
function reviewed(){let s=transition(createBusinessState(),{type:'submit-planning',projectId:id},pm);s=transition(s,{type:'review-planning',id:'PREVIEW-1',result:'通过',opinion:'资源与交付周期可行',rectifications:[]},pmo);return s;}
describe('新策划期 / WBS完整性 / 评审版本',()=>{
 it('独立新项目有唯一来源、冻结概算、零成本且无生效基线，不改八个固定故事',()=>{const s=createBusinessState(),p=s.projects.find(p=>p.id===id)!;expect(s.projects[0].budgetAmount).toBe(2847.7);expect(p.phase).toBe('立项');expect(p.actualCost).toBe(0);expect(s.opportunities.find(o=>o.id===p.opportunityId)?.earlyInvestmentUsed).toBe(0);expect(s.estimates.find(e=>e.id===p.frozenEstimateVersionId)?.opportunityId).toBe(p.opportunityId);expect(s.baselines.some(b=>b.projectId===id)).toBe(false);expect(validatePlanning(s.planningDrafts[id],id)).toEqual([]);});
 it('层级/依赖循环、失效成员、非法日期、空完成条件和重复编码不能导入，失败无部分写入',()=>{const s=createBusinessState(),plan=s.planningDrafts[id];const original=structuredClone(s);const a={...plan.tasks[0],id:'A',taskCode:'1',predecessorIds:['B']};const b={...a,id:'B',taskCode:'2',predecessorIds:['A']};expect(validatePlanning({...plan,tasks:[a,b]},id).join()).toContain('循环');expect(validatePlanning({...plan,tasks:[{...a,parentId:'B'},{...b,parentId:'A'}]},id).join()).toContain('循环');for(const edit of [{ownerId:'U-NONE'},{endDate:'2026-02-30'},{completionCondition:''},{endDate:'2028-01-01'}]){expect(()=>transition(s,{type:'save-planning',projectId:id,expectedRevision:1,plan:{...plan,tasks:[{...plan.tasks[0],...edit}]}},pm)).toThrow();}expect(s).toEqual(original);});
 it('评审冻结提交快照，整改必填负责人期限，回复后重提交新轮次，原版本保留',()=>{let s=transition(createBusinessState(),{type:'submit-planning',projectId:id},pm);const snapshot=structuredClone(s.planningReviews[0].snapshot);expect(()=>transition(s,{type:'save-planning',projectId:id,expectedRevision:1,plan:s.planningDrafts[id]},pm)).toThrow('评审中');expect(()=>transition(s,{type:'review-planning',id:'PREVIEW-1',result:'通过',opinion:'同意',rectifications:[]},pm)).toThrow('PMO');expect(()=>transition(s,{type:'review-planning',id:'PREVIEW-1',result:'整改',opinion:'补充验收依据',rectifications:[]},pmo)).toThrow('整改');s=transition(s,{type:'review-planning',id:'PREVIEW-1',result:'整改',opinion:'补充范围',rectifications:[{id:'R1',content:'明确接入边界',ownerId:'U-001',deadline:'2026-09-15'}]},pmo);expect(()=>transition(s,{type:'submit-planning',projectId:id},pm)).toThrow('回复');s=transition(s,{type:'reply-planning',id:'PREVIEW-1',rectificationId:'R1',reply:'已补充接入100台设备边界'},pm);s=transition(s,{type:'save-planning',projectId:id,expectedRevision:1,plan:{...s.planningDrafts[id],scope:'100台设备接入，不含设备硬件供货'}},pm);s=transition(s,{type:'submit-planning',projectId:id},pm);expect(s.planningReviews).toHaveLength(2);expect(s.planningReviews[0].snapshot).toEqual(snapshot);expect(s.planningReviews[1].revision).toBe(2);expect(s.planningReviews[1].snapshot.scope).toContain('不含');});
 it('里程碑缺交付物/验收依据阻断；已通过草稿再编辑取消通过资格',()=>{let s=reviewed();expect(validatePlanning({...s.planningDrafts[id],milestones:s.planningDrafts[id].milestones.map(m=>({...m,acceptanceBasis:'',requiredDeliverables:[]}))},id).length).toBeGreaterThan(0);s=transition(s,{type:'save-planning',projectId:id,expectedRevision:1,plan:{...s.planningDrafts[id],scope:'调整范围'}},pm);expect(s.planningDrafts[id].status).toBe('草稿');});
});
describe('预算通过与PMO确认独立 / 完整基线不可变',()=>{
 it('首次预算须计划评审通过；预算通过不生效，PMO确认冻结完整范围/计划/资源/预算，重复确认阻断',()=>{let s=createBusinessState();const budget={...s.budgets[0],id:'DRAFT-NEW',projectId:id,totalAmount:600,items:[{subjectId:'SUB-01',subjectName:'交付人力',amount:600}],laborCost:600,procurementCost:0,outsourceCost:0,expenseCost:0,reserveCost:0};expect(()=>transition(s,{type:'submit-budget',projectId:id,budget,reason:'首次预算'},pm)).toThrow('计划评审');s=reviewed();s=transition(s,{type:'submit-budget',projectId:id,budget,reason:'首次预算'},pm);expect(()=>transition(s,{type:'save-planning',projectId:id,expectedRevision:1,plan:s.planningDrafts[id]},pm)).toThrow('预算审批');s=transition(s,{type:'review',approvalId:'APR-1',approve:true,opinion:'预算合理'},pmo);expect(s.projects.find(p=>p.id===id)?.budgetAmount).toBe(0);expect(s.baselines.some(b=>b.projectId===id)).toBe(false);expect(()=>transition(s,{type:'confirm-budget-baseline',approvalId:'APR-1'},leader)).toThrow('PMO');s=transition(s,{type:'confirm-budget-baseline',approvalId:'APR-1'},pmo);const base=s.baselines.find(b=>b.projectId===id)!;expect(base.version).toBe('V1.0');expect(base.snapshot?.planningReviewId).toBe('PREVIEW-1');expect(base.snapshot?.budget.totalAmount).toBe(600);expect(base.snapshot?.resources).toHaveLength(2);expect(s.tasks.filter(t=>t.projectId===id)).toEqual(base.snapshot?.tasks);expect(s.materials.filter(m=>m.projectId===id).map(m=>m.name)).toContain('验收确认函');expect(s.planningDrafts[id].status).toBe('已冻结');expect(()=>transition(s,{type:'save-planning',projectId:id,expectedRevision:1,plan:s.planningDrafts[id]},pm)).toThrow('生效计划');expect(()=>transition(s,{type:'confirm-budget-baseline',approvalId:'APR-1'},pmo)).toThrow('已确认');s.tasks.find(t=>t.projectId===id)!.name='执行记录更名';expect(base.snapshot?.tasks[0].name).not.toBe('执行记录更名');});
 it('既有预算确认不修改实际/滚动，来源基线失效与建设冻结均阻断',()=>{const initial=createDemoBusinessState();const a=initial.approvals[0];let s=transition(initial,{type:'review',approvalId:a.id,approve:true,opinion:'同意'},leader);expect(s.projects[0].budgetAmount).toBe(initial.projects[0].budgetAmount);s.constructionFreezes[a.projectId]={requestId:'S1',reason:'结算审核'};expect(()=>transition(s,{type:'confirm-budget-baseline',approvalId:a.id},pmo)).toThrow('冻结');delete s.constructionFreezes[a.projectId];s=transition(s,{type:'confirm-budget-baseline',approvalId:a.id},pmo);expect(s.projects[0].actualCost).toBe(initial.projects[0].actualCost);expect(s.projects[0].rollingCost).toBe(initial.projects[0].rollingCost);const stale=transition(initial,{type:'review',approvalId:a.id,approve:true,opinion:'同意'},leader);stale.baselines.find(b=>b.id===a.baseline.id)!.status='历史';expect(()=>transition(stale,{type:'confirm-budget-baseline',approvalId:a.id},pmo)).toThrow('基线已变化');});
 it('项目变更审批仍直接追加基线且保留来源变更ID',()=>{const s=createDemoBusinessState();const a=s.approvals.find(a=>a.kind==='change')!;const next=transition(s,{type:'review',approvalId:a.id,approve:true,opinion:'同意范围内成本变更'},leader);expect(next.baselines.some(b=>b.id===`BASE-${a.id}`)).toBe(true);expect(next.changes.find(c=>c.id===a.sourceChangeId)?.newBaselineId).toBe(`BASE-${a.id}`);expect(next.baselines.find(b=>b.id===`BASE-${a.id}`)?.snapshot?.budget.totalAmount).toBe(a.budget.totalAmount);});
});

it('无预算时概算和新增实际科目仍可复算，预算保持零且明确引用冻结版本',async()=>{
 const {selectFourCalculations}=await import('@/mock/selectors');const s=createBusinessState();const p=s.projects.find(p=>p.id===id)!;
 s.estimates.unshift({...s.estimates.find(e=>e.id==='EST-PLAN-001')!,id:'OTHER-FROZEN',totalCost:990});
 s.costs.push({id:'COST-NEW',projectId:id,subjectId:'EXTRA-SUB',subjectName:'前期检测',type:'expense',amount:10,occurredDate:'2026-09-09',description:'已确认检测'});p.actualCost=10;
 const result=selectFourCalculations(p,s);expect(result.estimate?.id).toBe('EST-PLAN-001');expect(result.budget).toBeUndefined();expect(result.subjects.reduce((n,r)=>n+r.budget,0)).toBe(0);expect(result.subjects.reduce((n,r)=>n+r.estimate,0)).toBe(700);expect(result.subjects.reduce((n,r)=>n+r.actual,0)).toBe(10);expect(result.actual).toBe(10);
});
it('直接动作不能删模板里程碑、假冒项目成员或扩展批准周期',()=>{
 const s=createBusinessState(),plan=s.planningDrafts[id];
 for(const next of [{...plan,milestones:plan.milestones.slice(1)},{...plan,resources:[...plan.resources,{...plan.resources[0],userId:'U-050'}]},{...plan,plannedEndDate:'2027-12-31'}])expect(()=>transition(s,{type:'save-planning',projectId:id,plan:next,expectedRevision:1},pm)).toThrow();
});
