import { describe,it,expect } from 'vitest';
import { createBusinessState,transition,type Actor } from '@/mock/business-domain';
import { collectConfiguredAlerts,configuredSubjects,mapCostSource,selectConfiguredHealth,selectCostRate } from '@/mock/configuration-finance';
import { selectFourCalculations } from '@/mock/selectors';
import { getBudgetDraft,lineAmount,toBudgetVersion } from '@/mock/budget-drafts';
const finance:Actor={id:'U-004',name:'刘敏',role:'finance'},pmo:Actor={id:'U-002',name:'李主任',role:'pmo'},pm:Actor={id:'U-001',name:'张建国',role:'project-manager'};
describe('财务配置版本与消费快照',()=>{
 it('父科目不可入账、同来源不可重复映射、已用科目不可删除',()=>{const s=createBusinessState(),v=s.financeConfiguration.subjects[0];expect(configuredSubjects(s).some(r=>r.id==='SUB-04')).toBe(false);expect(()=>mapCostSource(s,'expense','SUB-04')).toThrow('叶子');const save=(value:typeof v)=>transition(s,{type:'finance-config-save',kind:'subjects',sourceId:v.id,value:{...value,changeReason:'规则检查'}},finance);expect(()=>save({...v,subjects:v.subjects.filter(x=>x.id!=='SUB-04-1')})).toThrow('已使用');expect(()=>save({...v,mappings:[...v.mappings,v.mappings[0]]})).toThrow('只能映射');expect(()=>save({...v,mappings:[{sourceType:'expense',sourceCode:'ERP',subjectId:'SUB-04'}]})).toThrow('父子');});
 it('新映射发布仅影响新来源，旧四算与凭证保持金额守恒',()=>{let s=createBusinessState();const before=structuredClone(s.costs),summary=selectFourCalculations(s.projects[0],s);const v=s.financeConfiguration.subjects[0];s=transition(s,{type:'finance-config-save',kind:'subjects',sourceId:v.id,value:{...v,changeReason:'接入差旅来源',mappings:[...v.mappings,{sourceType:'expense',sourceCode:'ERP-TRAVEL',subjectId:'SUB-04-2'}]}},finance);expect(()=>mapCostSource(s,'expense','ERP-TRAVEL')).toThrow();s=transition(s,{type:'finance-config-publish',kind:'subjects',id:'SUBJECTS-V2'},finance);expect(mapCostSource(s,'expense','ERP-TRAVEL')).toMatchObject({id:'SUB-04-2',mappingVersion:'SUBJECTS-V2'});expect(s.costs).toEqual(before);expect(selectFourCalculations(s.projects[0],s).actual).toBe(summary.actual);expect(selectFourCalculations(s.projects[0],s).subjects.reduce((n,i)=>n+i.actual,0)).toBeCloseTo(summary.actual,5);});
 it('单价按人员/职级/岗位/地域及日期匹配，成本维护权限严格',()=>{let s=createBusinessState();const v=s.financeConfiguration.rates[0];expect(()=>transition(s,{type:'finance-config-save',kind:'rates',sourceId:v.id,value:{...v,changeReason:'越权修改'}},pmo)).toThrow('权限');s=transition(s,{type:'finance-config-save',kind:'rates',value:{...v,id:'',key:'RATE-P8-FZ',name:'福州架构师P8',userId:'all',grade:'P8',position:'架构师',region:'福州',hourlyYuan:250,effectiveDate:'2026-09-09',changeReason:'新增岗位标准'}},finance);s=transition(s,{type:'finance-config-publish',kind:'rates',id:'RATE-P8-FZ-V1'},finance);const ctx={userId:'U-OTHER',grade:'P8',position:'架构师',region:'福州',orgId:'D-007',projectType:'软件开发'};expect(selectCostRate(s,ctx).hourlyYuan).toBe(250);expect(selectCostRate(s,{...ctx,date:'2026-09-08'}).hourlyYuan).toBe(120);expect(selectCostRate(s,{...ctx,region:'厦门'}).hourlyYuan).toBe(120);});
 it('新工时使用新单价，已提交工时审核沿用原金额与版本',()=>{let s=createBusinessState();const action={type:'submit-labor' as const,projectId:'P-001',taskId:'TSK-0001',date:'2026-09-09',hours:4,description:'联调测试'};s=transition(s,action,pm);expect(s.laborEntries[0]).toMatchObject({hourlyYuan:150,amount:0.06,rateVersion:'RATE-PM-V1'});const v=s.financeConfiguration.rates.find(r=>r.key==='RATE-PM')!;s=transition(s,{type:'finance-config-save',kind:'rates',sourceId:v.id,value:{...v,hourlyYuan:200,changeReason:'岗位成本调整'}},finance);s=transition(s,{type:'finance-config-publish',kind:'rates',id:'RATE-PM-V2'},finance);s=transition(s,{type:'review-labor',id:'LAB-1',approve:true,opinion:'工作完成'},pm);expect(s.costs.find(c=>c.sourceId==='LAB-1')?.amount).toBe(0.06);s=transition(s,{...action,date:'2026-09-08'},pm);expect(s.laborEntries[1]).toMatchObject({hourlyYuan:200,rateVersion:'RATE-PM-V2',amount:0.08});});
 it('预算新行冻结单价，历史无快照沿用原测算，伪造费率由保存层覆盖',()=>{let s=createBusinessState();const draft=getBudgetDraft(s,'P-PLAN-001');const old=lineAmount(draft.lines[0]);draft.lines[0].hourlyYuan=1;draft.lines[0].rateVersion='伪造';s=transition(s,{type:'save-budget-draft',draft,expectedRevision:0},pm);const line=s.budgetDrafts['P-PLAN-001'].lines[0];expect(line.hourlyYuan).toBe(150);expect(lineAmount(line)).toBe(old);s.financeConfiguration.rates.find(r=>r.key==='RATE-PM')!.hourlyYuan=999;expect(lineAmount(line)).toBe(old);const legacy={...line,hourlyYuan:undefined,rateVersion:undefined};expect(lineAmount(legacy)).toBe(old);});
 it('预警默认故事保持，发布新阈值统一重算健康并保留原业务下钻，无真实通知',()=>{let s=createBusinessState();expect(selectConfiguredHealth(s,s.projects[0]).level).toBe('yellow');const v=s.financeConfiguration.alerts.find(r=>r.kind==='cost')!;s=transition(s,{type:'finance-config-save',kind:'alerts',sourceId:v.id,value:{...v,highThreshold:4,warningThreshold:2,changeReason:'下调成本演示阈值'}},pmo);expect(s.projects[0].health).toBe('yellow');s=transition(s,{type:'finance-config-publish',kind:'alerts',id:'ALERT-COST-V2'},pmo);expect(s.projects[0].health).toBe('red');const alerts=collectConfiguredAlerts(s,[s.projects[0]]);const hit=alerts.find(a=>a.kind==='cost');expect(hit).toMatchObject({ruleId:'ALERT-COST-V2',route:'/projects/P-001/dynamic-accounting',severity:3});expect(hit?.channels).toEqual(['站内模拟消息']);expect(s.audit.at(-1)?.action).toBe('finance-config-publish');});
 it('运维提醒仅读真实周期，不把建设计划结束冒充维保期限',()=>{const s=createBusinessState();const p=s.projects[0];p.phase='运维';p.plannedEndDate='2026-01-01';expect(collectConfiguredAlerts(s,[p]).some(a=>a.kind==='maintenance')).toBe(false);Object.assign(s,{operationCycles:[{id:'OPS-TEST',projectId:p.id,endDate:'2026-09-11',status:'服务中'}]});expect(collectConfiguredAlerts(s,[p]).find(a=>a.kind==='maintenance')?.route).toBe('/operations/OPS-TEST');});
});

it('发布新增费用叶子后预算汇总包含新科目，明细与总额守恒',()=>{let s=createBusinessState();const v=s.financeConfiguration.subjects[0];s=transition(s,{type:'finance-config-save',kind:'subjects',sourceId:v.id,value:{...v,changeReason:'补充培训成本',subjects:[...v.subjects,{id:'SUB-04-5',name:'交付培训费',parentId:'SUB-04',kind:'expense',enabled:true}],mappings:[...v.mappings,{sourceType:'expense',sourceCode:'SUB-04-5',subjectId:'SUB-04-5'}]}},finance);s=transition(s,{type:'finance-config-publish',kind:'subjects',id:'SUBJECTS-V2'},finance);const draft=getBudgetDraft(s,'P-PLAN-001');draft.lines.push({...draft.lines[0],id:'NEW-TRAINING',kind:'expense',subjectId:'SUB-04-5',name:'客户培训',amount:12,plannedDays:0,travelDays:0});s=transition(s,{type:'save-budget-draft',draft,expectedRevision:0},pm);const b=toBudgetVersion(s.budgetDrafts['P-PLAN-001'],pm);expect(b.items.find(i=>i.subjectId==='SUB-04-5')).toMatchObject({subjectName:'交付培训费',amount:12});expect(b.totalAmount).toBeCloseTo(b.items.reduce((sum,item)=>sum+item.amount,0),6);});
it('新差旅行使用日标准快照，发布调价后已有预算行不重计',()=>{let s=createBusinessState();const draft=getBudgetDraft(s,'P-PLAN-001');draft.lines.push({...draft.lines[0],id:'TRAVEL',kind:'expense',subjectId:'SUB-04-2',name:'现场差旅',amount:0,plannedDays:0,travelDays:3});s=transition(s,{type:'save-budget-draft',draft,expectedRevision:0},pm);expect(lineAmount(s.budgetDrafts['P-PLAN-001'].lines.at(-1)!)).toBe(0.12);const rate=s.financeConfiguration.rates.find(r=>r.key==='RATE-PM')!;s=transition(s,{type:'finance-config-save',kind:'rates',sourceId:rate.id,value:{...rate,expenseDailyYuan:800,changeReason:'差旅调整'}},finance);s=transition(s,{type:'finance-config-publish',kind:'rates',id:'RATE-PM-V2'},finance);s=transition(s,{type:'save-budget-draft',draft:s.budgetDrafts['P-PLAN-001'],expectedRevision:1},pm);expect(lineAmount(s.budgetDrafts['P-PLAN-001'].lines.at(-1)!)).toBe(0.12);});
