import { describe,it,expect } from 'vitest';
import { createBusinessState,type Actor } from '@/mock/business';
import { applyAccessConfiguration,buildAuditChanges,canAccessAction,canAccessPage,canAccessProject,canViewSensitiveField,createAccessConfiguration,redactAuditEvent,selectAccessPolicy } from '@/mock/configuration-access';
import type { AuditEvent } from '@/models/configuration-access';
const admin:Actor={id:'U-ADMIN',name:'Admin',role:'admin'},pm:Actor={id:'U-001',name:'张建国',role:'project-manager'},finance:Actor={id:'U-004',name:'刘敏',role:'finance'},tech:Actor={id:'U-005',name:'赵工',role:'solution-tech'};
function fixture(){return Object.assign(createBusinessState(),{accessConfiguration:createAccessConfiguration()});}
describe('权限策略白名单与审计差异',()=>{
 it('默认仅允许角色白名单，未知动作及跨职责授权始终拒绝',()=>{const s=fixture();expect(canAccessAction(s,pm,'submit-budget-draft')).toBe(true);expect(canAccessAction(s,pm,'finance-config-publish')).toBe(false);expect(canAccessAction(s,admin,'delete-audit-log')).toBe(false);expect(canAccessPage(s,admin,'CF-07')).toBe(true);expect(canAccessPage(s,pm,'CF-07')).toBe(false);const value={...selectAccessPolicy(s,pm.role)!,changeReason:'尝试扩大职责',actions:['finance-config-publish']};expect(()=>applyAccessConfiguration(s,{type:'access-policy-save',sourceId:value.id,value},admin)).toThrow('跨职责');s.accessConfiguration.versions.find(v=>v.role===pm.role)!.actions.push('finance-config-publish');expect(canAccessAction(s,pm,'finance-config-publish')).toBe(false);});
 it('草稿不影响当前访问，发布立即收紧页面及动作，旧策略版本不被改写',()=>{const s=fixture(),old=structuredClone(selectAccessPolicy(s,pm.role)!);const value={...old,changeReason:'暂时停用预算编辑',pages:old.pages.filter(p=>p!=='YS-09'),actions:old.actions.filter(a=>a!=='submit-budget-draft')};const id=applyAccessConfiguration(s,{type:'access-policy-save',sourceId:old.id,value},admin);expect(canAccessAction(s,pm,'submit-budget-draft')).toBe(true);applyAccessConfiguration(s,{type:'access-policy-publish',id},admin);expect(canAccessAction(s,pm,'submit-budget-draft')).toBe(false);expect(canAccessPage(s,pm,'YS-09')).toBe(false);expect(s.accessConfiguration.versions.find(v=>v.id===old.id)).toEqual(old);});
 it('指定组织与租户受约束，不能配置管理员自锁或越权维护',()=>{const s=fixture(),value={...selectAccessPolicy(s,finance.role)!,dataScope:'organizations' as const,orgIds:['D-007'],changeReason:'限本部门'};expect(()=>applyAccessConfiguration(s,{type:'access-policy-save',value},finance)).toThrow('管理员');const id=applyAccessConfiguration(s,{type:'access-policy-save',sourceId:value.id,value},admin);applyAccessConfiguration(s,{type:'access-policy-publish',id},admin);expect(s.projects.filter(p=>canAccessProject(s,finance,p)).every(p=>p.departmentId==='D-007')).toBe(true);expect(canAccessProject(s,finance,s.projects[0],'OTHER-TENANT')).toBe(false);const a=selectAccessPolicy(s,admin.role)!;const aid=applyAccessConfiguration(s,{type:'access-policy-save',sourceId:a.id,value:{...a,enabled:false,changeReason:'停用自己'}},admin);expect(()=>applyAccessConfiguration(s,{type:'access-policy-publish',id:aid},admin)).toThrow('锁死');});
 it('退出与参与期限实时收回关系权限，不删除团队与责任历史，配置all也不越过职责上限',()=>{const s=fixture(),p=s.projects[0],team=s.projectTeams[p.id];team.members.push({userId:tech.id,name:tech.name,role:'技术',departmentId:'D-003',active:true,startDate:'2026-01-01',endDate:'2026-12-31',allocation:20,plannedHours:20,keyPosition:false});p.memberIds=[...(p.memberIds??[]),tech.id];expect(canAccessProject(s,tech,p)).toBe(true);const history=structuredClone(team.history);team.members.find(m=>m.userId===tech.id)!.active=false;expect(canAccessProject(s,tech,p)).toBe(false);const policy=selectAccessPolicy(s,tech.role)!;policy.dataScope='all';policy.projectRelationRequired=false;expect(canAccessProject(s,tech,p)).toBe(false);expect(team.history).toEqual(history);expect(team.members.some(m=>m.userId===tech.id)).toBe(true);});
 it('未来版本尚不生效，停用版本不会回退已被替换的角色策略',()=>{const s=fixture(),v=selectAccessPolicy(s,finance.role)!;const id=applyAccessConfiguration(s,{type:'access-policy-save',sourceId:v.id,value:{...v,enabled:false,effectiveDate:'2027-01-01',changeReason:'计划停用'}},admin);applyAccessConfiguration(s,{type:'access-policy-publish',id},admin);expect(selectAccessPolicy(s,finance.role)?.id).toBe(v.id);s.accessConfiguration.versions.find(v=>v.id===id)!.effectiveDate='2026-01-01';expect(selectAccessPolicy(s,finance.role)).toBeUndefined();});
 it('审计仅比较真实关联对象变化，捕获新增/删除，忽略其他项目及日志自身',()=>{const before=fixture(),after=structuredClone(before);after.projects[0].rollingCost+=20;after.projects[1].rollingCost+=30;after.costs.push({id:'TEST-COST',projectId:before.projects[0].id,type:'expense',subjectId:'SUB-04-4',subjectName:'其他期间费用',amount:20,occurredDate:'2026-09-09',sourceId:'VOUCHER-X',description:'补充费用'});after.audit.push({id:'AUD-X',actor:'财务',date:'2026-09-09',action:'confirm-cost',target:before.projects[0].id});const changes=buildAuditChanges(before,after,before.projects[0].id);expect(changes.some(c=>c.path.includes('projects[P-001].rollingCost')&&c.after===before.projects[0].rollingCost+20)).toBe(true);expect(changes.some(c=>c.path.includes('TEST-COST')&&c.before===null)).toBe(true);expect(changes.some(c=>c.path.includes('P-002')||c.path.startsWith('audit'))).toBe(false);expect(buildAuditChanges(after,before,'TEST-COST')[0].after).toBe(null);expect(before.costs.some(c=>c.id==='TEST-COST')).toBe(false);});
 it('字段与嵌套数组均脱敏，历史无差异不补造，原审计事件保持不变',()=>{const s=fixture(),policy=selectAccessPolicy(s,pm.role)!;const event:AuditEvent={id:'AUD-1',actor:'财务',action:'save',target:'P-001',date:'2026-09-09',changes:[{path:'cost.hourlyYuan',label:'小时费率',before:150,after:200,sensitive:'labor-rate'},{path:'budget.details',label:'明细',before:[],after:[{hourlyYuan:180,plannedDays:10}]}]};const redacted=redactAuditEvent(event,policy);expect(redacted.changes?.[0].after).toBe('***（已脱敏）');expect((redacted.changes?.[1].after as {hourlyYuan:string}[])[0].hourlyYuan).toBe('***（已脱敏）');expect(event.changes?.[0].after).toBe(200);expect(canViewSensitiveField(s,finance,'labor-rate')).toBe(true);expect(canViewSensitiveField(s,pm,'labor-rate')).toBe(false);expect(redactAuditEvent({...event,changes:undefined},policy).changes).toBeUndefined();});
});
it('被任命人与运维接收人可访问待接受职责，结束后不残留授权',()=>{const s=fixture(),p=s.projects[0];const team=s.projectTeams[p.id];team.members=team.members.filter(m=>m.userId!==tech.id);p.memberIds=[];team.appointments.push({id:'APPT-TEST',userId:tech.id,name:tech.name,status:'待接受',nominatedAt:'2026-09-09',nominatedBy:'PMO'});expect(canAccessProject(s,tech,p)).toBe(true);expect(canAccessAction(s,tech,'respond-pm')).toBe(true);team.appointments.at(-1)!.status='已拒绝';expect(canAccessProject(s,tech,p)).toBe(false);s.operationHandovers[p.id]={id:'HANDOVER-TEST',projectId:p.id,contractId:'CONTRACT-TEST',required:true,basis:'合同维保',startDate:'2026-09-09',endDate:'2027-09-08',receiverId:tech.id,teamIds:[tech.id],scope:'维保',sla:'按合同',systemInfo:'服务实例',legacyIssues:'无',accounts:'运维账号',documents:'移交材料',status:'待接收',submittedBy:'项目经理',submittedAt:'2026-09-09'};expect(canAccessProject(s,tech,p)).toBe(true);expect(canAccessAction(s,tech,'accept-operation-handover')).toBe(true);s.operationHandovers[p.id].status='已接收';expect(canAccessProject(s,tech,p)).toBe(false);});

it('配置审批节点给出的动态角色按当前轮次授予，指定对象及收紧策略仍生效',()=>{
 const s=fixture();const progress={snapshot:{ruleId:'RULE-TEST',ruleVersion:'RULE-TEST-V1',reason:'指定财务节点',nodes:[{name:'财务决策',roles:['finance' as const],mode:'all' as const,timeoutDays:3}]},node:0,enteredAt:'2026-09-09',reviews:[] as import('@/models/configuration').ApprovalProgress['reviews'],status:'待审批' as const};
 const dynamic={...s,initiations:[{id:'INIT-TEST',status:'待决策',rounds:[{status:'待决策',approvalProgress:progress}]}]};
 expect(canAccessAction(dynamic,finance,'decide-initiation','INIT-TEST')).toBe(true);expect(canAccessAction(dynamic,finance,'decide-initiation','OTHER')).toBe(false);expect(canAccessAction(dynamic,tech,'decide-initiation','INIT-TEST')).toBe(false);
 progress.reviews.push({node:0,role:'finance',by:finance.name,approve:true,opinion:'通过',date:'2026-09-09'});expect(canAccessAction(dynamic,finance,'decide-initiation','INIT-TEST')).toBe(false);progress.reviews=[];
 dynamic.initiations[0].status='通过';expect(canAccessAction(dynamic,finance,'decide-initiation','INIT-TEST')).toBe(false);dynamic.initiations[0].status='待决策';
 selectAccessPolicy(dynamic,finance.role)!.actions=selectAccessPolicy(dynamic,finance.role)!.actions.filter(a=>a!=='decide-initiation');expect(canAccessAction(dynamic,finance,'decide-initiation','INIT-TEST')).toBe(false);
 expect(canAccessAction(dynamic,{role:'pmo'},'decide-initiation','UNSUBMITTED')).toBe(true);
});

it('确认实际收款仅财务白名单可进入，配置仍可收紧',()=>{const s=fixture();expect(canAccessAction(s,finance,'confirm-project-receipt')).toBe(true);for(const role of ['admin','executive','pmo','market','project-manager','solution-tech'] as const)expect(canAccessAction(s,{role},'confirm-project-receipt')).toBe(false);selectAccessPolicy(s,'finance')!.actions=selectAccessPolicy(s,'finance')!.actions.filter(a=>a!=='confirm-project-receipt');expect(canAccessAction(s,finance,'confirm-project-receipt')).toBe(false);});
