import { describe, expect, it } from 'vitest';
import { createBusinessState, transition, type Actor } from '@/mock/business-domain';
import { configuredApprovalTimeout, effectiveVersions, evaluateProjectGrading, instantiateProjectTemplates, reviewConfiguredApproval, selectApprovalRule } from '@/mock/configuration';
import type { ApprovalProgress } from '@/models/configuration';
const pmo:Actor={id:'U-002',name:'李主任',role:'pmo'},finance:Actor={id:'U-004',name:'刘敏',role:'finance'},executive:Actor={id:'U-003',name:'王总',role:'executive'};
describe('配置版本与真实消费者',()=>{
 it('分级新版本发布后影响新评定，不覆盖原项目，未来日期与停用有确定语义',()=>{let state=createBusinessState();const input={amount:3000,strategic:false,risk:'一般',customerLevel:'普通客户',orgId:'D-002',projectType:'all'};const old=evaluateProjectGrading(state,input);const before=state.projects.map(p=>({id:p.id,level:p.level,frozenEstimateVersionId:p.frozenEstimateVersionId}));const value={...state.configuration.grading[0],majorAmount:2500,changeReason:'降低重大金额阈值'};state=transition(state,{type:'configuration-save',kind:'grading',sourceId:value.id,value},pmo);const id=state.configuration.grading.at(-1)!.id;expect(evaluateProjectGrading(state,input).level).toBe(old.level);state=transition(state,{type:'configuration-publish',kind:'grading',id},pmo);expect(evaluateProjectGrading(state,input).level).toBe('重大');expect(old.snapshot.majorAmount).toBe(5000);expect(state.projects.map(p=>({id:p.id,level:p.level,frozenEstimateVersionId:p.frozenEstimateVersionId}))).toEqual(before);const rule=state.configuration.grading.at(-1)!;rule.effectiveDate='2027-01-01';expect(evaluateProjectGrading(state,input).ruleId).toBe('GRADE-V1');rule.effectiveDate='2026-01-01';rule.enabled=false;expect(effectiveVersions(state.configuration.grading)).toHaveLength(0);expect(()=>evaluateProjectGrading(state,input)).toThrow('无生效');});
 it('非配置维护角色拒绝写入，系统必交目录不能降级，实例化一次且不覆盖历史',()=>{let state=createBusinessState();const t=state.configuration.templates[0];expect(()=>transition(state,{type:'configuration-save',kind:'templates',sourceId:t.id,value:{...t,changeReason:'尝试改配置'}},finance)).toThrow('PMO');expect(()=>transition(state,{type:'configuration-save',kind:'templates',sourceId:t.id,value:{...t,changeReason:'删掉必交',rows:[]}},pmo)).toThrow('模板项目');const original=structuredClone(state.materials.filter(m=>m.projectId==='P-001'));const value={...t,changeReason:'加入上线报告',rows:[...t.rows,{id:'go-live',name:'上线报告',phase:'实施',required:true,systemRequired:false,role:'project-manager' as const,timing:'上线前',weight:0}]};state=transition(state,{type:'configuration-save',kind:'templates',sourceId:t.id,value},pmo);state=transition(state,{type:'configuration-publish',kind:'templates',id:state.configuration.templates.at(-1)!.id},pmo);expect(instantiateProjectTemplates(state,'P-001')).toBeGreaterThan(0);expect(instantiateProjectTemplates(state,'P-001')).toBe(0);expect(state.materials.filter(m=>original.some(o=>o.id===m.id))).toEqual(original);expect(state.materials.find(m=>m.projectId==='P-001'&&m.name==='上线报告')?.required).toBe(true);});
 it('审批匹配范围/金额/风险/毛利，提交路径深拷贝且不漂移',()=>{const state=createBusinessState();const ctx={businessType:'early-investment' as const,amount:50,risk:'一般',orgId:'D-002',projectType:'all'};const snapshot=selectApprovalRule(state,ctx);expect(snapshot.ruleId).toBe('APR-EARLY-BASE-V1');expect(selectApprovalRule(state,{...ctx,risk:'高风险'}).nodes[0].roles).toEqual(['executive']);state.configuration.approvals.find(v=>v.id===snapshot.ruleId)!.nodes[0].roles=['finance'];expect(snapshot.nodes[0].roles).toEqual(['pmo']);});
 it('串行节点内会签/或签去重，同角色可处理不同节点，或签拒绝不立即结束',()=>{const progress:ApprovalProgress={snapshot:{ruleId:'TEST',ruleVersion:'TEST-V1',reason:'会签再或签',nodes:[{name:'专业会签',roles:['pmo','finance'],mode:'all',timeoutDays:2},{name:'决策或签',roles:['pmo','executive'],mode:'any',timeoutDays:2}]},node:0,enteredAt:'2026-09-01',reviews:[],status:'待审批'};expect(configuredApprovalTimeout(progress).overdue).toBe(true);reviewConfiguredApproval(progress,pmo,true,'PMO专业通过');expect(progress.node).toBe(0);expect(()=>reviewConfiguredApproval(progress,pmo,true,'重复')).toThrow('重复');expect(()=>reviewConfiguredApproval(progress,executive,true,'越节点')).toThrow('不是');reviewConfiguredApproval(progress,finance,true,'财务通过');expect(progress.node).toBe(1);reviewConfiguredApproval(progress,pmo,false,'建议谨慎');expect(progress.status).toBe('待审批');reviewConfiguredApproval(progress,executive,true,'决策同意');expect(progress.status).toBe('通过');expect(progress.reviews).toHaveLength(4);expect(()=>reviewConfiguredApproval(progress,executive,true,'重复')).toThrow('结束');});
 it('提交的提前投入按原审批节点走完，发布新规则不改变待审单',()=>{let state=createBusinessState();const o=state.opportunities.at(-1)!;o.status='拟立项';o.estimatedAmount=2000;o.earlyInvestmentQuota=0;o.earlyInvestmentUsed=0;const rule=state.configuration.approvals.find(r=>r.key==='APR-EARLY-BASE')!;rule.nodes=[{name:'财务PMO会签',roles:['pmo','finance'],mode:'all',timeoutDays:2},{name:'高阶确认',roles:['executive'],mode:'all',timeoutDays:2}];state=transition(state,{type:'save-early-investment',id:o.id,submit:true,input:{reason:'验证',amount:50,resourceTypes:['人力'],department:'交付部',people:['U-005'],startDate:'2026-09-09',endDate:'2026-09-30',signPlanDate:'2026-10-15',signPlan:'计划签约',riskLevel:'一般',risks:'风险',exitPlan:'退出',estimateId:state.estimates.find(e=>e.opportunityId===o.id&&e.isFrozen)!.id}},{id:'U-006',name:'陈亮',role:'market'});state.configuration.approvals=[];const action={type:'review-early-investment' as const,id:o.id,requestId:state.earlyInvestmentRequests.at(-1)!.id,approve:true,opinion:'通过'};state=transition(state,action,pmo);expect(state.opportunities.at(-1)?.earlyInvestmentQuota).toBe(0);state=transition(state,action,finance);expect(state.earlyInvestmentRequests.at(-1)?.status).toBe('待审批');state=transition(state,action,executive);expect(state.opportunities.at(-1)?.earlyInvestmentQuota).toBe(50);});
});
it('阶段申请冻结释放比例，规则停用后历史待审仍能按快照办理',()=>{let s=createBusinessState();s.projects[0].progressRate=100;s.tasks.filter(t=>t.projectId==='P-001').forEach(t=>{t.progress=100;});s.materials.filter(m=>m.projectId==='P-001').forEach(m=>{m.status='通过';});s.configuration.grading[0].stageReleasePercent=85;s=transition(s,{type:'request-plan',projectId:'P-001',kind:'stage',shiftDays:0,reason:'完成交付申请终验'},{id:'U-001',name:'张建国',role:'project-manager'});s.configuration.grading[0].enabled=false;s=transition(s,{type:'review-plan',id:'PLAN-1',approve:true,opinion:'阶段条件复核通过'},pmo);expect(s.projects[0].releasedBudgetPercent).toBe(85);expect(s.planRequests[0].approvalSnapshot?.releasePercent).toBe(85);});
