import { expect, it } from 'vitest';
import { createBusinessState, transition } from '@/mock/business-domain';
import { costAvailability, type CostOrderAction } from '@/mock/cost-orders';
import { selectFourCalculations } from '@/mock/selectors';
import { sumMoney } from '@/utils/money';
const pm = { id: 'U-001', name: '张建国', role: 'project-manager' as const };
const finance = { id: 'U-004', name: '刘敏', role: 'finance' as const };
const request: Extract<CostOrderAction, { type: 'submit-cost-order' }> = { type: 'submit-cost-order', projectId: 'P-001', kind: 'procurement', subjectId: 'SUB-03', title: '海防网关补充采购', amount: 10, supplier: '福建信创设备公司', contractNo: 'CG-2026-0910', scope: '边缘网关2台', dueDate: '2026-09-20' };
const action = (operation: Extract<CostOrderAction, { type: 'process-cost-order' }>['operation'], progress?: number): CostOrderAction => ({ type: 'process-cost-order', id: 'CO-1', operation, note: '已核验对应业务事实', progress });
it('采购批准增加指定科目承诺，验收入账等额转换且重复入账被拦截', () => {
  const before = createBusinessState(); const original = selectFourCalculations(before.projects[0], before);
  let s = transition(before, request, pm);
  expect(s.projects[0].rollingCost).toBe(before.projects[0].rollingCost);
  expect(() => transition(s, action('approve'), pm)).toThrow();
  s = transition(s, action('approve'), finance);
  expect(s.projects[0].committedCost).toBeCloseTo(before.projects[0].committedCost + 10);
  expect(() => transition(s, action('book'), finance)).toThrow();
  expect(() => transition(s, action('accept'), pm)).toThrow();
  s = transition(s, action('progress', 100), pm); s = transition(s, action('accept'), pm);
  const rollingBeforeBooking = s.projects[0].rollingCost;
  s = transition(s, action('book'), finance);
  expect(s.projects[0].rollingCost).toBe(rollingBeforeBooking);
  expect(s.projects[0].actualCost).toBe(before.projects[0].actualCost + 10);
  expect(s.projects[0].committedCost).toBe(before.projects[0].committedCost);
  const after = selectFourCalculations(s.projects[0], s);
  expect(after.subjects.find((v) => v.subjectId === 'SUB-03')!.committed).toBe(original.subjects.find((v) => v.subjectId === 'SUB-03')!.committed);
  expect(sumMoney(after.subjects.map((v) => v.rolling))).toBe(after.rolling);
  expect(s.costs.filter((c) => c.sourceId === 'CO-1')).toHaveLength(1);
  expect(() => transition(s, action('book'), finance)).toThrow();
  expect(s.costOrders[0].history).toHaveLength(5);
});
it('预算占用防并发超额，驳回释放占用；未签额度和锁定不可绕过', () => {
  const before = createBusinessState(); const available = costAvailability(before, 'P-001', 'SUB-03').available;
  let s = transition(before, { ...request, amount: available }, pm);
  expect(() => transition(s, { ...request, contractNo: 'CG-SECOND', amount: 1 }, pm)).toThrow(/预算不足/);
  s = transition(s, action('reject'), finance);
  expect(costAvailability(s, 'P-001', 'SUB-03').available).toBe(available);
  const unsigned = before.projects[0]; unsigned.isUnsigned = true; unsigned.unsignedLimitQuota = unsigned.actualCost + unsigned.committedCost;
  expect(() => transition(before, request, pm)).toThrow(/未签/);
  unsigned.isUnsigned = false; before.lockedProjects.push('P-001');
  expect(() => transition(before, request, pm)).toThrow(/锁定/);
});
it('外包引用本项目WBS与基线并通过履约验收，费用只在财务入账后进入实际', () => {
  let s = createBusinessState();
  expect(() => transition(s, { ...request, kind: 'outsource', subjectId: 'SUB-02' }, pm)).toThrow(/WBS/);
  s = transition(s, { ...request, kind: 'outsource', subjectId: 'SUB-02', taskId: s.tasks.find((t) => t.projectId === 'P-001')!.id }, pm);
  expect(s.costOrders[0].baselineId).toBe('BASE-VER-001');
  s = transition(s, action('approve'), finance); s = transition(s, action('progress', 60), pm);
  expect(() => transition(s, action('progress', 40), pm)).toThrow();
  expect(() => transition(s, action('accept'), pm)).toThrow();
  s = transition(s, action('progress', 100), pm); s = transition(s, action('accept'), pm); s = transition(s, action('book'), finance);
  s = createBusinessState(); const leaf = selectFourCalculations(s.projects[0], s).subjects.find((v) => v.subjectId.startsWith('SUB-04-') && costAvailability(s, 'P-001', v.subjectId).available > 1)!;
  const original = s.projects[0].actualCost;
  s = transition(s, { ...request, kind: 'expense', subjectId: leaf.subjectId, amount: 1 }, pm);
  s = transition(s, action('approve'), finance); expect(s.projects[0].actualCost).toBe(original);
  s = transition(s, action('book'), finance); expect(s.projects[0].actualCost).toBe(original + 1);
});
