import { describe,expect,it } from 'vitest';
import { createBusinessState,transition,type Actor } from '@/mock/business';
import { estimateFreezeMissing,estimateTotals } from '@/mock/estimates';
import type { CostVersion,SolutionVersion } from '@/models/presales';
const tech:Actor={id:'U-005',name:'赵工',role:'solution-tech'},pmo:Actor={id:'U-002',name:'李主任',role:'pmo'};
function ready(){const state=createBusinessState();const id=state.opportunities.at(-1)!.id;state.opportunities.at(-1)!.status='拟立项';const solution:SolutionVersion={id:'SV-1',version:1,submittedAt:'2026-09-09',submittedBy:'赵工',customerSituation:'数据分散',goals:'统一数据',scope:'20接口',boundaries:'无清洗',architecture:'微服务',implementation:'迭代',deliverables:'部署包',dependencies:'客户接口',assumptions:'接口开放',ownerId:'U-005',participants:[],startDate:'2026-09-09',endDate:'2026-09-20',attachments:['方案.pdf'],changeReason:''};const cost:CostVersion={id:'CV-1',solutionVersionId:'SV-1',version:1,total:113,submittedAt:'2026-09-09',submittedBy:'赵工',solutionFingerprint:'',feasibility:'可行',architecture:'微服务',reuse:'80%',customization:'20接口',environment:'容器',security:'鉴权',dependencies:'客户接口',risk:'交付窗口',attachments:[],lines:[{id:'L1',subjectId:'SUB-03',name:'服务设备',scope:'20接口',quantity:10,unit:'台',unitPrice:10,taxBasis:'不含税',taxRate:13,basis:'采购询价',risk:''}]};state.presales[id]={solutionVersions:[solution],costVersions:[cost],research:[],reviews:[{id:'R1',round:1,solutionVersionId:'SV-1',costVersionId:'CV-1',status:'通过',method:'专家会',plannedDate:'2026-09-09',experts:[],opinions:[],createdAt:'2026-09-09',createdBy:'李主任',corrections:[]}]};return {state:transition(state,{type:'estimate-create-draft',id,reviewId:'R1'},tech),id};}
describe('概算版本与冻结',()=>{
 it('来源双版本、税口径与合计一致，发布不直接冻结',()=>{const {state,id}=ready();const d=state.estimateDrafts[id];expect(estimateTotals(d).cost).toBe(113);const next=transition(state,{type:'estimate-publish',id},tech);const e=next.estimates.at(-1)!;expect(e.totalCost).toBe(113);expect(e.items.reduce((n,i)=>n+i.amount,0)).toBe(e.totalCost);expect(e.isFrozen).toBe(false);expect(next.estimateMeta[e.id].solutionVersionId).toBe('SV-1');expect(next.estimateMeta[e.id].costVersionId).toBe('CV-1');});
 it('修改评审成本仍可存草稿和版本，冻结被阻断',()=>{const {state,id}=ready();const draft=structuredClone(state.estimateDrafts[id]);draft.lines[0].quantity=11;let next=transition(state,{type:'estimate-save-draft',id,draft},tech);next=transition(next,{type:'estimate-publish',id},tech);const e=next.estimates.at(-1)!;expect(estimateFreezeMissing(next,e.id).join()).toContain('偏离');expect(()=>transition(next,{type:'estimate-freeze',id,estimateId:e.id,opinion:'确认'},pmo)).toThrow('重新评审');});
 it('PMO冻结只更新商机引用，旧项目绑定和旧版本均保持',()=>{const readyState=ready();let state=readyState.state;const id=readyState.id;state.projects[0].frozenEstimateVersionId=state.estimates[0].id;const old=structuredClone(state.estimates[0]);const projectId=state.projects[0].frozenEstimateVersionId;state=transition(state,{type:'estimate-publish',id},tech);const first=state.estimates.at(-1)!;expect(()=>transition(state,{type:'estimate-freeze',id,estimateId:first.id,opinion:'确认'},tech)).toThrow('PMO');state=transition(state,{type:'estimate-freeze',id,estimateId:first.id,opinion:'已核对评审明细与税口径'},pmo);expect(state.opportunities.find(o=>o.id===id)?.currentEstimateVersionId).toBe(first.id);expect(state.projects[0].frozenEstimateVersionId).toBe(projectId);expect(state.estimates[0]).toEqual(old);const snapshot=structuredClone(state.estimates.at(-1));state=transition(state,{type:'estimate-publish',id},tech);expect(state.estimates.at(-2)).toEqual(snapshot);expect(state.estimates.at(-1)?.id).not.toBe(first.id);});
 it('零收入不产生NaN，未通过评审不能生成概算',()=>{const {state,id}=ready();const d=structuredClone(state.estimateDrafts[id]);d.income=0;expect(estimateTotals(d).rate).toBeNull();state.presales[id].reviews[0].status='不通过';expect(()=>transition(state,{type:'estimate-create-draft',id,reviewId:'R1'},tech)).toThrow('已通过');});
});
