import {describe,it,expect} from 'vitest';
import {createBusinessState,transition,type Actor} from '@/mock/business';
import {defaultInitiationInput,INITIATION_SIGNATURES} from '@/mock/initiation';
import {opportunityMeta} from '@/mock/opportunities';
import {visibleProjects} from '@/mock/selectors';
const market:Actor={id:'U-006',name:'陈亮',role:'market'},pmo:Actor={id:'U-002',name:'李主任',role:'pmo'},pm:Actor={id:'U-001',name:'张伟',role:'project-manager'},finance:Actor={id:'U-004',name:'刘敏',role:'finance'},tech:Actor={id:'U-005',name:'赵工',role:'solution-tech'},leader:Actor={id:'U-003',name:'王总',role:'executive'};
function fixture(){const state=createBusinessState();const source=structuredClone(state.opportunities[0]);const id='OPP-INIT-TEST';Object.assign(source,{id,code:id,status:'拟立项',ownerId:market.id,ownerName:market.name,estimatedAmount:1000,earlyInvestmentUsed:35,currentEstimateVersionId:'EST-INIT-TEST'});state.opportunities.push(source);const meta=state.opportunityMeta[id]=opportunityMeta(state,source);meta.solutionTask={id:'ST-INIT',opportunityId:id,assessmentId:'AR1',ownerId:tech.id,ownerName:tech.name,status:'已完成',createdAt:'2026-09-01',dueDate:'2026-09-09'};state.presales[id]={solutionVersions:[{id:'S1',version:1,submittedAt:'2026-09-09',submittedBy:tech.name,customerSituation:'客户需要统一业务',goals:'统一门户',scope:'门户与20个接口',boundaries:'不含数据清洗',architecture:'服务化',implementation:'分期交付',deliverables:'部署包',dependencies:'客户开放接口',assumptions:'资料按期提供',ownerId:tech.id,participants:[],startDate:'2026-09-01',endDate:'2026-09-09',attachments:['方案.pdf'],changeReason:''}],costVersions:[],research:[],reviews:[{id:'R1',round:1,solutionVersionId:'S1',costVersionId:'C1',status:'通过',method:'专家会',plannedDate:'2026-09-09',experts:[],opinions:[],createdAt:'2026-09-09',createdBy:pmo.name,corrections:[]}]};state.estimates.push({...structuredClone(state.estimates[0]),id:'EST-INIT-TEST',opportunityId:id,isFrozen:true,totalIncome:1000,totalCost:500,grossMargin:500,grossMarginRate:50});state.estimateMeta['EST-INIT-TEST']={reviewId:'R1',solutionVersionId:'S1',costVersionId:'C1',income:1000,incomeTaxRate:0,incomeTaxBasis:'不含税',lines:[],changeReason:'已评审来源',assumptions:'接口按期提供',riskReserveNote:'已核对',responsibleDepartment:'交付部',createdBy:tech.name,createdAt:'2026-09-09',frozenBy:pmo.name,frozenAt:'2026-09-09',freezeOpinion:'确认来源'};const input={...defaultInitiationInput(state,id),necessity:'统一客户业务入口',scope:'门户与20个接口',customerNeeds:'部署并完成培训',recommendation:'一般项目',region:'华东',attachments:['立项申请.pdf']};return {state,id,input};}
function submitted(){const f=fixture();let state=transition(f.state,{type:'save-initiation',input:f.input},market);state=transition(state,{type:'submit-initiation',id:'INIT-1'},market);return state;}
function classified(state=submitted(),high=false){state=transition(state,{type:'assess-initiation-risk',id:'INIT-1',risks:[],level:high?'高':'低',explanation:'已逐项核对来源及交付可行性'},pmo);return transition(state,{type:'classify-initiation',id:'INIT-1',level:high?'重大':'一般',reason:'按金额及风险确认级别'},pmo);}
function signed(state=classified()){for(const node of INITIATION_SIGNATURES){const actor=({pmo,finance,'solution-tech':tech,'project-manager':pm})[node.role];state=transition(state,{type:'sign-initiation',id:'INIT-1',node:node.node,conclusion:'同意',opinion:`${node.node}核验通过`},actor);}return state;}
const approve={type:'decide-initiation' as const,id:'INIT-1',result:'通过' as const,opinion:'批准立项',meetingDate:'',participants:[],minutes:'',rectifications:[]};
describe('立项评审与正式项目承接',()=>{
 it('不允许缺少真实上游或重复立项，提交后固定来源快照',()=>{const f=fixture();f.state.presales[f.id].reviews[0].status='不通过';let state=transition(f.state,{type:'save-initiation',input:f.input},market);expect(()=>transition(state,{type:'submit-initiation',id:'INIT-1'},market)).toThrow('方案');state=submitted();const source=structuredClone(state.initiations[0].rounds[0].source);state.estimates.at(-1)!.totalCost=1;expect(state.initiations[0].rounds[0].source).toEqual(source);expect(()=>transition(state,{type:'save-initiation',id:'INIT-1',input:f.input},market)).toThrow('不可覆盖');});
 it('六节点分别签署，同角色节点不可合并或重复，一次 PMO 点击不能批准',()=>{let state=classified();state=transition(state,{type:'sign-initiation',id:'INIT-1',node:'PMO',conclusion:'同意',opinion:'PMO确认'},pmo);expect(state.initiations[0].rounds[0].signatures).toHaveLength(1);expect(()=>transition(state,approve,pmo)).toThrow('前置');expect(()=>transition(state,{type:'sign-initiation',id:'INIT-1',node:'PMO',conclusion:'同意',opinion:'重复'},pmo)).toThrow('重复');expect(()=>transition(state,{type:'sign-initiation',id:'INIT-1',node:'财务',conclusion:'同意',opinion:'越权'},pmo)).toThrow('指定角色');expect(signed().initiations[0].status).toBe('待决策');});
 it('高风险不能绕过 PMC 路径，领导决策需会议证据',()=>{const state=classified(submitted(),true);expect(state.initiations[0].rounds[0].path).toBe('PMC决策会');expect(()=>transition(state,approve,pmo)).toThrow('仅PMO或集团领导');expect(()=>transition(state,approve,leader)).toThrow('会议日期');const next=transition(state,{...approve,meetingDate:'2026-09-10',participants:[leader.id,pmo.id],minutes:'PMC 全体表决同意，专项跟踪风险'},leader);expect(next.projects.at(-1)?.level).toBe('重大');});
 it('通过项目初始无 PM/预算/基线，候选人可见接受且此前不能策划',()=>{let state=transition(signed(),approve,pmo);const p=state.projects.at(-1)!;expect(p.pmId).toBe('');expect(state.budgets.some(b=>b.projectId===p.id)).toBe(false);expect(state.baselines.some(b=>b.projectId===p.id)).toBe(false);expect(p.actualCost).toBe(0);expect(()=>transition(state,{type:'save-planning',projectId:p.id,plan:state.planningDrafts[p.id],expectedRevision:state.planningDrafts[p.id].revision},pm)).toThrow();state=transition(state,{type:'nominate-pm',projectId:p.id,userId:pm.id,reason:'具备交付经验'},pmo);expect(visibleProjects('project-manager',state.projects).some(x=>x.id===p.id)).toBe(true);expect(state.projects.at(-1)?.pmId).toBe('');state=transition(state,{type:'respond-pm',projectId:p.id,accept:true,opinion:'接受任命'},pm);expect(state.projects.at(-1)?.pmId).toBe(pm.id);expect(()=>transition(state,approve,pmo)).toThrow('轮次已结束');});
 it('继承真实早期成本一次，旧汇总不虚构，投入来源仍可追溯',()=>{let state=signed();state.earlyCosts.push({id:'EARLY-C1',opportunityId:'OPP-INIT-TEST',requestId:'EARLY-R1',sourceId:'VOUCHER-1',subjectId:'SUB-01',subjectName:'人力',type:'labor',amount:12,occurredDate:'2026-09-09',description:'早期验证',enteredBy:finance.name});state=transition(state,approve,pmo);const p=state.projects.at(-1)!;expect(p.actualCost).toBe(12);expect(p.rollingCost).toBe(12);expect(state.costs.filter(c=>c.sourceId==='VOUCHER-1')).toHaveLength(1);expect(state.earlyCosts[0].projectId).toBe(p.id);expect(state.opportunities.at(-1)?.earlyInvestmentUsed).toBe(35);});
 it('整改保留上一轮资料，回复后形成新轮；否决暂缓留存成本处置责任',()=>{let state=transition(classified(),{...approve,result:'整改',rectifications:[{content:'补充客户验收条件',ownerId:market.id,deadline:'2026-09-20'}]},pmo);const original=structuredClone(state.initiations[0].rounds[0]);state=transition(state,{type:'save-initiation',id:'INIT-1',input:{...state.initiations[0].input,rectificationReply:'已在客户诉求补充验收条件'}},market);state=transition(state,{type:'submit-initiation',id:'INIT-1'},market);expect(state.initiations[0].rounds).toHaveLength(2);expect(state.initiations[0].rounds[0]).toEqual(original);expect(()=>transition(state,{...approve,result:'否决'},pmo)).toThrow('沉没成本');const costs=structuredClone(state.costs);state=transition(state,{...approve,result:'否决',costDisposition:'保留已发生费用，市场组织复盘',trackingOwnerId:market.id},pmo);expect(state.costs).toEqual(costs);expect(state.opportunityMeta['OPP-INIT-TEST'].termination?.costSnapshot).toBe(35);});
 it('已签依据仅允许归属该商机的真实未绑定合同，项目承接合同事实',()=>{const f=fixture();f.input.contractStatus='已签';f.input.contractReference='CON-NEW';f.input.amount=980;let state=transition(f.state,{type:'save-initiation',input:f.input},market);expect(()=>transition(state,{type:'submit-initiation',id:'INIT-1'},market)).toThrow('真实已签合同');state.contracts.push({id:'CON-NEW',code:'CON-NEW',name:'客户门户合同',projectId:'',opportunityId:f.id,customerId:f.state.opportunities.at(-1)!.customerId,amount:980,signDate:'2026-09-09',status:'已签订',paidAmount:0,unpaidAmount:980});state=transition(state,{type:'submit-initiation',id:'INIT-1'},market);state=transition(signed(classified(state)),approve,pmo);expect(state.projects.at(-1)?.isUnsigned).toBe(false);expect(state.projects.at(-1)?.contractAmount).toBe(980);expect(state.contracts.at(-1)?.projectId).toBe(state.projects.at(-1)?.id);});
 it('暂缓保存复评责任与成本处置，PMO恢复后须新轮提交，旧决定不变',()=>{let state=transition(classified(),{...approve,result:'暂缓',resumeDate:'2026-10-01',costDisposition:'保留前期成本并暂停新投入',trackingOwnerId:market.id},pmo);const round=structuredClone(state.initiations[0].rounds[0]);expect(state.opportunities.at(-1)?.status).toBe('暂缓');expect(()=>transition(state,{type:'resume-initiation',id:'INIT-1',reason:'条件满足'},market)).toThrow('PMO');state=transition(state,{type:'resume-initiation',id:'INIT-1',reason:'客户已确认接口条件，可以重新评审'},pmo);expect(state.initiations[0].status).toBe('草稿');expect(state.initiations[0].rounds[0]).toEqual(round);state=transition(state,{type:'submit-initiation',id:'INIT-1'},market);expect(state.initiations[0].rounds).toHaveLength(2);});
 it('风险矩阵不许下调或丢失来源，PMO新增必交目录进入正式项目',()=>{let state=submitted();const risk={id:'RISK-1',domain:'技术' as const,description:'客户接口延期',sourceId:'R1',sourceRoute:'/opportunities/OPP-INIT-TEST/review',probability:4,impact:4,mitigation:'提前联调',ownerId:tech.id};state.initiations[0].rounds[0].source.risks.push(risk);expect(()=>transition(state,{type:'assess-initiation-risk',id:'INIT-1',risks:[],level:'低',explanation:'忽略'},pmo)).toThrow('不能删除');expect(()=>transition(state,{type:'assess-initiation-risk',id:'INIT-1',risks:[risk],level:'低',explanation:'降低'},pmo)).toThrow('不得低于');state=submitted();state=transition(state,{type:'assess-initiation-risk',id:'INIT-1',risks:[],level:'低',explanation:'风险可控'},pmo);state=transition(state,{type:'classify-initiation',id:'INIT-1',level:'一般',reason:'按规则',requiredDeliverables:['安全评估报告']},pmo);state=transition(signed(state),approve,pmo);expect(state.materials.find(m=>m.projectId===state.projects.at(-1)?.id&&m.name==='安全评估报告')?.required).toBe(true);});

});
