import { describe, expect, it } from 'vitest';
import { createBusinessState, transition, type Actor, type BusinessState } from '@/mock/business-domain';
import { assessmentSummary, DIMENSIONS, opportunityMeta } from '@/mock/opportunities';
import type { OpportunityInput } from '@/models/opportunities';
const market:Actor={id:'U-006',name:'陈亮',role:'market'};
const tech:Actor={id:'U-005',name:'赵工',role:'solution-tech'};
const finance:Actor={id:'U-004',name:'刘敏',role:'finance'};
const input:OpportunityInput={name:'晋江市数据协同应用二期机会',customerId:'CUST-001',departmentId:'D-002',ownerId:'U-006',estimatedAmount:1000,expectedSignDate:'2026-11-30',winRate:80,source:'客户需求',projectType:'软件开发',description:'整合跨部门数据并建设业务协同应用',competition:'客户比选两家供应商',businessLine:'数字政务',region:'福建省',collaborators:['U-005'],attachments:['客户需求纪要.pdf']};
function create(){const state=transition(createBusinessState(),{type:'save-opportunity',input,submit:true},market);return {state,id:state.opportunities.at(-1)!.id};}
function assessed(cost=650){const created=create(); const id=created.id; let state=created.state;state=transition(state,{type:'start-opportunity-assessment',id},market);for(const d of DIMENSIONS)state=transition(state,{type:'save-opportunity-dimension',id,dimension:d.key,opinion:{score:85,conclusion:'可行',risk:'',note:'专业条件已核实，可按既定边界推进',attachment:'',preliminaryCost:d.key==='margin'?cost:undefined}},d.role==='market'?market:d.role==='finance'?finance:tech);return {state,id};}
describe('商机初评业务闭环',()=>{
 it('草稿生成唯一编号、提交校验、重复提醒和输入不可原地修改',()=>{const base=createBusinessState();const draft=transition(base,{type:'save-opportunity',input:{...input,description:''},submit:false},market);expect(draft.opportunities.at(-1)?.status).toBe('草稿');expect(base.opportunities.length+1).toBe(draft.opportunities.length);expect(()=>transition(base,{type:'save-opportunity',input:{...input,description:''},submit:true},market)).toThrow('业务背景');expect(()=>transition(draft,{type:'save-opportunity',input,submit:true},market)).toThrow('相似');const s=transition(draft,{type:'save-opportunity',input,submit:true,duplicateConfirmed:true},market);expect(new Set(s.opportunities.map(o=>o.id)).size).toBe(s.opportunities.length);});
 it('专业权限与缺失维度阻断拟立项',()=>{const created=create(); const id=created.id; let state=created.state;state=transition(state,{type:'start-opportunity-assessment',id},market);expect(()=>transition(state,{type:'save-opportunity-dimension',id,dimension:'technology',opinion:{score:90,conclusion:'可行',note:'越权代填',risk:'',attachment:''}},market)).toThrow('本专业');expect(()=>transition(state,{type:'conclude-opportunity',id,conclusion:'拟立项',reason:'推进'},market)).toThrow('六个');expect(()=>transition(state,{type:'save-opportunity',id,input,submit:true},market)).toThrow('锁定');});
 it('六维完成后形成快照与唯一方案任务，锁定基础字段',()=>{const created=assessed(); const id=created.id; let state=created.state;const before=structuredClone(state);state=transition(state,{type:'conclude-opportunity',id,conclusion:'拟立项',reason:'专业条件具备，进入方案调查'},market);expect(state.opportunities.at(-1)?.status).toBe('拟立项');expect(state.opportunityMeta[id].solutionTask?.assessmentId).toBe(state.opportunityMeta[id].assessments[0].id);expect(state.opportunityMeta[id].assessments[0].status).toBe('已确认');expect(before.opportunityMeta[id].assessments[0].status).toBe('评估中');expect(()=>transition(state,{type:'save-opportunity',id,input,submit:true},market)).toThrow('禁止直接覆盖');expect(()=>transition(state,{type:'start-opportunity-assessment',id},market)).toThrow('方案流程');expect(state.audit.at(-1)?.target).toBe(id);});
 it('低毛利、不可行专业结论都不能绕过条件门',()=>{const {state,id}=assessed(950);expect(assessmentSummary(state.opportunities.at(-1)!,opportunityMeta(state,state.opportunities.at(-1)!)).marginRate).toBe(5);expect(()=>transition(state,{type:'conclude-opportunity',id,conclusion:'拟立项',reason:'强行推进'},market)).toThrow('毛利');const blocked=transition(state,{type:'save-opportunity-dimension',id,dimension:'technology',opinion:{score:90,conclusion:'不可行',risk:'关键接口未开放',note:'交付存在阻断',attachment:''}},tech);expect(()=>transition(blocked,{type:'conclude-opportunity',id,conclusion:'拟立项',reason:'推进'},market)).toThrow('不可行');});
 it('暂缓必须安排复评，复评追加轮次且保留历史',()=>{const created=assessed(); const id=created.id; let state=created.state;expect(()=>transition(state,{type:'conclude-opportunity',id,conclusion:'暂缓',reason:'客户预算延后'},market)).toThrow('复评');state=transition(state,{type:'conclude-opportunity',id,conclusion:'暂缓',reason:'客户预算延后',reviewDate:'2026-09-15',reviewOwnerId:'U-006'},market);const old=structuredClone(state.opportunityMeta[id].assessments[0]);state=transition(state,{type:'start-opportunity-assessment',id},market);expect(state.opportunityMeta[id].assessments).toHaveLength(2);expect(state.opportunityMeta[id].assessments[0]).toEqual(old);expect(state.opportunityMeta[id].assessments[1].opinions).toEqual({});});
 it('终止保留提前投入并强制成本处置与复盘',()=>{const created=create(); const id=created.id; let state=created.state;state.opportunities.at(-1)!.earlyInvestmentUsed=12;state.opportunities.at(-1)!.earlyInvestmentQuota=20;expect(()=>transition(state,{type:'conclude-opportunity',id,conclusion:'已终止',reason:'客户取消'},market)).toThrow('成本处置');const costs=structuredClone(state.costs);state=transition(state,{type:'conclude-opportunity',id,conclusion:'已终止',reason:'客户取消',costDisposition:'12万元转沉没成本分析，保留来源',retrospective:'采购计划应在合同明确后推进'},market);expect(state.opportunityMeta[id].termination?.costSnapshot).toBe(12);expect(state.opportunities.at(-1)?.earlyInvestmentUsed).toBe(12);expect(state.costs).toEqual(costs);});
 it('跟进只追加且角色和日期受约束',()=>{const created=create(); const id=created.id; let state=created.state;const action={type:'follow-opportunity' as const,id,date:'2026-09-09',communication:'客户确认范围',requirementChange:'新增数据接口',commercialProgress:'预算审议',nextPlan:'提交技术澄清'};expect(()=>transition(state,action,finance)).toThrow('市场');state=transition(state,action,market);const first=structuredClone(state.opportunityMeta[id].followups[0]);state=transition(state,{...action,communication:'补充会议纪要'},market);expect(state.opportunityMeta[id].followups).toHaveLength(2);expect(state.opportunityMeta[id].followups[0]).toEqual(first);expect(()=>transition(state,{...action,date:'2026-09-11'},market)).toThrow('日期');});
 it('无权限商机不可用直接动作访问',()=>{const {state,id}=create();const other:BusinessState=structuredClone(state);other.opportunities.at(-1)!.departmentId='D-003';other.opportunities.at(-1)!.ownerId='U-009';expect(()=>transition(other,{type:'start-opportunity-assessment',id},market)).toThrow('无权');});
});
