import { describe, expect, it } from 'vitest';
import { createBusinessState, transition, type Actor } from '@/mock/business';
import { costLineAmount, costTotal, laborDayRate, presalesReady } from '@/mock/presales';
import type { CostDraft, SolutionDraft } from '@/models/presales';
const tech:Actor={id:'U-005',name:'赵工',role:'solution-tech'};const finance:Actor={id:'U-004',name:'刘敏',role:'finance'};const pmo:Actor={id:'U-002',name:'李主任',role:'pmo'};
const solution:SolutionDraft={customerSituation:'多套业务系统孤立',goals:'完成数据共享与单点登录',scope:'20个接口、1套统一门户',boundaries:'不含客户历史数据清洗',architecture:'微服务与统一身份认证',implementation:'调研、迭代、试运行',deliverables:'接口文档、部署包、测试报告',dependencies:'客户提供测试环境',assumptions:'现有接口稳定开放',ownerId:'U-005',participants:['U-006','U-005'],startDate:'2026-09-09',endDate:'2026-09-20',attachments:['方案V1.pdf','架构图.png'],changeReason:''};
const cost:CostDraft={solutionFingerprint:'',feasibility:'可行',architecture:'既有产品V3',reuse:'复用基础框架80%',customization:'20接口适配',environment:'客户提供容器平台',security:'等保三级接口审计',dependencies:'第三方认证服务',risk:'测试环境交付时间可能延迟',attachments:['成本依据.xlsx'],lines:[{id:'L1',subjectId:'SUB-01',name:'接口开发',scope:'20接口',quantity:100,unit:'人天',unitPrice:999,taxRate:0,taxBasis:'含税',basis:'2人50天',risk:'',laborUserId:'U-005',laborGrade:'高级研发'}, {id:'L2',subjectId:'SUB-03',name:'集成网关',scope:'统一门户',quantity:2,unit:'套',unitPrice:10,taxRate:13,taxBasis:'不含税',basis:'厂商询价',risk:'交货周期',supplier:'数字基础设施供应商',quotationSource:'Q-20260909',quotationExpiry:'2026-10-09'}]};
function prepared(){let state=createBusinessState();const o=state.opportunities.at(-1)!;o.status='拟立项';const id=o.id;state.opportunityMeta[id]={source:'客户需求',projectType:'软件开发',description:'数据集成',competition:'市场竞争',businessLine:'数字政务',region:'福建省',collaborators:['U-005'],attachments:[],followups:[],assessments:[],pauses:[],solutionTask:{id:`SOL-TASK-${id}`,opportunityId:id,assessmentId:'ASSESS-FIXTURE',ownerId:'U-005',ownerName:'赵工',status:'待开始',createdAt:'2026-09-09',dueDate:'2026-09-20'}};state=transition(state,{type:'presales-save-solution',id,draft:solution},tech);state=transition(state,{type:'presales-save-cost',id,draft:cost},tech);state=transition(state,{type:'presales-finance-check',id,opinion:'核对范围、询价和人力基准'},finance);return {state,id};}
function reviewPrepared(){const ready=prepared();const state=transition(ready.state,{type:'presales-submit-review',id:ready.id,method:'线上评审',plannedDate:'2026-09-10',expertIds:['U-005','U-004']},pmo);return {state,id:ready.id,reviewId:state.presales[ready.id].reviews[0].id};}
function correctionReplied(){const prepared=reviewPrepared();let state=prepared.state;const {id,reviewId}=prepared;for(const actor of [tech,finance])state=transition(state,{type:'presales-expert-opinion',id,reviewId,conclusion:'整改',opinion:'补充评审整改',attachment:''},actor);state=transition(state,{type:'presales-review-decision',id,reviewId,conclusion:'整改后复审',reason:'请完成整改',corrections:[{item:'更新评审材料',ownerId:'U-005',dueDate:'2026-09-20'}]},pmo);const correctionId=state.presales[id].reviews[0].corrections[0].id;state=transition(state,{type:'presales-correction-reply',id,reviewId,correctionId,response:'已更新评审材料',attachment:'整改说明.pdf'},tech);return {state,id,reviewId};}
describe('方案成本与专家评审',()=>{
 it('统一人力基准覆盖任意单价，税前询价换算含税金额且输入动作不被变更',()=>{const {state,id}=prepared();const saved=state.presales[id].costDraft!;expect(saved.lines[0].unitPrice).toBe(laborDayRate('U-005'));expect(cost.lines[0].unitPrice).toBe(999);expect(costLineAmount(saved.lines[1])).toBe(22.6);expect(costTotal(saved)).toBe(37);expect(presalesReady(state,id)).toEqual([]);});
 it('范围变化使成本和财务确认失效，过期询价不可发起评审',()=>{const ready=prepared();let state=transition(ready.state,{type:'presales-save-solution',id:ready.id,draft:{...solution,scope:'追加5个接口'}},tech);expect(presalesReady(state,ready.id)).toContain('方案已变更，需重新确认成本测算');const expired=structuredClone(cost);expired.lines[1].quotationExpiry='2026-09-01';state=transition(state,{type:'presales-save-cost',id:ready.id,draft:expired},tech);expect(state.presales[ready.id].costDraft?.financeCheck).toBeUndefined();expect(presalesReady(state,ready.id)).toContain('采购询价缺失或过期');});
 it('评审绑定只读版本、专业意见不可代填或重复提交',()=>{const {state,id,reviewId}=reviewPrepared();expect(()=>transition(state,{type:'presales-save-solution',id,draft:solution},tech)).toThrow('冻结');expect(()=>transition(state,{type:'presales-expert-opinion',id,reviewId,conclusion:'通过',opinion:'代填',attachment:''},pmo)).toThrow('指定专家');const next=transition(state,{type:'presales-expert-opinion',id,reviewId,conclusion:'通过',opinion:'技术通过',attachment:''},tech);expect(()=>transition(next,{type:'presales-expert-opinion',id,reviewId,conclusion:'通过',opinion:'再次提交',attachment:''},tech)).toThrow('已提交');expect(next.presales[id].reviews[0].solutionVersionId).toBe(next.presales[id].solutionVersions[0].id);});
 it('专家意见未齐或有整改时PMO不能直接通过',()=>{const {state,id,reviewId}=reviewPrepared();expect(()=>transition(state,{type:'presales-review-decision',id,reviewId,conclusion:'通过',reason:'通过',corrections:[]},pmo)).toThrow('尚未齐全');let next=transition(state,{type:'presales-expert-opinion',id,reviewId,conclusion:'整改',opinion:'补充接口安全设计',attachment:''},tech);next=transition(next,{type:'presales-expert-opinion',id,reviewId,conclusion:'通过',opinion:'费用口径合理',attachment:''},finance);expect(()=>transition(next,{type:'presales-review-decision',id,reviewId,conclusion:'通过',reason:'强行通过',corrections:[]},pmo)).toThrow('整改');expect(()=>transition(next,{type:'presales-review-decision',id,reviewId,conclusion:'整改后复审',reason:'补充材料',corrections:[]},pmo)).toThrow('整改必须');});
 it('整改回复和实质方案变更后才能产生新轮次，旧快照保持不变',()=>{const prepared=reviewPrepared();let state=prepared.state;const {id,reviewId}=prepared;for(const actor of [tech,finance])state=transition(state,{type:'presales-expert-opinion',id,reviewId,conclusion:'整改',opinion:'补充接口安全设计',attachment:''},actor);state=transition(state,{type:'presales-review-decision',id,reviewId,conclusion:'整改后复审',reason:'请完善安全设计',corrections:[{item:'增加接口鉴权说明',ownerId:'U-005',dueDate:'2026-09-20'}]},pmo);const old=structuredClone(state.presales[id].solutionVersions[0]);expect(presalesReady(state,id)).toContain('上轮整改事项尚未逐条回复');expect(presalesReady(state,id)).toContain('整改后方案与成本内容均未变更');const cid=state.presales[id].reviews[0].corrections[0].id;state=transition(state,{type:'presales-correction-reply',id,reviewId,correctionId:cid,response:'已增加鉴权流程图',attachment:'鉴权设计.pdf'},tech);expect(presalesReady(state,id)).toContain('整改后方案与成本内容均未变更');expect(()=>transition(state,{type:'presales-submit-review',id,method:'复审会议',plannedDate:'2026-09-21',expertIds:['U-004','U-005']},pmo)).toThrow('整改后方案与成本内容均未变更');state=transition(state,{type:'presales-save-solution',id,draft:{...solution,changeReason:'仅补充修改说明'}},tech);expect(presalesReady(state,id)).toContain('整改后方案与成本内容均未变更');state=transition(state,{type:'presales-save-solution',id,draft:{...solution,architecture:'新增接口鉴权设计',changeReason:'落实首轮专家整改'}},tech);state=transition(state,{type:'presales-save-cost',id,draft:cost},tech);state=transition(state,{type:'presales-finance-check',id,opinion:'确认整改后成本'},finance);expect(presalesReady(state,id)).toEqual([]);state=transition(state,{type:'presales-submit-review',id,method:'复审会议',plannedDate:'2026-09-21',expertIds:['U-004','U-005']},pmo);expect(state.presales[id].reviews).toHaveLength(2);expect(state.presales[id].solutionVersions[0]).toEqual(old);expect(state.presales[id].solutionVersions[1].architecture).toBe('新增接口鉴权设计');expect(()=>transition(state,{type:'presales-expert-opinion',id,reviewId,conclusion:'通过',opinion:'绕过新轮次',attachment:''},tech)).toThrow('当前');});
 it('整改可仅实质调整成本并生成新轮次，旧双版本保持不变',()=>{const prepared=correctionReplied();let state=prepared.state;const {id}=prepared;const oldSolution=structuredClone(state.presales[id].solutionVersions[0]);const oldCost=structuredClone(state.presales[id].costVersions[0]);state=transition(state,{type:'presales-save-cost',id,draft:{...cost,risk:'整改后增加供应延期风险准备'}},tech);state=transition(state,{type:'presales-finance-check',id,opinion:'确认成本专项整改'},finance);expect(presalesReady(state,id)).toEqual([]);state=transition(state,{type:'presales-submit-review',id,method:'成本专项复审',plannedDate:'2026-09-21',expertIds:['U-004','U-005']},pmo);expect(state.presales[id].reviews).toHaveLength(2);expect(state.presales[id].solutionVersions[0]).toEqual(oldSolution);expect(state.presales[id].costVersions[0]).toEqual(oldCost);expect(state.presales[id].solutionVersions[1].architecture).toBe(oldSolution.architecture);expect(state.presales[id].costVersions[1].risk).toBe('整改后增加供应延期风险准备');});
 it('参与人和附件仅重排不能绕过整改实质变更门禁',()=>{const prepared=correctionReplied();let state=prepared.state;const {id}=prepared;state=transition(state,{type:'presales-save-solution',id,draft:{...solution,participants:[...solution.participants].reverse(),attachments:[...solution.attachments].reverse(),changeReason:'仅调整展示顺序'}},tech);expect(presalesReady(state,id)).toContain('整改后方案与成本内容均未变更');expect(()=>transition(state,{type:'presales-submit-review',id,method:'复审会议',plannedDate:'2026-09-21',expertIds:['U-004','U-005']},pmo)).toThrow('整改后方案与成本内容均未变更');expect(state.presales[id].solutionVersions).toHaveLength(1);expect(state.presales[id].reviews).toHaveLength(1);});
 it('真实评审通过才完成方案任务，领导角色不能代替PMO',()=>{const prepared=reviewPrepared();let state=prepared.state;const {id,reviewId}=prepared;for(const actor of [tech,finance])state=transition(state,{type:'presales-expert-opinion',id,reviewId,conclusion:'通过',opinion:'专业意见通过',attachment:''},actor);expect(state.opportunityMeta[id].solutionTask?.status).toBe('进行中');expect(()=>transition(state,{type:'presales-review-decision',id,reviewId,conclusion:'通过',reason:'通过',corrections:[]},{id:'U-003',name:'王总',role:'executive'})).toThrow('无权');state=transition(state,{type:'presales-review-decision',id,reviewId,conclusion:'通过',reason:'专业意见一致，同意形成概算',corrections:[]},pmo);expect(state.opportunityMeta[id].solutionTask?.status).toBe('已完成');expect(state.presales[id].reviews[0].status).toBe('通过');expect(state.opportunities.find(o=>o.id===id)?.status).toBe('拟立项');});
});
