import {it,expect} from 'vitest';
import {createBusinessState,createDemoBusinessState,transition,type Actor,type BusinessState} from '@/mock/business';
import {defaultChangeInput} from '@/mock/changes';
const pm:Actor={id:'U-001',name:'张建国',role:'project-manager'},pmo:Actor={id:'U-002',name:'李主任',role:'pmo'},leader:Actor={id:'U-003',name:'王总',role:'executive'};
const experts:Actor[]=[{id:'U-005',name:'赵工',role:'solution-tech'},{id:'U-004',name:'刘敏',role:'finance'},{id:'U-006',name:'陈亮',role:'market'}];
function submitted(cost=20,days=14){let s=createBusinessState();const input=defaultChangeInput(s,'P-001');Object.assign(input,{title:'增加设备接入范围',reason:'客户签证明确新增点位',scope:'增加10个设备点位',newWorkPackage:'新增设备点位接入',customerBasis:'客户签证2026-09-09',contractBasis:'合同范围变更条款',attachments:['客户签证.pdf'],risk:'按原技术栈交付，跟踪联调风险',procurementImpact:'增加设备20万元',outsourceImpact:'无新增外包',shiftDays:days,adjustments:{'SUB-03':cost}});s=transition(s,{type:'save-project-change',projectId:'P-001',input},pm);const id=s.changeRequests.at(-1)!.id;s=transition(s,{type:'submit-project-change',id},pm);return {s,id};}
function classified(state:BusinessState,id:string){let s=state;for(let i=0;i<3;i++)s=transition(s,{type:'assess-project-change',id,area:(['技术','财务','市场'] as const)[i],opinion:'核对范围、工期与相应专业成本影响后同意'},experts[i]);return transition(s,{type:'classify-project-change',id,opinion:'按规则分级，专业意见齐全'},pmo);}
it('原CHG-0006待审编号金额不变，PMO可以真实退回解除未决变更且不改预算成本',()=>{const initial=createDemoBusinessState(),r=initial.changeRequests.find(r=>r.id==='CHG-0006')!,summary=initial.changes.find(c=>c.id===r.id)!;expect(summary.status).toBe('PMO审批中');expect(summary.costImpact).toBe(15);expect(r.original.projectId).toBe('P-006');expect(r.assessments).toHaveLength(0);expect(initial.changeRequests.some(r=>r.id===initial.approvals.find(a=>a.kind==='change')?.sourceChangeId)).toBe(false);const next=transition(initial,{type:'review-project-change',id:r.id,approve:false,opinion:'原材料待补齐，退回重新申报'},pmo);expect(next.changes.find(c=>c.id===r.id)?.status).toBe('已否决');expect(next.projects.find(p=>p.id==='P-006')?.budgetAmount).toBe(initial.projects.find(p=>p.id==='P-006')?.budgetAmount);expect(next.costs).toEqual(initial.costs);});
it('新增范围先评估分级，再由PMO批准；追加完整基线，旧版本与最新执行事实保留',()=>{const {s:initial,id}=submitted();expect(()=>transition(initial,{type:'review-project-change',id,approve:true,opinion:'跳过评估'},pmo)).toThrow('评估');let s=classified(initial,id);const originalBase=structuredClone(s.baselines.find(b=>b.projectId==='P-001'&&b.status==='已生效')!);const t=s.tasks.find(t=>t.projectId==='P-001'&&t.progress<100)!;t.progress=99;t.actualStartDate='2026-04-01';t.executionNote='审批期间继续原范围交付';const date=t.endDate;const costs=structuredClone(s.costs);s=transition(s,{type:'review-project-change',id,approve:true,opinion:'同意指定范围、工期和预算'},pmo);expect(s.tasks.find(x=>x.id===t.id)?.progress).toBe(99);expect(s.tasks.find(x=>x.id===t.id)?.endDate).not.toBe(date);expect(s.tasks.find(x=>x.id===t.id)?.executionNote).toBe(t.executionNote);expect(s.costs).toEqual(costs);expect(s.baselines.find(b=>b.id===originalBase.id)?.plannedEndDate).toBe(originalBase.plannedEndDate);const base=s.baselines.find(b=>b.projectId==='P-001'&&b.status==='已生效')!;expect(base.snapshot?.scope).toBe('增加10个设备点位');expect(s.tasks.some(t=>t.projectId==='P-001'&&t.name==='新增设备点位接入')).toBe(true);expect(base.budgetAmount).toBe(originalBase.budgetAmount+20);expect(s.decisions.find(d=>d.id===`DEC-${id}`)?.status).toBe('已通过');});
it('重大工期或金额必须高阶审批；角色不能绕过；建设冻结和源基线变化阻断',()=>{const {s:initial,id}=submitted(200,40);let s=classified(initial,id);expect(s.changeRequests.find(r=>r.id===id)?.requiredRole).toBe('executive');expect(()=>transition(s,{type:'review-project-change',id,approve:true,opinion:'绕过'},pmo)).toThrow('指定');s.constructionFreezes['P-001']={requestId:'SETTLE',reason:'结算审核'};expect(()=>transition(s,{type:'review-project-change',id,approve:true,opinion:'批准'},leader)).toThrow('冻结');delete s.constructionFreezes['P-001'];s.baselines.find(b=>b.projectId==='P-001'&&b.status==='已生效')!.id='DIFFERENT';expect(()=>transition(s,{type:'review-project-change',id,approve:true,opinion:'批准'},leader)).toThrow('源基线');s=classified(initial,id);expect(transition(s,{type:'review-project-change',id,approve:true,opinion:'按PMC授权执行'},leader).changes.find(c=>c.id===id)?.status).toBe('已批准');});
it('驳回不改原基线，重提保留上一修订和意见；非法核减不能保存',()=>{const {s:initial,id}=submitted();let s=transition(initial,{type:'review-project-change',id,approve:false,opinion:'客户依据需补充'},pmo);expect(s.baselines).toEqual(initial.baselines);const r=s.changeRequests.find(r=>r.id===id)!;s=transition(s,{type:'save-project-change',id,projectId:r.projectId,input:{...r.input,customerBasis:'补充客户签证'}},pm);expect(s.changeRequests.find(r=>r.id===id)?.history?.[0].opinion).toBe('客户依据需补充');expect(()=>transition(s,{type:'save-project-change',id,projectId:r.projectId,input:{...r.input,adjustments:{'SUB-03':-999999}}},pm)).toThrow('不能为负');});
it('历史补齐快照不能冒充已齐材料直接通过，须退回补充；不存在重复新基线',()=>{const initial=createBusinessState();let s=classified(initial,'CHG-0006');const r=s.changeRequests.find(r=>r.id==='CHG-0006')!;expect(()=>transition(s,{type:'review-project-change',id:r.id,approve:true,opinion:'同意'},r.requiredRole==='pmo'?pmo:leader)).toThrow('材料不完整');s=transition(s,{type:'review-project-change',id:r.id,approve:false,opinion:'补充客户附件'},pmo);expect(()=>transition(s,{type:'review-project-change',id:r.id,approve:false,opinion:'重复'},pmo)).toThrow('已处理');});
