import {describe,it,expect} from 'vitest';
import {createBusinessState,transition,type Actor,type BusinessState} from '@/mock/business';
import {acceptanceDetail,checkNames} from '@/mock/acceptance';
import {pendingSettlementSources,settlementChecks} from '@/mock/settlement';
import {selectFourCalculations} from '@/mock/selectors';
import {sumMoney} from '@/utils/money';
const pm:Actor={id:'U-001',name:'张建国',role:'project-manager'};const finance:Actor={id:'U-004',name:'刘敏',role:'finance'};const pmo:Actor={id:'U-002',name:'李主任',role:'pmo'};
function accepted(){let s=createBusinessState();const old=s.acceptances.find((a)=>a.projectId==='P-006'&&a.type==='客户终验')!;s=transition(s,{type:'reply-acceptance',id:old.id,reply:'已补齐客户整改材料'},pm);const d=acceptanceDetail(s,old);s=transition(s,{type:'submit-acceptance',projectId:'P-006',kind:'客户终验',id:old.id,detail:{scope:d.scope,plannedDate:'2026-09-10',method:d.method,customerContact:d.customerContact,participants:d.participants,contractId:d.contractId}},pm);const id=s.acceptances.at(-1)!.id;s=transition(s,{type:'review-acceptance',id,passed:true,checks:checkNames('客户终验').map((name)=>({name,passed:true,note:'复验确认'})),opinion:'客户通过',process:'现场逐项复验'},pm);s=transition(s,{type:'save-acceptance-proof',id,proofFiles:['客户验收确认函.pdf']},pm);s=transition(s,{type:'confirm-acceptance',id,proofFiles:['客户验收确认函.pdf'],opinion:'签署材料确认'},pmo);return s;}
function ready(){let s=accepted(); // Test precondition: pending change has completed before settlement. UI uses the original change review.
 s.changes.filter((c)=>c.projectId==='P-006'&&c.status==='PMO审批中').forEach((c)=>{c.status='已否决';});
 for(const source of pendingSettlementSources(s,'P-006'))s=transition(s,{type:'resolve-settlement-source',projectId:'P-006',sourceId:source.id,disposition:'取消不发生',evidence:'原待审申请已撤销，未发生；取消审批凭据CANCEL-20260909'},finance);
 const subjects=selectFourCalculations(s.projects.find((p)=>p.id==='P-006')!,s).subjects;
 for(const subject of subjects){for(const bucket of ['承诺','预测'] as const){const amount=bucket==='承诺'?subject.committed:subject.remaining;if(amount)s=transition(s,{type:'dispose-settlement-balance',projectId:'P-006',subjectId:subject.subjectId,bucket,disposition:'实际发生',amount,evidence:'合同结尾服务已实际交付，财务凭据FINAL-COST'},finance);}}
 return s;
}
function submit(s:BusinessState,id?:string){return transition(s,{type:'save-settlement',projectId:'P-006',id,note:'验收已完成，实际收入和成本清晰，未决事项已逐一处理',files:['智慧园区结算报告.pdf'],submit:true},pm);}
function advance(s:BusinessState,id:string){s=transition(s,{type:'review-settlement',id,operation:'finance-confirm',opinion:'收入成本凭证核对一致',invoicedAmount:1860,taxAmount:100},finance);s=transition(s,{type:'review-settlement',id,operation:'pmo-audit',opinion:'材料和过程完整'},pmo);return transition(s,{type:'review-settlement',id,operation:'review-pass',opinion:'评审通过'},pmo);}
describe('正式结算与冻结协议',()=>{
 it('客户通过未确认、历史未决与原变更均阻断',()=>{const s=accepted();const a=s.acceptances.at(-1)!;delete s.acceptanceDetails[a.id].confirmedAt;expect(()=>submit(s)).toThrow('最终客户验收确认');s.acceptanceDetails[a.id].confirmedAt='2026-09-09';expect(()=>submit(s)).toThrow('建设成本');expect(settlementChecks(s,'P-006').find((c)=>c.name==='重大事项与变更')?.passed).toBe(false);});
 it('逐科目承诺/预测实际发生守恒，旧滚动科目快照保留',()=>{const initial=createBusinessState();const before=initial.projects.find((p)=>p.id==='P-006')!;const state=ready();const p=state.projects.find((p)=>p.id==='P-006')!;expect(p.actualCost).toBe(before.rollingCost);expect(p.committedCost).toBe(0);expect(p.forecastRemainingCost).toBe(0);expect(selectFourCalculations(p,state).rolling).toBe(before.rollingCost);expect(state.settlementForecastSnapshots[p.id].total).toBe(before.rollingCost);expect(sumMoney(Object.values(state.settlementForecastSnapshots[p.id].subjects))).toBe(before.rollingCost);expect(sumMoney(selectFourCalculations(p,state).subjects.map((s)=>s.rolling))).toBe(p.rollingCost);});
 it('提交冻结成本入口，材料退回保持冻结、追加版本保留旧快照',()=>{let s=submit(ready());const r=s.settlementRequests.at(-1)!;const snapshot=structuredClone(r.snapshot);expect(s.constructionFreezes['P-006'].requestId).toBe(r.id);const cost={...s.costs.find((c)=>c.projectId==='P-006')!,id:'UNEXPECTED',sourceId:'UNEXPECTED',amount:1};expect(()=>transition(s,{type:'confirm-cost',cost},finance)).toThrow('冻结');s=transition(s,{type:'review-settlement',id:r.id,operation:'material-return',opinion:'补充材料'},pmo);expect(s.constructionFreezes['P-006']).toBeDefined();s=submit(s,r.id);expect(s.settlementRequests.at(-1)!.version).toBe(2);expect(s.settlementRequests[0].snapshot).toEqual(snapshot);expect(s.settlementRequests[0].supersededBy).toBe(s.settlementRequests.at(-1)!.id);expect(s.settlementRequests.at(-1)!.snapshot).toEqual(snapshot);});
 it('仅财务金额退回可解冻；重提引用新金额，旧结果保留',()=>{let s=submit(ready());const id=s.settlementRequests.at(-1)!.id;const oldCost=s.settlementRequests[0].snapshot.cost;expect(()=>transition(s,{type:'review-settlement',id,operation:'amount-return',opinion:'调整成本'},pmo)).toThrow('只有财务');s=transition(s,{type:'review-settlement',id,operation:'amount-return',opinion:'新增历史凭证须重新核算'},finance);expect(s.constructionFreezes['P-006']).toBeUndefined();s=transition(s,{type:'confirm-cost',cost:{...s.costs.find((c)=>c.projectId==='P-006')!,id:'ADJUST-COST',sourceId:'ADJUST-COST',amount:1}},finance);s=submit(s,id);expect(s.settlementRequests[0].snapshot.cost).toBe(oldCost);expect(s.settlementRequests.at(-1)!.snapshot.cost).toBe(oldCost+1);});
 it('财务→PMO审核→评审→最终锁定，建设锁定但不关闭项目且运维隔离',()=>{let s=submit(ready());const id=s.settlementRequests.at(-1)!.id;expect(()=>transition(s,{type:'review-settlement',id,operation:'lock',opinion:'跳步'},finance)).toThrow('评审通过');s=advance(s,id);s=transition(s,{type:'review-settlement',id,operation:'lock',opinion:'锁定最终结果'},finance);const p=s.projects.find((p)=>p.id==='P-006')!;expect(p.phase).toBe('收尾');expect(p.status).toBe('已结算');expect(s.lockedProjects).toContain(p.id);expect(()=>submit(s)).toThrow('已正式结算');const result=selectFourCalculations(p,s).settlement!;expect(result.finalCost).toBe(p.actualCost);const cost={...s.costs.find((c)=>c.projectId===p.id)!,id:'LATE-COST',sourceId:'LATE-COST',amount:1};expect(()=>transition(s,{type:'confirm-cost',cost},finance)).toThrow('锁定');const maintenance=transition(s,{type:'confirm-cost',maintenance:true,cost:{...cost,projectId:'P-007'}},finance);expect(maintenance.settlements).toEqual(s.settlements);expect(maintenance.maintenanceCosts).toHaveLength(1);});
 it('历史凭证核对要求项目、类型、金额一致且不重复抵充',()=>{let s=createBusinessState();const source=pendingSettlementSources(s,'P-006')[0];expect(source).toBeDefined();expect(()=>transition(s,{type:'resolve-settlement-source',projectId:'P-006',sourceId:source.id,disposition:'已有凭证',ledgerId:s.costs[0].id,evidence:'已入账'},finance)).toThrow('本项目');s.costs.push({id:'MATCHING-LEDGER',projectId:'P-006',type:source.kind,subjectId:'SUB-01',subjectName:'人力',amount:source.amount,sourceId:'MATCHING-SOURCE',occurredDate:'2026-09-01',description:'此旧原单对应凭证'});s=transition(s,{type:'resolve-settlement-source',projectId:'P-006',sourceId:source.id,disposition:'已有凭证',ledgerId:'MATCHING-LEDGER',evidence:'核对旧原始凭证一致'},finance);expect(()=>transition(s,{type:'resolve-settlement-source',projectId:'P-006',sourceId:source.id,disposition:'已有凭证',ledgerId:'MATCHING-LEDGER',evidence:'重复'},finance)).toThrow('历史导入未决单');});
 it('非预算科目预测也保留，取消不会覆写实际成本',()=>{let s=createBusinessState();const p=s.projects.find((p)=>p.id==='P-006')!;p.forecastBySubject={'SUB-EXTRA':20};const costs=structuredClone(s.costs);s=transition(s,{type:'dispose-settlement-balance',projectId:p.id,subjectId:'SUB-EXTRA',bucket:'预测',disposition:'取消不发生',amount:20,evidence:'客户取消额外工作，无实际发生'},finance);const next=s.projects.find((p)=>p.id==='P-006')!;expect(s.costs).toEqual(costs);expect(s.projects.find((p)=>p.id==='P-006')!.forecastRemainingCost).toBe(0);expect(selectFourCalculations(s.projects.find((p)=>p.id==='P-006')!,s).subjects.find((r)=>r.subjectId==='SUB-EXTRA')?.remaining).toBe(0);expect(sumMoney(selectFourCalculations(next,s).subjects.map((r)=>r.rolling))).toBe(next.rollingCost);});
 it('动态待审成本不能由历史核对旁路，也阻断余额重复处置',()=>{let s=createBusinessState();s.laborEntries.push({id:'PENDING-LABOR',projectId:'P-006',taskId:s.tasks.find((t)=>t.projectId==='P-006')!.id,userId:pm.id,userName:pm.name,date:'2026-09-09',hours:1,description:'未决工时',status:'待审核',rateVersion:'LAB-2026-01',hourlyYuan:150,amount:.015,baselineId:s.baselines.find((b)=>b.projectId==='P-006')!.id});expect(pendingSettlementSources(s,'P-006').some((x)=>x.id==='PENDING-LABOR')).toBe(true);expect(()=>transition(s,{type:'resolve-settlement-source',projectId:'P-006',sourceId:'PENDING-LABOR',disposition:'取消不发生',evidence:'企图旁路审核'},finance)).toThrow('动态原单');expect(()=>transition(s,{type:'dispose-settlement-balance',projectId:'P-006',subjectId:'SUB-01',bucket:'承诺',disposition:'实际发生',amount:1,evidence:'企图重复转换'},finance)).toThrow('动态未决原单');s=transition(s,{type:'save-settlement',projectId:'P-006',note:'仅保存准备草稿',files:[],submit:false},pm);expect(s.constructionFreezes['P-006']).toBeUndefined();});

});
