import {AS_OF_DATE} from '@/mock';
import {describe,it,expect} from 'vitest';
import {createBusinessState,transition,type Actor} from '@/mock/business';
import {unsignedControl,unsignedSummary,type ContractRegistration} from '@/mock/unsigned';
const market:Actor={id:'U-006',name:'陈亮',role:'market'},pmo:Actor={id:'U-002',name:'李主任',role:'pmo'},pm:Actor={id:'U-001',name:'张伟',role:'project-manager'},finance:Actor={id:'U-004',name:'刘敏',role:'finance'},leader:Actor={id:'U-003',name:'王总',role:'executive'};
const planId='P-PLAN-001';
const registration:ContractRegistration={code:'CON-TEST-START',name:'园区协同平台交付合同',amount:1200,signDate:AS_OF_DATE,acceptanceDueDate:'2026-12-31',source:'客户签署合同正本',attachment:'双方签章合同.pdf',receiptPlans:[{title:'启动款',dueDate:'2026-09-20',amount:360},{title:'验收款',dueDate:'2026-12-31',amount:840}]};
function planned(){const initial=createBusinessState();initial.projects.find(p=>p.id===planId)!.plannedStartDate=AS_OF_DATE;initial.planningDrafts[planId].plannedStartDate=AS_OF_DATE;let state=transition(initial,{type:'submit-planning',projectId:planId},pm);state=transition(state,{type:'review-planning',id:'PREVIEW-1',result:'通过',opinion:'计划资源满足交付',rectifications:[]},pmo);const budget={...state.budgets[0],id:'DRAFT-NEW',projectId:planId,totalAmount:600,items:[{subjectId:'SUB-01',subjectName:'交付人力',amount:600}],laborCost:600,procurementCost:0,outsourceCost:0,expenseCost:0,reserveCost:0};state=transition(state,{type:'submit-budget',projectId:planId,budget,reason:'首次项目预算'},pm);state=transition(state,{type:'review',approvalId:'APR-1',approve:true,opinion:'同意预算'},pmo);return transition(state,{type:'confirm-budget-baseline',approvalId:'APR-1'},pmo);}
describe('未签投入、合同及正式启动',()=>{
 it('追加申请固定敞口与额度，待审不释放，重复申请阻断，批准后只改额度和授权时限',()=>{const initial=createBusinessState();const p=initial.projects.find(p=>p.id===planId)!;const action={type:'request-unsigned-investment' as const,projectId:planId,amount:100,validUntil:'2026-12-31',expectedSignDate:'2026-10-15',signProgress:'客户进入合同审批',necessity:'继续技术验证',risk:'按期不签则停止新增投入',attachments:['申请.pdf']};let state=transition(initial,action,market);expect(state.projects.find(p=>p.id===planId)?.unsignedLimitQuota).toBe(0);expect(()=>transition(state,action,market)).toThrow('已有待审');const request=structuredClone(state.unsignedInvestmentRequests[0]);expect(()=>transition(state,{type:'review-management',id:request.approvalId,approve:true,opinion:'批准'},pmo)).toThrow('无权');state=transition(state,{type:'review-management',id:request.approvalId,approve:true,opinion:'同意限额与有效期'},leader);expect(state.projects.find(p=>p.id===planId)?.unsignedLimitQuota).toBe(100);expect(state.projects.find(p=>p.id===planId)?.actualCost).toBe(p.actualCost);expect(state.costs).toEqual(initial.costs);expect(state.unsignedProjects[planId].validUntil).toBe('2026-12-31');expect(state.unsignedInvestmentRequests[0]).toEqual(request);});
 it('更新跟进不会擅自延长授权，过期阻断新采购但已发生凭证照实归集',()=>{const initial=createBusinessState();const p=initial.projects[0];p.isUnsigned=true;p.unsignedLimitQuota=10000;initial.unsignedProjects[p.id]={...unsignedControl(initial,p),expectedSignDate:'2026-09-01',validUntil:'2026-09-01'};let state=transition(initial,{type:'follow-unsigned',projectId:p.id,progress:'客户延期',nextAction:'申请延期审批',expectedSignDate:'2026-10-01'},market);expect(state.unsignedProjects[p.id].validUntil).toBe('2026-09-01');expect(()=>transition(state,{type:'submit-cost-order',projectId:p.id,kind:'procurement',subjectId:'SUB-03',title:'新增采购',amount:1,supplier:'供应商',contractNo:'CG1',scope:'设备',dueDate:'2026-10-01'},pm)).toThrow('逾期');state.projects[0].unsignedLimitQuota=0;state=transition(state,{type:'confirm-cost',cost:{...state.costs[0],id:'ACTUAL-OVER',sourceId:'VOUCHER-OVER',amount:10}},finance);expect(state.costs.some(c=>c.sourceId==='VOUCHER-OVER')).toBe(true);expect(unsignedSummary(state,state.projects[0]).flags).toContain('投入超限');});
 it('签约必须有原单和守恒回款节点，失败不产生合同，签约不跳过启动',()=>{const state=planned();expect(()=>transition(state,{type:'confirm-project-contract',projectId:planId,registration:{...registration,receiptPlans:[]},source:'核验签署依据'},market)).toThrow('回款计划');expect(()=>transition(state,{type:'confirm-project-contract',projectId:planId,source:'只有自由文本'},market)).toThrow('缺少');const next=transition(state,{type:'confirm-project-contract',projectId:planId,registration,source:'核验原件主体及金额'},market);const p=next.projects.find(p=>p.id===planId)!;expect(p.isUnsigned).toBe(false);expect(p.contractAmount).toBe(1200);expect(p.phase).toBe('立项');expect(next.receiptPlans.filter(r=>r.projectId===planId).reduce((n,r)=>n+r.amount,0)).toBe(1200);expect(next.costs).toEqual(state.costs);expect(next.baselines).toEqual(state.baselines);});
 it('启动重验真实合同、任命和完整基线，保存独立快照并只生成一次团队通知',()=>{let state=planned();expect(()=>transition(state,{type:'confirm-project-start',projectId:planId,date:AS_OF_DATE,opinion:'启动'},pmo)).toThrow('真实已签合同');state=transition(state,{type:'confirm-project-contract',projectId:planId,registration,source:'原单一致'},market);const before=structuredClone(state);state=transition(state,{type:'confirm-project-start',projectId:planId,date:AS_OF_DATE,opinion:'按计划启动，责任人落实'},pmo);expect(state.projects.find(p=>p.id===planId)?.phase).toBe('执行');expect(state.startConfirmations[planId].notifications.some(n=>n.userId===pm.id)).toBe(true);expect(state.startConfirmations[planId].baseline).toEqual(before.baselines.find(b=>b.projectId===planId));expect(state.costs).toEqual(before.costs);expect(state.budgets).toEqual(before.budgets);expect(()=>transition(state,{type:'confirm-project-start',projectId:planId,date:AS_OF_DATE,opinion:'重复'},pmo)).toThrow('不得重复');});
 it('失效任命、历史摘要基线与建设冻结均不能启动',()=>{let state=planned();state=transition(state,{type:'confirm-project-contract',projectId:planId,registration,source:'原单核对'},market);const command={type:'confirm-project-start' as const,projectId:planId,date:AS_OF_DATE,opinion:'启动'};const noPm=structuredClone(state);noPm.projects.find(p=>p.id===planId)!.pmId='';expect(()=>transition(noPm,command,pmo)).toThrow('主PM');const noSnapshot=structuredClone(state);delete noSnapshot.baselines.find(b=>b.projectId===planId)!.snapshot;expect(()=>transition(noSnapshot,command,pmo)).toThrow('完整');state.constructionFreezes[planId]={requestId:'FREEZE',reason:'结算检查'};expect(()=>transition(state,command,pmo)).toThrow('冻结');});
 it('退出保留已发生流水和成本快照，追加审批不能给已终止项目释放额度',()=>{let state=createBusinessState();const p=state.projects.find(p=>p.id==='P-004')!;state=transition(state,{type:'exit-unsigned',projectId:p.id,reason:'客户取消采购',resources:'人员及设备投入',recoverableAssets:'设备转库待确认',responsibility:'主办部门组织复盘',recommendation:'完成资产处置并关闭经营线索',terminated:true,reactivationPossible:false},pmo);expect(state.projects.find(x=>x.id===p.id)?.status).toBe('已终止');expect(state.unsignedProjects[p.id].exit?.actualCost).toBe(p.actualCost);expect(state.unsignedProjects[p.id].exit?.costSources).toEqual(state.costs.filter(c=>c.projectId===p.id));expect(()=>transition(state,{type:'request-unsigned-investment',projectId:p.id,amount:10,validUntil:'2026-12-31',expectedSignDate:'2026-10-01',signProgress:'进展',necessity:'需求',risk:'风险',attachments:['依据']},market)).toThrow('有效未签');});
});
