import { useActionAccess } from '@/hooks/useActionAccess';
import { constructionLockReason } from '@/mock/construction-lock';
import { useState } from 'react';
import { Alert, App, Button, Card, Col, Descriptions, Drawer, Input, InputNumber, Modal, Row, Select, Space, Statistic, Table, Tag, Tabs, Timeline } from 'antd';
import { useNavigate, useParams, useSearchParams, useLocation } from 'react-router-dom';
import { useBusinessStore } from '@/mock/store';
import { costAvailability, costOrderLabels, isCostSubject, type CostOrderAction, type CostOrderKind } from '@/mock/cost-orders';
import { selectFourCalculations, visibleProjects } from '@/mock/selectors';
import { AS_OF_DATE, mockCostSources, mockProcurements, mockOutsources, mockExpenses } from '@/mock';
import { useAppStore } from '@/store/useAppStore';
import { sumMoney, money } from '@/utils/money';
import { PageSection, PageToolbar } from '@/components/common/PageSection';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';
import { MoneyText } from '@/components/common/MoneyText';
type Operation = Extract<CostOrderAction, { type: 'process-cost-order' }>['operation'];
const operationLabels: Record<Operation, string> = { approve: '批准申请', reject: '驳回申请', progress: '更新履约进度', accept: '确认验收通过', book: '确认实际入账' };
const kindTabs: { key: CostOrderKind; label: string }[] = [
  { key: 'procurement', label: '采购成本' },
  { key: 'outsource', label: '外包成本' },
  { key: 'expense', label: '项目费用' },
];

export function CostSourcesPage() {
  const {id}=useParams();const location=useLocation();
  const pathKind = location.pathname.includes('outsourcing') ? 'outsource' as const
    : location.pathname.includes('expenses') ? 'expense' as const
    : location.pathname.includes('procurement') || location.pathname.includes('costs') ? 'procurement' as const
    : undefined;
  const kind = (new URLSearchParams(window.location.search).get('kind') as CostOrderKind | null) ?? pathKind ?? 'procurement';
  return <CostSourcesContent key={`${id}-${kind}`} kind={kind}/>;
}
function CostSourcesContent({ kind }: { kind: CostOrderKind }) {
  const { canDo } = useActionAccess();
  const { id } = useParams(); const [params, setParams] = useSearchParams(); const navigate = useNavigate(); const { message } = App.useApp();
  const { data, dispatch } = useBusinessStore(); const { currentRole, currentUser } = useAppStore();
  const [open, setOpen] = useState(false); const [subjectId, setSubjectId] = useState(kind === 'procurement' ? 'SUB-03' : kind === 'outsource' ? 'SUB-02' : 'SUB-04-2');
  const [title, setTitle] = useState(''); const [amount, setAmount] = useState<number>(1); const [supplier, setSupplier] = useState(''); const [contractNo, setContractNo] = useState(''); const [scope, setScope] = useState(''); const [taskId, setTaskId] = useState<string>(); const [dueDate, setDueDate] = useState('2026-09-20');
  const [operation, setOperation] = useState<Operation>(); const [note, setNote] = useState(''); const [progress, setProgress] = useState(100);
  const p = data.projects.find((p) => p.id === id); if (!p) return <StateView type="404" />;
  if (!visibleProjects(currentRole, data.projects, data).some((p) => p.id === id)) return <StateView type="403" />;
  const calc = selectFourCalculations(p, data); const subjects = calc.subjects.filter((s) => isCostSubject(kind, s.subjectId));
  const availability = costAvailability(data, p.id, subjectId); const pm = currentRole === 'project-manager' && currentUser.id === p.pmId; const finance = currentRole === 'finance';
  const locked = !!constructionLockReason(data, p.id) || ['已关闭', '运维'].includes(p.phase) || ['已终止', '已关闭'].includes(p.status); const canSubmit = canDo('submit-cost-order',p.id) && !locked && (pm || kind === 'expense' && currentRole === 'solution-tech' && p.memberIds?.includes(currentUser.id));
  const orders = data.costOrders.filter((o) => o.projectId === id && o.kind === kind); const costs = data.costs.filter((c) => c.projectId === id && c.type === kind);
  const selected = orders.find((o) => o.id === params.get('source')); const voucher = costs.find((c) => c.sourceId === params.get('source'));
  const canProcess = (op: Operation | undefined) => !!op && !!selected && canDo('process-cost-order',selected.id) && !locked && (op === 'approve' || op === 'reject' ? finance && selected.status === '待审批' : op === 'book' ? finance && selected.status === (kind === 'expense' ? '已批准' : '验收通过') : pm && selected.status === '已批准');
  const canProcessCurrent = canProcess(operation);
  const source = mockCostSources.find((s) => s.id === voucher?.sourceId); const upstream = [...mockProcurements, ...mockOutsources, ...mockExpenses].find((s) => s.id === source?.upstreamId);
  const filter = (s: string, status: string) => (!params.get('search') || s.includes(params.get('search')!)) && (!params.get('status') || status === params.get('status'));
  const setParam = (key: string, value?: string) => { const next = new URLSearchParams(window.location.search); if (value) next.set(key, value); else next.delete(key); setParams(next); };
  const actor = { id: currentUser.id, name: currentUser.name, role: currentRole }; const label = costOrderLabels[kind];
  const setKind = (k: string) => { const next = new URLSearchParams(window.location.search); next.set('kind', k); next.delete('source'); setParams(next); };
  // Summary across all three cost kinds
  const allKinds: CostOrderKind[] = ['procurement', 'outsource', 'expense'];
  const summaryData = allKinds.map((k) => {
    const s = calc.subjects.filter((sub) => isCostSubject(k, sub.subjectId));
    const c = data.costs.filter((co) => co.projectId === p.id && co.type === k);
    return { kind: k, label: costOrderLabels[k], budget: sumMoney(s.map((sub) => sub.budget)), actual: sumMoney(c.map((co) => co.amount)), committed: sumMoney(s.map((sub) => sub.committed)), available: sumMoney(s.map((sub) => costAvailability(data, p.id, sub.subjectId).available)) };
  });
  return <><Tabs activeKey={kind} onChange={setKind} items={kindTabs} /><PageHeader title={`${label}成本`} description={`${p.id} · ${p.name} · 基准日 ${AS_OF_DATE} · 单位：万元`} breadcrumbs={[{ title: '首页', href: '/' }, { title: p.name, href: `/projects/${p.id}` }, { title: `${label}成本` }]} extra={<Space wrap><Button onClick={() => navigate(`/projects/${p.id}/dynamic-accounting`)}>查看动态核算</Button><Button type="primary" disabled={!canSubmit} onClick={() => { setTitle(''); setScope(''); setContractNo(''); setSupplier(''); setAmount(1); setTaskId(undefined); setOpen(true); }}>新建{label}申请</Button></Space>} />
    <Alert showIcon type={locked ? 'warning' : 'info'} message={locked ? '建设期已结束或成本锁定，仅可查看原始单据；运维费用须进入独立周期。' : `演示规则 COST-1：财务审批后形成承诺；${kind === 'expense' ? '财务确认发生后入账' : '主PM登记到货/履约100%并验收后，财务入账'}。超科目预算或未签额度时阻断，先完成额度审批。`} style={{ marginBottom: 16 }} />
    <Row gutter={[12,12]} style={{ marginBottom: 16 }}>{[['有效科目预算', sumMoney(subjects.map((s) => s.budget))], ['已确认实际', sumMoney(costs.map((c) => c.amount))], ['未发生承诺', sumMoney(subjects.map((s) => s.committed))], ['科目净余量', sumMoney(subjects.map((s) => costAvailability(data, p.id, s.subjectId).available))]].map(([name, value]) => <Col span={6} key={name}><Card size="small" style={{height:"100%",minHeight:110}}><Statistic title={name} value={value} formatter={() => <MoneyText value={Number(value)} />} /></Card></Col>)}</Row>
    <details style={{ marginBottom: 16, color: '#64748b', fontSize: 13 }}><summary style={{ cursor: 'pointer' }}>全部成本类型汇总（万元）</summary><Row gutter={[12, 12]} style={{ marginTop: 8 }}>{summaryData.map((s) => <Col span={8} key={s.kind}><Card size="small" title={s.label}><Statistic title="预算" value={s.budget} formatter={() => <MoneyText value={s.budget} />} /><Statistic title="已发生" value={s.actual} formatter={() => <MoneyText value={s.actual} />} style={{ marginTop: 8 }} /><Statistic title="承诺" value={s.committed} formatter={() => <MoneyText value={s.committed} />} style={{ marginTop: 8 }} /><Statistic title="可用" value={s.available} formatter={() => <MoneyText value={s.available} />} style={{ marginTop: 8 }} /></Card></Col>)}</Row></details>
    <PageToolbar><Input aria-label="成本申请搜索" placeholder="申请、合同、供应商或凭证" value={params.get('search') ?? ''} onChange={(e) => setParam('search', e.target.value)} style={{ width: 290 }} /><Select aria-label="成本申请状态" allowClear placeholder="全部状态" value={params.get('status') ?? undefined} onChange={(v) => setParam('status', v)} style={{ width: 160 }} options={['待审批', '驳回', '已批准', '验收通过', '已入账'].map((value) => ({ value, label: value }))} /><Button onClick={() => setParams({})}>重置查询</Button></PageToolbar>
    <Card size="small" title={`${label}申请与${kind === 'expense' ? '财务确认' : '合同履约'}`}><Table rowKey="id" size="small" dataSource={orders.filter((o) => filter(`${o.id} ${o.title} ${o.contractNo} ${o.supplier}`, o.status))} scroll={{ x: 1120 }} pagination={{ pageSize: 5, showSizeChanger: false }} columns={[{ title: '原申请 / 合同', width: 240, fixed: 'left', render: (_, o) => <Button type="link" style={{ height: 'auto', whiteSpace: 'normal', display: 'block', textAlign: 'left', padding: 0 }} onClick={() => setParam('source', o.id)}>{o.id} · {o.title}<br />{o.contractNo}</Button> }, { title: '供应商 / 收款方', dataIndex: 'supplier', width: 190 }, { title: '状态', dataIndex: 'status', width: 100, render: (v) => <Tag color={v==='驳回'?'red':v==='已入账'?'green':v==='待审批'?'orange':'blue'}>{v}</Tag> }, { title: '金额（万元）', dataIndex: 'amount', align:'right',width:120,render:v=><MoneyText value={v}/> }, { title: '已发生 / 未发生', width:170,align:'right',render:(_,o)=><><MoneyText value={o.recognized}/> / <MoneyText value={['已批准','验收通过'].includes(o.status)?money(o.amount-o.recognized):0}/></> }, { title: kind === 'procurement' ? '到货 / 验收' : '履约 / 验收', width: 140, render: (_, o) => kind === 'expense' ? '财务确认口径' : `${o.progress}% / ${o.acceptance ? '通过' : '待验收'}` }, { title: '计划日期', dataIndex: 'dueDate', width: 130 }, { title: '预算科目', dataIndex: 'subjectName', width: 130 }]} /></Card>
    <PageSection title="预算使用与申请控制" description="按生效科目分别控制，剩余预测不重复占用申请额度。"><Table size="small" rowKey="subjectId" pagination={false} dataSource={subjects.map((s) => ({ ...s, ...costAvailability(data, p.id, s.subjectId) }))} scroll={{ x: 760 }} columns={[{ title: '科目 / 生效版本', render: (_, s) => <>{s.subjectName}<div>{calc.budget?.version}</div></> }, ...(['budget', 'actual', 'committed', 'pending', 'available'] as const).map((key, i) => ({ title: ['预算', '已用', '已承诺', '待批占用', '可申请'][i], dataIndex: key, align:'right' as const, render: (v: number) => <MoneyText value={v} /> }))]} /><p>可申请 = 预算 − 已用 − 未发生承诺 − 待批占用。期初承诺按预算科目分摊，新批准合同按对应科目记录；剩余预测不重复占用申请额度；各科目独立控制，不相互抵扣。{p.isUnsigned && `未签投入上限 ${p.unsignedLimitQuota}，当前实际与承诺 ${money(p.actualCost + p.committedCost)}。`}</p></PageSection>
    <Card title="已确认来源明细（仅此金额计入实际）" size="small" style={{ marginTop: 16 }}><Table rowKey="id" size="small" dataSource={costs.filter((c) => filter(`${c.sourceId} ${c.description}`, '已入账'))} pagination={{ pageSize: 5, showSizeChanger: false }} columns={[{ title: '来源凭证', dataIndex: 'sourceId', render: (v) => <Button type="link" onClick={() => setParam('source', v)}>{v}</Button> }, { title: '摘要 / 科目', render: (_, c) => <>{c.description}<div>{c.subjectName}</div></> }, { title: '确认日期', dataIndex: 'occurredDate' }, { title: '实际金额（万元）', dataIndex: 'amount',align:'right', render: (v) => <MoneyText value={v} /> }]} /></Card>
    <Modal title={`新建${label}申请`} open={open} okButtonProps={{disabled:!canSubmit}} width={650} onCancel={() => setOpen(false)} onOk={() => { try { if(!canSubmit || !canDo('submit-cost-order',p.id))throw new Error('当前策略或项目状态不允许提交成本申请');dispatch({ type: 'submit-cost-order', kind, projectId: p.id, subjectId, title, amount, supplier, contractNo, scope, taskId, dueDate }, actor); setOpen(false); message.success('已提交财务审批，尚未计入实际'); } catch (e) { message.error((e as Error).message); } }}><Space direction="vertical" style={{ width: '100%' }}><label style={{display:"block",width:"100%"}}>成本申请标题<Input disabled={!canSubmit} aria-label="成本申请标题" placeholder="申请标题" value={title} onChange={(e) => setTitle(e.target.value)} /></label><label style={{display:"block",width:"100%"}}>申请成本科目<Select disabled={!canSubmit} aria-label="申请成本科目" style={{ width: '100%' }} value={subjectId} onChange={setSubjectId} options={subjects.map((s) => ({ value: s.subjectId, label: s.subjectName }))} /></label><label>本次金额（万元） <InputNumber disabled={!canSubmit} aria-label="申请金额" value={amount} min={0.01} precision={2} onChange={(v) => setAmount(v ?? 0)} /></label><Alert type={amount > availability.available ? 'error' : 'info'} message={`预算 ${availability.budget} · 已用 ${availability.actual} · 承诺 ${availability.committed} · 待批 ${availability.pending} · 本次 ${amount} · 申请后剩余 ${money(availability.available - amount)}`} /><label style={{display:"block",width:"100%"}}>供应商或收款方<Input disabled={!canSubmit} aria-label="供应商或收款方" placeholder={kind === 'expense' ? '收款方 / 费用承担人' : '供应商名称'} value={supplier} onChange={(e) => setSupplier(e.target.value)} /></label>{kind !== 'expense' && <label style={{display:"block",width:"100%"}}>采购外包合同号<Input disabled={!canSubmit} aria-label="采购外包合同号" placeholder="拟签合同号（审批后形成承诺）" value={contractNo} onChange={(e) => setContractNo(e.target.value)} /></label>}{kind === 'outsource' && <label style={{display:"block",width:"100%"}}>外包关联WBS<Select disabled={!canSubmit} aria-label="外包关联WBS" style={{ width: '100%' }} placeholder="关联项目WBS" value={taskId} onChange={setTaskId} options={data.tasks.filter((t) => t.projectId === p.id).map((t) => ({ value: t.id, label: t.name }))} /></label>}<label style={{display:"block",width:"100%"}}>成本申请范围用途<Input.TextArea disabled={!canSubmit} aria-label="成本申请范围用途" rows={3} placeholder={kind === 'outsource' ? '说明WBS内外包范围与交付物' : '物资清单 / 费用用途及必要性'} value={scope} onChange={(e) => setScope(e.target.value)} /></label><label style={{display:"block",width:"100%"}}>成本计划日期<Input disabled={!canSubmit} aria-label="成本计划日期" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label></Space></Modal>
    <Drawer title="原业务单据" width={700} open={!!params.get('source')} onClose={() => setParam('source')}>{selected ? <><Space wrap style={{ margin: '16px 0' }}>{(['approve', 'reject', ...(kind === 'expense' ? [] : ['progress', 'accept']), 'book'] as Operation[]).map((op) => <Button key={op} disabled={!canProcess(op)} onClick={() => { setOperation(op); setNote(''); setProgress(selected.progress); }}>{operationLabels[op]}</Button>)}</Space><Descriptions column={2} bordered size="small" items={[{ key: 'id', label: '申请编号', children: selected.id }, { key: 'status', label: '当前状态', children: selected.status }, { key: 'title', label: '申请事项', span: 2, children: selected.title }, { key: 'subject', label: '预算科目', children: selected.subjectName }, { key: 'base', label: '引用基线', children: selected.baselineId }, { key: 'supplier', label: '供应商/收款方', children: selected.supplier }, { key: 'contract', label: '合同号', children: selected.contractNo }, { key: 'amount', label: '申请/合同金额', children: <MoneyText value={selected.amount}/> }, { key: 'actual', label: '实际 / 未发生', children:<><MoneyText value={selected.recognized}/> / <MoneyText value={['已批准','验收通过'].includes(selected.status)?money(selected.amount-selected.recognized):0}/></> }, { key: 'scope', label: '范围/用途', span: 2, children: selected.scope }, { key: 'task', label: '关联WBS', span: 2, children: selected.taskId ? <Button onClick={() => navigate(`/projects/${p.id}/progress`)}>{data.tasks.find((t) => t.id === selected.taskId)?.name}</Button> : '不适用' }, ...(kind === 'expense' ? [] : [{ key: 'progress', label: '到货/履约', children: `${selected.progress}%` }, { key: 'accept', label: '验收说明', children: selected.acceptance ?? '尚未验收' }]), { key: 'applicant', label: '申请人', children: selected.applicant }, { key: 'date', label: '计划日期', children: selected.dueDate }]} /><Timeline items={selected.history.map((h) => ({ children: <><b>{h.date} · {h.actor} · {h.action}</b><p>{h.note}</p></> }))} /></> : voucher ? <Descriptions bordered column={1} items={[{ key: 'id', label: '原凭证', children: voucher.sourceId }, { key: 'amount', label: '已确认金额', children: voucher.amount }, { key: 'subject', label: '成本科目', children: voucher.subjectName }, { key: 'date', label: '确认日期', children: voucher.occurredDate }, { key: 'upstream', label: '上游单据', children: source?.upstreamId ?? '本轮原申请' }, { key: 'supplier', label: '上游主体', children: upstream ? 'supplierName' in upstream ? upstream.supplierName : 'vendorName' in upstream ? upstream.vendorName : upstream.applicant : '见原申请' }, { key: 'desc', label: '核算说明', children: `${voucher.description}；此凭证已计入实际一次，上游记录不重复相加。历史履约过程未提供，仅保留确认快照。` }]} /> : <StateView type="404" title="原单不存在" />}</Drawer>
    <Modal title={operation ? operationLabels[operation] : ''} open={!!operation} okButtonProps={{disabled:!canProcessCurrent}} onCancel={() => setOperation(undefined)} onOk={() => { try { if(!canProcess(operation))throw new Error('当前策略或单据状态不允许此操作');dispatch({ type: 'process-cost-order', id: selected!.id, operation: operation!, note, progress }, actor); setOperation(undefined); message.success('原单与统一核算已更新'); } catch (e) { message.error((e as Error).message); } }}><Space direction="vertical" style={{ width: '100%' }}>{operation === 'progress' && <InputNumber disabled={!canProcessCurrent} aria-label="履约完成率" min={0} max={100} value={progress} onChange={(v) => setProgress(v ?? 0)} />}<Input.TextArea disabled={!canProcessCurrent} aria-label="成本办理说明" placeholder="审批意见、到货/验收或财务入账说明（必填）" rows={4} value={note} onChange={(e) => setNote(e.target.value)} /></Space></Modal>
  </>;
}