import { canViewSensitiveField } from '@/mock/configuration-access';
import { constructionLockReason } from '@/mock/construction-lock';
import { useState } from 'react';
import { Alert, App, Button, Card, Descriptions, Drawer, Input, InputNumber, Modal, Select, Space, Table, Tabs, Tag } from 'antd';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { AS_OF_DATE, mockTimesheets } from '@/mock';
import { useBusinessStore } from '@/mock/business';
import { LABOR_RULE, laborAvailability, type LaborEntry } from '@/mock/labor';
import { visibleProjects } from '@/mock/selectors';
import { useAppStore } from '@/store/useAppStore';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';
import { MoneyText } from '@/components/common/MoneyText';
import { sumMoney } from '@/utils/money';

export function LaborCostPage() {
  const { id } = useParams(); const [params,setParams] = useSearchParams(); const navigate=useNavigate(); const { message }=App.useApp();
  const { data,dispatch }=useBusinessStore(); const { currentRole,currentUser }=useAppStore();
  const [editing,setEditing]=useState(false); const [date,setDate]=useState(AS_OF_DATE); const [task,setTask]=useState<string>(); const [hours,setHours]=useState(8); const [description,setDescription]=useState(''); const [review,setReview]=useState<boolean>(); const [opinion,setOpinion]=useState('');
  const p=data.projects.find((p)=>p.id===id); if(!p) return <StateView type="404" />;
  if(!visibleProjects(currentRole, data.projects, data).some((p)=>p.id===id)) return <StateView type="403" />;
  const pm=currentRole==='project-manager' && p.pmId===currentUser.id; const showCost=['project-manager','pmo','finance','executive','admin'].includes(currentRole); const showPersonalCost=showCost&&canViewSensitiveField(data,currentUser,'labor-rate');
  const member=pm || currentRole==='solution-tech' && !!p.memberIds?.includes(currentUser.id); const locked=p.phase!=='执行' || !!constructionLockReason(data, p.id) || p.status==='已终止';
  const actor={id:currentUser.id,name:currentUser.name,role:currentRole}; const a=laborAvailability(data,p.id); const tasks=data.tasks.filter((t)=>t.projectId===p.id);
  const update=(key:string,value?:string)=>{const next=new URLSearchParams(params); if(value)next.set(key,value);else next.delete(key);setParams(next);};
  const entries=data.laborEntries.filter((e)=>e.projectId===p.id && (showCost || e.userId===currentUser.id));
  const filtered=entries.filter((e)=>(!params.get('search') || `${e.id} ${e.userName} ${e.description}`.includes(params.get('search')!)) && (!params.get('status') || e.status===params.get('status')) && (!params.get('from') || e.date>=params.get('from')!) && (!params.get('to') || e.date<=params.get('to')!));
  const selected=entries.find((e)=>e.id===params.get('entry')); const imported=mockTimesheets.filter((e)=>e.projectId===p.id && (showCost || e.userId===currentUser.id));
  const aggregate=Object.values(filtered.reduce<Record<string,{name:string;hours:number;approved:number;amount:number}>>((out,e)=>{const row=out[e.userId]??={name:e.userName,hours:0,approved:0,amount:0};row.hours+=e.hours;if(e.status==='已通过'){row.approved+=e.hours;row.amount=sumMoney([row.amount,e.amount]);}return out;},{}));
  const submit=()=>{try{dispatch({type:'submit-labor',projectId:p.id,taskId:task??'',date,hours,description},actor);setEditing(false);message.success('已生成主PM审核待办，审核前不计入实际成本');}catch(e){message.error((e as Error).message);}};
  const columns=[{title:'工时原单',width:120,render:(_:unknown,e:LaborEntry)=><Button type="link" onClick={()=>update('entry',e.id)}>{e.id}</Button>},{title:'人员 / 日期',width:170,render:(_:unknown,e:LaborEntry)=><>{e.userName}<div>{e.date}</div></>},{title:'任务 / 工作内容',width:280,render:(_:unknown,e:LaborEntry)=><>{tasks.find((t)=>t.id===e.taskId)?.name}<div>{e.description}</div></>},{title:'小时',dataIndex:'hours',width:85,sorter:(x:LaborEntry,y:LaborEntry)=>x.hours-y.hours},{title:'状态',width:120,render:(_:unknown,e:LaborEntry)=><Tag color={e.status==='已通过'?'success':e.status==='已驳回'?'error':'processing'}>{e.status}</Tag>},...(showPersonalCost?[{title:'折算成本（万元）',width:150,render:(_:unknown,e:LaborEntry)=><MoneyText value={e.amount}/> }]:[]),{title:'办理',width:110,render:(_:unknown,e:LaborEntry)=><Button onClick={()=>update('entry',e.id)}>原单详情</Button>}];
  return <><PageHeader title="HS-09 工时与人力成本" description={`${p.id} · ${p.name} · ${p.departmentName} · ${p.phase}/${p.subPhase}`} breadcrumbs={[{title:'首页',href:'/'},{title:p.name,href:`/projects/${p.id}`},{title:'工时与人力成本'}]} extra={<Space>{showCost&&<Button onClick={()=>navigate(`/projects/${p.id}/dynamic-accounting?subject=SUB-01`)}>查看人力核算明细</Button>}<Button type="primary" disabled={!member||locked} onClick={()=>{setTask(tasks[0]?.id);setDescription('');setHours(8);setDate(AS_OF_DATE);setEditing(true);}}>填报本人工时</Button></Space>}/>
    <Alert showIcon type={locked?'warning':'info'} style={{marginBottom:16}} message={`演示规则 ${LABOR_RULE.version}：按0.5小时填报，同人跨项目每日最多8小时；仅执行项目成员填报，主PM审核（含本人）。${locked?'当前项目阶段禁止建设工时办理。':'通过后一次计费，优先从未发生人力承诺转为已发生。'}`} />
    {showCost?<Card size="small" title="当前阶段人力预算释放" style={{marginBottom:16}}><Descriptions column={3} items={[{key:'budget',label:'人力预算',children:<><MoneyText value={a.budget}/> 万元</>},{key:'released',label:`阶段累计释放 ${a.releaseRate}%`,children:<><MoneyText value={a.released}/> 万元</>},{key:'actual',label:'累计实际人力',children:<><MoneyText value={a.actual}/> 万元</>},{key:'pending',label:'待审占用',children:<><MoneyText value={a.pending}/> 万元</>},{key:'available',label:'释放可用',children:<><MoneyText value={a.available}/> 万元</>},{key:'commit',label:'未发生人力承诺',children:<><MoneyText value={a.committed}/> 万元</>}]} /><p>启动60% → 开发完成75% → 内部初验90% → 客户终验100%；按已达成里程碑释放，超额须先审批。实际以核算凭证为准。</p></Card>:<Alert message="成员视图仅显示本人工时；成本金额与人员单价不展示。" style={{marginBottom:16}}/>}
    {!showPersonalCost&&<Alert type="info" showIcon message="人员单价、费率版本及个人成本金额已隐藏；工时填报和审核仍按原职责办理。" style={{marginBottom:12}}/>}
    <Space wrap style={{marginBottom:12}}><Input aria-label="工时查询" placeholder="原单、姓名或工作内容" value={params.get('search')??''} onChange={(e)=>update('search',e.target.value)}/><Select aria-label="工时状态" placeholder="全部状态" allowClear style={{width:140}} value={params.get('status')??undefined} onChange={(v)=>update('status',v)} options={['待审核','已通过','已驳回'].map((value)=>({value,label:value}))}/><Input aria-label="工时开始日期" placeholder="开始 YYYY-MM-DD" style={{width:160}} value={params.get('from')??''} onChange={(e)=>update('from',e.target.value)}/><Input aria-label="工时结束日期" placeholder="结束 YYYY-MM-DD" style={{width:160}} value={params.get('to')??''} onChange={(e)=>update('to',e.target.value)}/><Button onClick={()=>setParams({})}>重置工时查询</Button></Space>
    <Tabs activeKey={params.get('tab')??'entries'} onChange={(v)=>update('tab',v)} items={[{key:'entries',label:`本轮填报（${filtered.length}）`,children:<Table rowKey="id" size="small" dataSource={filtered} columns={columns} scroll={{x:showPersonalCost?1135:985}} pagination={{pageSize:8,showSizeChanger:false}}/>},{key:'analysis',label:'投入分析',children:<><p>当前项目 / 主责组织：{p.departmentName}；仅汇总当前人员、状态与日期筛选内的本轮记录，驳回工时不计入有效投入。</p><Table rowKey="name" size="small" dataSource={aggregate} pagination={false} columns={[{title:'人员',dataIndex:'name'},{title:'填报小时',dataIndex:'hours'},{title:'审核有效小时',dataIndex:'approved'},...(showPersonalCost?[{title:'有效人力成本（万元）',render:(_:unknown,r:{amount:number})=><MoneyText value={r.amount}/>}]:[])]}/></>},{key:'history',label:`历史导入（${imported.length}）`,children:<><Alert message="历史快照仅供追溯，未提供完整费率和审批链，不能再次审核或据此重复生成成本；期初实际金额以已确认凭证为准。" style={{marginBottom:12}}/><Table rowKey="id" size="small" dataSource={imported} pagination={{pageSize:8,showSizeChanger:false}} columns={[{title:'导入编号',dataIndex:'id'},{title:'人员',dataIndex:'userName'},{title:'日期',dataIndex:'date'},{title:'工时',dataIndex:'hours'},{title:'来源状态',dataIndex:'status'},{title:'任务',render:(_,e)=>tasks.find((t)=>t.id===e.taskId)?.name??e.taskId}]}/></>}]} />
    <Drawer title="工时原单与成本依据" width={700} open={!!params.get('entry')} onClose={()=>update('entry')}>{selected?<><Descriptions bordered column={1} size="small" items={[{key:'id',label:'工时原单',children:selected.id},{key:'person',label:'人员 / 日期 / 工时',children:`${selected.userName} / ${selected.date} / ${selected.hours}小时`},{key:'task',label:'所属WBS',children:`${selected.taskId} ${tasks.find((t)=>t.id===selected.taskId)?.name}`},{key:'description',label:'工作内容',children:selected.description},{key:'status',label:'状态',children:selected.status},...(showPersonalCost?[{key:'rate',label:'提交时成本基准',children:`${selected.rateVersion} · ${selected.hourlyYuan}元/小时`},{key:'amount',label:'折算成本（万元）',children:<MoneyText value={selected.amount}/>}]:[]),{key:'baseline',label:'提交时项目基线',children:selected.baselineId},{key:'opinion',label:'审核记录',children:selected.reviewer?`${selected.reviewedAt} ${selected.reviewer}：${selected.opinion}`:'待主PM审核'},{key:'ledger',label:'成本确认',children:selected.ledgerId??'尚未生成核算凭证'}]}/><Space style={{marginTop:16}}><Button disabled={!pm||locked||selected.status!=='待审核'} onClick={()=>{setReview(true);setOpinion('');}}>审核工时通过</Button><Button danger disabled={!pm||locked||selected.status!=='待审核'} onClick={()=>{setReview(false);setOpinion('');}}>驳回工时</Button>{showPersonalCost&&selected.ledgerId&&<Button onClick={()=>navigate(`/projects/${p.id}/dynamic-accounting?subject=SUB-01`)}>查看已确认人力凭证</Button>}</Space></>:<StateView type="404" title="工时不存在或不在本人可见范围"/>}</Drawer>
    <Modal zIndex={1200} title="填报本人工时" open={editing} onCancel={()=>setEditing(false)} onOk={submit} okText="提交工时审核"><Space direction="vertical" style={{width:'100%'}}><p>{p.name} · 填报人 {currentUser.name}</p><Select aria-label="工时所属任务" style={{width:'100%'}} value={task} onChange={setTask} options={tasks.map((t)=>({value:t.id,label:`${t.name} · ${t.ownerName}`}))}/><Input aria-label="工时日期" value={date} onChange={(e)=>setDate(e.target.value)}/><label>投入小时 <InputNumber aria-label="投入小时" min={0.5} max={8} step={0.5} value={hours} onChange={(v)=>setHours(v??0)}/></label><Input.TextArea aria-label="工时工作内容" placeholder="工作内容（必填）" value={description} onChange={(e)=>setDescription(e.target.value)}/></Space></Modal>
    <Modal zIndex={1200} title={review?'确认工时通过并计费':'驳回工时'} open={review!==undefined} onCancel={()=>setReview(undefined)} onOk={()=>{try{dispatch({type:'review-labor',id:selected!.id,approve:review!,opinion},actor);setReview(undefined);message.success(review?'工时已通过，核算凭证已生成一次':'已驳回，保留原记录并释放待审占用');}catch(e){message.error((e as Error).message);}}}><Input.TextArea aria-label="工时审核意见" value={opinion} onChange={(e)=>setOpinion(e.target.value)} placeholder="审核意见（必填）"/></Modal>
  </>;
}
