import { useActionAccess } from '@/hooks/useActionAccess';
import { useState } from 'react';
import { Alert, App, Button, Checkbox, Descriptions, Drawer, Input, InputNumber, Modal, Select, Space, Table, Tag } from 'antd';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { AS_OF_DATE } from '@/mock';
import { useBusinessStore } from '@/mock/business';
import { currentWeek, dailyNeeded, reportSnapshot, REPORT_RULES } from '@/mock/reports';
import { visibleProjects } from '@/mock/selectors';
import { useAppStore } from '@/store/useAppStore';
import { PageSection, PageToolbar } from '@/components/common/PageSection';
import { MoneyText } from '@/components/common/MoneyText';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';

export function ReportsPage({ weekly = false }: { weekly?: boolean }) {
  const {id}=useParams();return <ReportsContent key={`${id}-${weekly}`} weekly={weekly}/>;
}
function ReportsContent({weekly}:{weekly:boolean}){
  const {canDo}=useActionAccess();
  const { id } = useParams(); const [params, setParams] = useSearchParams(); const navigate = useNavigate(); const { message } = App.useApp();
  const { data, dispatch } = useBusinessStore(); const { currentRole, currentUser } = useAppStore();
  const [editing, setEditing] = useState(false); const [hasProgress, setHasProgress] = useState(true); const [progress, setProgress] = useState(0); const [completed, setCompleted] = useState(''); const [reason, setReason] = useState(''); const [nextPlan, setNextPlan] = useState(''); const [coordination, setCoordination] = useState(''); const [linkedIds, setLinkedIds] = useState<string[]>([]);
  const [milestoneId, setMilestoneId] = useState<string>(); const [actualDate, setActualDate] = useState(AS_OF_DATE); const [milestoneNote, setMilestoneNote] = useState('');
  const p = data.projects.find((p) => p.id === id); if (!p) return <StateView type="404" />;
  if (!visibleProjects(currentRole, data.projects, data).some((p) => p.id === id)) return <StateView type="403" />;
  const pm = currentRole === 'project-manager' && p.pmId === currentUser.id && p.phase === '执行' && !data.lockedProjects.includes(p.id);
  const actor = { id: currentUser.id, name: currentUser.name, role: currentRole }; const week = currentWeek(); const snapshot = reportSnapshot(data, p.id);
  const daily = data.dailyReports.filter((r) => r.projectId === id); const weeks = data.weeklyReports.filter((r) => r.projectId === id);
  const selectedDaily = daily.find((r) => r.id === params.get('report')); const selectedWeek = weeks.find((r) => r.id === params.get('report')); const selected = weekly ? selectedWeek : selectedDaily; const snap = selected?.snapshot;
  const today = daily.find((r) => r.date === AS_OF_DATE); const current = weeks.find((r) => r.weekStart === week.start);
  const canSaveDaily=pm&&dailyNeeded(data,p.id)&&canDo('save-daily',p.id);const canSaveWeekly=pm&&selectedWeek?.status==='草稿'&&canDo('save-weekly',selectedWeek.id);const canEditReport=weekly?canSaveWeekly:canSaveDaily;
  const setParam = (key: string, value?: string) => { const next = new URLSearchParams(window.location.search); if (value) next.set(key, value); else next.delete(key); setParams(next); };
  const openDaily = () => { setProgress(today?.reportedProgress ?? p.progressRate); setHasProgress(today?.hasProgress ?? true); setCompleted(today?.hasProgress === false ? '' : today?.completedTasks ?? ''); setReason(today?.noProgressReason ?? ''); setNextPlan(today?.plannedTasks ?? ''); setCoordination(today?.coordination ?? ''); setLinkedIds(today?.linkedIds ?? []); setEditing(true); };
  const save = (submit: boolean) => { try { if(!canEditReport||!canDo(weekly?'save-weekly':'save-daily',weekly?selectedWeek?.id:p.id))throw new Error('当前策略或报告状态不允许保存及提交');if (weekly) dispatch({ type: 'save-weekly', id: selectedWeek!.id, submit, summary: completed, nextPlan, coordination }, actor); else dispatch({ type: 'save-daily', projectId: p.id, submit, progress, hasProgress, completed, reason, nextPlan, coordination, linkedIds }, actor); setEditing(false); message.success(submit ? weekly ? '已模拟上报指定范围，未发送外部消息' : '日报已提交，待办同步完成' : '草稿已保存'); } catch (e) { message.error((e as Error).message); } };
  const matches = (text: string) => !params.get('search') || text.includes(params.get('search')!);
  const milestones = data.milestones.filter((m) => m.projectId === id); const milestone = milestones.find((m) => m.id === milestoneId);const canCompleteMilestone=pm&&!!milestone&&milestone.status!=='已达成'&&canDo('complete-milestone',milestone.id);
  return <><PageHeader title={weekly ? 'HS-04 项目周报' : 'HS-03 项目日报'} description={`${p.id} · ${p.name} · ${p.phase}/${p.subPhase}`} breadcrumbs={[{ title: '首页', href: '/' }, { title: p.name, href: `/projects/${p.id}` }, { title: weekly ? '周报' : '日报' }]} extra={<Space><Button onClick={() => navigate(`/projects/${p.id}/${weekly ? 'daily-reports' : 'weekly-reports'}`)}>{weekly ? '查看项目日报' : '查看项目周报'}</Button>{weekly ? <Button type="primary" disabled={!pm||!current&&!canDo('create-weekly',p.id)} onClick={() => { try { if (current) setParam('report', current.id); else { if(!pm||!canDo('create-weekly',p.id))throw new Error('当前策略不允许生成周报');const newId = `WR-NEW-${data.weeklyReports.length + 1}`; dispatch({ type: 'create-weekly', projectId: p.id }, actor); setParam('report', newId); message.success('已生成本周快照草稿，可补充后上报'); } } catch (e) { message.error((e as Error).message); } }}>{current ? '打开本周周报' : '生成本周草稿'}</Button> : <Button type="primary" disabled={!canSaveDaily} onClick={openDaily}>{today?.status === '草稿' ? '继续今日日报' : today ? '今日日报已提交' : '填报今日日报'}</Button>}</Space>} />
    <Alert type="info" showIcon style={{ marginBottom: 16 }} message={weekly ? `演示规则 ${REPORT_RULES.version}：本周${week.start}至${week.end}，仅汇集截至${AS_OF_DATE}的事实；${REPORT_RULES.weeklyDeadline}前上报PMO及主责部门，重大项目追加PMC。` : `演示规则 ${REPORT_RULES.version}：执行中项目每日生成一项主PM日报待办，截止${REPORT_RULES.dailyDeadline}；${AS_OF_DATE} ${dailyNeeded(data, p.id) ? '尚待提交' : '已提交或不适用'}。PM填报比例单独保留，WBS实际完成率仍由任务加权。`} />
    <PageSection title={weekly?`本周 ${week.start} 至 ${week.end}`:`今日填报 · ${AS_OF_DATE}`} extra={<Tag>{weekly?(current?.status??'尚未生成'):(today?.status??(dailyNeeded(data,p.id)?'待填报':'当前不适用'))}</Tag>}><Descriptions size="small" column={3} items={[{ key: 'progress', label: 'WBS实际 / 计划', children: `${snapshot.actualProgress}% / ${snapshot.plannedProgress.toFixed(1)}%` }, { key: 'cost', label: '预算 / 实际 / 滚动', children: <><MoneyText value={snapshot.budget}/> / <MoneyText value={snapshot.actualCost}/> / <MoneyText value={snapshot.rollingCost}/> 万元</> }, { key: 'risk', label: '未关闭问题 / 监控风险', children: `${snapshot.issueIds.length} / ${snapshot.riskIds.length}` }]} /></PageSection>
    <PageToolbar><Input aria-label="报告查询" placeholder="日期、编号或进展" value={params.get('search') ?? ''} onChange={(e) => setParam('search', e.target.value)} style={{ width: 280 }} /><Button onClick={() => setParams({})}>重置查询</Button><Button onClick={() => navigate(`/projects/${p.id}/progress`)}>查看WBS及里程碑</Button><Button onClick={() => navigate(`/projects/${p.id}/deliverables`)}>维护必交材料</Button><Button onClick={() => navigate(`/issues-risks?projectId=${p.id}`)}>新增或查看问题风险</Button></PageToolbar>
    <PageSection title={weekly ? '周报记录 · 已上报版本只读' : '日报记录 · 每日一份，提交后保留'}>{weekly ? <Table rowKey="id" size="small" dataSource={weeks.filter((r) => matches(`${r.id} ${r.weekSpan} ${r.progressSummary}`))} pagination={{ pageSize: 8, showSizeChanger: false }} columns={[{ title: '周报周期', width: 220, render: (_, r) => <Button type="link" onClick={() => setParam('report', r.id)}>{r.weekSpan}</Button> }, { title: '进展摘要', dataIndex: 'progressSummary', ellipsis: true }, { title: '成本快照', dataIndex: 'costStatus', width: 230 }, { title: '状态', render: (_, r) => <Tag>{r.status ?? '历史导入'}</Tag> }, { title: '填报人', dataIndex: 'reporter' }]} /> : <Table rowKey="id" size="small" dataSource={daily.filter((r) => matches(`${r.id} ${r.date} ${r.completedTasks}`))} pagination={{ pageSize: 8, showSizeChanger: false }} columns={[{ title: '日期 / 原报告', width: 145, render: (_, r) => <Button type="link" onClick={() => setParam('report', r.id)}>{r.date}</Button> }, { title: '本日进展', dataIndex: 'completedTasks', ellipsis: true }, { title: '下一步计划', dataIndex: 'plannedTasks', ellipsis: true }, { title: 'PM填报比例', width: 125, render: (_, r) => r.reportedProgress === undefined ? '历史未提供' : `${r.reportedProgress}%` }, { title: '状态 / 填报人', width: 150, render: (_, r) => <>{r.status ?? '历史已提交'}<div>{r.reporter}</div></> }]} />}</PageSection>
    {!weekly && <PageSection title="里程碑实际达成 · 必交材料审核前不可完成"><Table rowKey="id" size="small" dataSource={milestones} pagination={false} columns={[{ title: '里程碑', dataIndex: 'type' }, { title: '计划 / 实际', render: (_, m) => `${m.plannedDate} / ${m.actualDate ?? '未达成'}` }, { title: '必交材料', render: (_, m) => m.requiredDeliverables.join('、') }, { title: '状态', dataIndex: 'status' }, { title: '操作', render: (_, m) => <Button disabled={!pm || m.status === '已达成'||!canDo('complete-milestone',m.id)} onClick={() => { setMilestoneId(m.id); setActualDate(AS_OF_DATE); setMilestoneNote(''); }}>登记实际达成</Button> }]} /></PageSection>}
    <Drawer title={weekly ? '周报快照与上报范围' : '日报原始记录'} width={760} open={!!params.get('report')} onClose={() => setParam('report')}>{selected ? <>{selectedWeek?.status === '草稿' && <Button type="primary" disabled={!canSaveWeekly} style={{ marginTop: 16 }} onClick={() => { setCompleted(selectedWeek.progressSummary); setNextPlan(selectedWeek.nextWeekPlan); setCoordination(selectedWeek.coordination ?? ''); setEditing(true); }}>补充并上报周报</Button>}<Descriptions bordered column={1} size="small" items={[{ key: 'id', label: '原报告', children: selected.id }, { key: 'status', label: '状态', children: selected.status ?? '历史导入，原记录保留' }, { key: 'summary', label: '本期进展', children: <div style={{ whiteSpace: 'pre-wrap' }}>{selectedWeek?.progressSummary ?? selectedDaily?.completedTasks}</div> }, { key: 'plan', label: '下期计划', children: selectedWeek?.nextWeekPlan ?? selectedDaily?.plannedTasks }, { key: 'coord', label: '协调事项', children: selected.coordination || '未填写' }, { key: 'recipients', label: weekly ? '模拟上报范围' : 'PM填报完成率', children: weekly ? selectedWeek?.recipients?.join('、') ?? '历史收件范围未提供' : selectedDaily?.reportedProgress === undefined ? '历史未提供' : `${selectedDaily.reportedProgress}%` }, ...(snap ? [{ key: 'snapshot', label: '提交/生成时快照', children: `截至${snap.capturedAt}，WBS实际${snap.actualProgress}% / 计划${snap.plannedProgress.toFixed(1)}%；预算${snap.budget} / 实际${snap.actualCost} / 滚动${snap.rollingCost}万元` }, { key: 'milestones', label: '里程碑快照', children: snap.milestoneSummary }] : [])]} />{snap && <PageSection title="独立业务来源"><p>日报 {snap.dailyIds.join('、') || '无当周已提交日报'}；WBS {snap.taskIds.length}项</p><Space wrap>{[...(selectedDaily?.linkedIds ?? []), ...snap.issueIds, ...snap.riskIds].filter((id, i, all) => all.indexOf(id) === i).map((id) => <Button key={id} onClick={() => navigate(`/issues-risks/${id}`)}>{id}</Button>)}</Space><p>报告保留当时数量和成本快照，原问题风险继续独立流转；不覆盖WBS基线。</p></PageSection>}{selectedWeek?.status === '已上报' && <Alert style={{ marginTop: 16 }} type="success" message={`已于${selectedWeek.submittedAt}完成站内模拟上报，历史快照已保留。`} />}</> : <StateView type="404" title="报告不存在" />}</Drawer>
    <Modal zIndex={1200} title={weekly ? '补充本周报告' : `${AS_OF_DATE} 日报填报`} width={720} open={editing} onCancel={() => setEditing(false)} footer={<Space><Button onClick={() => setEditing(false)}>取消</Button><Button disabled={!canEditReport} onClick={() => save(false)}>保存草稿</Button><Button type="primary" disabled={!canEditReport} onClick={() => save(true)}>{weekly ? '确认模拟上报' : '确认提交日报'}</Button></Space>}><Space direction="vertical" style={{ width: '100%' }}>{!weekly && <><label>PM填报整体完成率 <InputNumber disabled={!canEditReport} aria-label="日报完成率" min={0} max={100} value={progress} onChange={(v) => setProgress(v ?? 0)} /></label><Checkbox disabled={!canEditReport} checked={hasProgress} onChange={(e) => setHasProgress(e.target.checked)}>当天有进展</Checkbox></>}{weekly || hasProgress ? <label style={{display:"block",width:"100%"}}>本期进展<Input.TextArea disabled={!canEditReport} aria-label="报告进展" placeholder="最新进展与本期完成事项" rows={4} value={completed} onChange={(e) => setCompleted(e.target.value)} /></label> : <label style={{display:"block",width:"100%"}}>无进展原因（必填）<Input.TextArea disabled={!canEditReport} aria-label="无进展原因" placeholder="无进展原因（必填）" value={reason} onChange={(e) => setReason(e.target.value)} /></label>}<label style={{display:"block",width:"100%"}}>下一期计划（必填）<Input.TextArea disabled={!canEditReport} aria-label="报告下一步" placeholder="下一步/下周计划（必填）" rows={3} value={nextPlan} onChange={(e) => setNextPlan(e.target.value)} /></label><label style={{display:"block",width:"100%"}}>协调事项<Input.TextArea disabled={!canEditReport} aria-label="报告协调事项" placeholder="需要协调的事项（无可不填）" value={coordination} onChange={(e) => setCoordination(e.target.value)} /></label>{!weekly && <Select mode="multiple" disabled={!canEditReport} aria-label="日报关联问题风险" style={{ width: '100%' }} placeholder="关联本项目独立问题风险" value={linkedIds} onChange={setLinkedIds} options={[...data.issues, ...data.risks].filter((r) => r.projectId === p.id).map((r) => ({ value: r.id, label: `${r.id} ${r.title}` }))} />}</Space></Modal>
    <Modal zIndex={1200} title={`登记里程碑实际达成 · ${milestone?.type ?? ''}`} open={!!milestoneId} okButtonProps={{disabled:!canCompleteMilestone}} onCancel={() => setMilestoneId(undefined)} onOk={() => { try { if(!milestone||!canDo('complete-milestone',milestone.id)||!canCompleteMilestone)throw new Error('当前策略或里程碑状态不允许登记达成');dispatch({ type: 'complete-milestone', id: milestoneId!, actualDate, note: milestoneNote }, actor); setMilestoneId(undefined); message.success('里程碑实际日期已记录，原计划保持'); } catch (e) { message.error((e as Error).message); } }}><p>必交材料：{milestone?.requiredDeliverables.join('、')}，均须审核通过；未关闭重大问题会阻断。</p><Input disabled={!canCompleteMilestone} aria-label="里程碑实际日期" value={actualDate} onChange={(e) => setActualDate(e.target.value)} /><Input.TextArea disabled={!canCompleteMilestone} aria-label="里程碑达成说明" placeholder="实际达成说明（必填）" style={{ marginTop: 12 }} value={milestoneNote} onChange={(e) => setMilestoneNote(e.target.value)} /></Modal>
  </>;
}
