import type { ColumnsType } from 'antd/es/table';
import type { Opportunity } from '@/models/types';
import { useState } from 'react';
import { Alert, App, Button, Card, Col, DatePicker, Descriptions, Drawer, Form, Input, InputNumber, Modal, Row, Select, Space, Statistic, Table, Tag } from 'antd';
import { Link,useSearchParams } from 'react-router-dom';
import dayjs from 'dayjs';
import { useBusinessStore } from '@/mock/business';
import { canViewOpportunity } from '@/mock/opportunities';
import { earlyInvestmentWarnings,EARLY_INVESTMENT_RULE } from '@/mock/early-investments';
import { presalesSubjects } from '@/mock/presales';
import { useAppStore } from '@/store/useAppStore';
import { PageHeader } from '@/components/common/PageHeader';
import { MoneyText } from '@/components/common/MoneyText';
import { AnalysisTools } from '@/components/common/AnalysisTools';
import { PAGE_MANIFEST } from '@/routes/manifest';
import { sumMoney } from '@/utils/money';
export function EarlyInvestmentsPage(){
 const {data,dispatch}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const {message}=App.useApp();const [params,setParams]=useSearchParams();const [form]=Form.useForm();const [costForm]=Form.useForm();const [more,setMore]=useState(false);const [visible,setVisible]=useState(['1','2','3','4','5','6','7','8']);const [detailId,setDetailId]=useState<string>();const [costId,setCostId]=useState<string>();const requestId=Form.useWatch('requestId',costForm);
 const accessible=data.opportunities.filter(o=>canViewOpportunity(data,o,actor));const rows=accessible.filter(o=>(o.earlyInvestmentQuota>0||data.earlyInvestmentRequests.some(r=>r.opportunityId===o.id))&&(!params.get('search')||`${o.code} ${o.name} ${o.customerName}`.includes(params.get('search')!))&&(!params.get('owner')||o.ownerName.includes(params.get('owner')!))&&(!params.get('status')||o.status===params.get('status'))&&(!params.get('warning')||earlyInvestmentWarnings(data,o.id).length>0)&&(!params.get('department')||o.departmentName===params.get('department')));
 const detail=accessible.find(o=>o.id===detailId);const costs=data.earlyCosts.filter(c=>c.opportunityId===detailId);const requests=data.earlyInvestmentRequests.filter(r=>r.opportunityId===detailId);const selectedCostOpportunity=accessible.find(o=>o.id===costId);const approved=data.earlyInvestmentRequests.filter(r=>r.opportunityId===costId&&r.status==='通过');const request=approved.find(r=>r.id===requestId);const costSubjects=presalesSubjects(data).filter(s=>s.id!=='SUB-05');
 return <><PageHeader item={PAGE_MANIFEST.find(p=>p.id==='GS-11')} breadcrumbs={[{title:'商机与概算'},{title:'提前投入台账'}]} description={`批准额度与实际投入分开；原始成本按来源单据去重，正式立项后只继承一次。演示日2026-09-09，规则${EARLY_INVESTMENT_RULE.version}。`}/>
 <Row gutter={16} style={{marginBottom:16}}>{[{title:'有投入记录商机',value:rows.length,suffix:'个'},{title:'累计批准额度（万元）',value:sumMoney(rows.map(o=>o.earlyInvestmentQuota)),precision:2},{title:'累计已发生（万元）',value:sumMoney(rows.map(o=>o.earlyInvestmentUsed)),precision:2},{title:'异常商机',value:rows.filter(o=>earlyInvestmentWarnings(data,o.id).length).length,suffix:'个'}].map(s=><Col span={6} key={s.title}><Card size="small"><Statistic {...s}/></Card></Col>)}</Row>
 <Card size="small" style={{marginBottom:16}}><Form form={form} layout="inline" initialValues={Object.fromEntries(params)} onFinish={v=>{const next=new URLSearchParams();for(const[k,val]of Object.entries(v))if(val)next.set(k,String(val));setParams(next);}}><Space wrap><Form.Item name="search" label="商机 / 客户"><Input allowClear/></Form.Item><Form.Item name="warning" label="异常"><Select allowClear style={{width:130}} options={[{value:'yes',label:'仅有异常'}]}/></Form.Item><Form.Item name="status" label="商机状态"><Select allowClear style={{width:130}} options={['待评估','跟进中','拟立项','方案评审中','暂缓','已终止','已转立项'].map(value=>({value,label:value}))}/></Form.Item>{more&&<><Form.Item name="owner" label="负责人"><Input allowClear/></Form.Item><Form.Item name="department" label="部门"><Select allowClear style={{width:180}} options={[...new Set(accessible.map(o=>o.departmentName))].map(value=>({value,label:value}))}/></Form.Item></>}<Button type="primary" htmlType="submit">查询</Button><Button onClick={()=>{form.resetFields();setParams(new URLSearchParams());}}>重置</Button><Button type="link" onClick={()=>setMore(!more)}>{more?'收起':'更多筛选'}</Button></Space></Form></Card>
 <Card title="商机投入与风险敞口" size="small"><AnalysisTools storageKey={`early-investment-views-${actor.id}`} params={params} onChange={v=>{setParams(v);form.resetFields();form.setFieldsValue(Object.fromEntries(v));}} columns={['负责人 / 部门','状态','批准额度','已发生','剩余额度','使用率','有效期 / 签约计划','异常原因'].map((label,i)=>({value:String(i+1),label}))} visible={visible} onColumns={setVisible} exportRows={[["商机","批准额度（万元）","已发生（万元）","剩余（万元）","异常"],...rows.map(o=>[o.name,String(o.earlyInvestmentQuota),String(o.earlyInvestmentUsed),String(o.earlyInvestmentQuota-o.earlyInvestmentUsed),earlyInvestmentWarnings(data,o.id).join('；')])]}/><Table rowKey="id" size="small" dataSource={rows} scroll={{x:1550}} pagination={{pageSize:10,showSizeChanger:true,showTotal:n=>`共${n}条`}} columns={([{title:'商机 / 客户',width:260,fixed:'left',render:(_,o)=><><Link to={`/opportunities/${o.id}`}>{o.name}</Link><div style={{color:'#8c8c8c',fontSize:12}}>{o.customerName}</div></>},{title:'负责人 / 部门',width:150,render:(_,o)=><>{o.ownerName}<div>{o.departmentName}</div></>},{title:'状态',dataIndex:'status',width:100},{title:'批准额度（万元）',width:145,align:'right',sorter:(a,b)=>a.earlyInvestmentQuota-b.earlyInvestmentQuota,render:(_,o)=><MoneyText value={o.earlyInvestmentQuota}/>},{title:'已发生（万元）',width:140,align:'right',sorter:(a,b)=>a.earlyInvestmentUsed-b.earlyInvestmentUsed,render:(_,o)=><Button type="link" onClick={()=>setDetailId(o.id)}><MoneyText value={o.earlyInvestmentUsed}/></Button>},{title:'剩余额度（万元）',width:145,align:'right',render:(_,o)=><MoneyText value={o.earlyInvestmentQuota-o.earlyInvestmentUsed}/>},{title:'使用率',width:90,render:(_,o)=>o.earlyInvestmentQuota?`${(o.earlyInvestmentUsed/o.earlyInvestmentQuota*100).toFixed(1)}%`:'—'},{title:'有效期 / 签约计划',width:190,render:(_,o)=><>{data.earlyInvestmentRequests.filter(r=>r.opportunityId===o.id&&r.status==='通过').at(-1)?.endDate??'历史额度未提供有效期'}<div>预计签约 {o.expectedSignDate||'未确定'}</div></>},{title:'异常原因',width:180,render:(_,o)=>earlyInvestmentWarnings(data,o.id).map(x=><Tag key={x} color="orange">{x}</Tag>)},{title:'操作',width:180,fixed:'right',render:(_,o)=><Space wrap><Button size="small" onClick={()=>setDetailId(o.id)}>查看来源</Button><Link to={`/opportunities/${o.id}/early-investment`}>追加申请</Link>{actor.role==='finance'&&<Button size="small" disabled={['暂缓','已终止','已转立项'].includes(o.status)} onClick={()=>{costForm.resetFields();setCostId(o.id);}}>登记成本</Button>}</Space>} ] satisfies ColumnsType<Opportunity>).filter((_column,index)=>index===0||index===9||visible.includes(String(index)))}/></Card>
 <Drawer title={`${detail?.name??''} · 提前投入来源`} open={!!detail} width={850} onClose={()=>setDetailId(undefined)}>{detail&&<><Descriptions size="small" column={3} items={[{key:'quota',label:'批准额度',children:<MoneyText value={detail.earlyInvestmentQuota}/>},{key:'used',label:'已发生',children:<MoneyText value={detail.earlyInvestmentUsed}/>},{key:'left',label:'剩余额度',children:<MoneyText value={detail.earlyInvestmentQuota-detail.earlyInvestmentUsed}/>} ]}/>{detail.earlyInvestmentUsed>sumMoney(costs.map(c=>c.amount))&&<Alert style={{margin:'16px 0'}} type="info" message={`历史导入汇总 ${ (detail.earlyInvestmentUsed-sumMoney(costs.map(c=>c.amount))).toFixed(2)} 万元`} description="原种子数据只提供商机早期投入汇总，未提供原始单据；不伪造明细，也不重复追加到现有项目成本。以下为本演示实际新增的可追溯记录。"/>}<h4>批准申请与原审批</h4><Table size="small" rowKey="id" pagination={false} dataSource={requests} columns={[{title:'原申请',render:(_,r)=><Link to={`/opportunities/${detail.id}/early-investment?requestId=${r.id}`}>{r.id}</Link>},{title:'追加金额',render:(_,r)=><MoneyText value={r.amount}/>},{title:'状态',dataIndex:'status'},{title:'概算来源',dataIndex:'estimateId'},{title:'有效期',render:(_,r)=>`${r.startDate} ～ ${r.endDate}`} ]}/><h4>新发生成本与项目继承</h4><Table size="small" rowKey="id" dataSource={costs} pagination={false} scroll={{x:780}} columns={[{title:'来源单据',dataIndex:'sourceId'},{title:'科目',dataIndex:'subjectName'},{title:'金额',render:(_,c)=><MoneyText value={c.amount}/>},{title:'发生日期',dataIndex:'occurredDate'},{title:'说明',dataIndex:'description'},{title:'成本去向',render:(_,c)=>c.projectId?<Link to={`/projects/${c.projectId}/dynamic-accounting`}>已继承至 {c.projectId}</Link>:'商机前期成本'}]}/></>}</Drawer>
 <Modal title={`${selectedCostOpportunity?.name??''} · 登记前期成本`} open={!!selectedCostOpportunity&&actor.role==='finance'} width={680} onCancel={()=>setCostId(undefined)} okText="确认归集成本" onOk={async()=>{try{const v=await costForm.validateFields();dispatch({type:'record-early-cost',id:costId!,requestId:v.requestId,sourceId:v.sourceId,subjectId:v.subjectId,amount:v.amount,occurredDate:v.occurredDate.format('YYYY-MM-DD'),description:v.description},actor);setCostId(undefined);message.success('前期成本已归集到商机，原单据唯一保留');}catch(e){if(e instanceof Error)message.error(e.message);}}}><Form form={costForm} layout="vertical" initialValues={{occurredDate:dayjs('2026-09-09')}}><Form.Item name="requestId" label="已批准投入申请" rules={[{required:true}]}><Select options={approved.map(r=>({value:r.id,label:`${r.id} · ${r.amount}万元 · ${r.startDate}～${r.endDate}`}))}/></Form.Item>{request&&<Alert style={{marginBottom:16}} message={`该申请剩余 ${(request.amount-sumMoney(data.earlyCosts.filter(c=>c.requestId===request.id).map(c=>c.amount))).toFixed(2)} 万元`} description="系统将同时检查商机总额度、原申请额度、有效期、签约计划与商机状态。"/>}<Form.Item name="sourceId" label="来源单据编号（唯一）" rules={[{required:true,whitespace:true}]}><Input placeholder="例如：PRE-EXP-20260909-001"/></Form.Item><Row gutter={16}><Col span={12}><Form.Item name="subjectId" label="成本叶子科目" rules={[{required:true}]}><Select options={costSubjects.map(s=>({value:s.id,label:s.name}))}/></Form.Item></Col><Col span={12}><Form.Item name="amount" label="已发生成本（万元）" rules={[{required:true,type:'number',min:0.000001}]}><InputNumber min={0.000001} precision={6}/></Form.Item></Col></Row><Form.Item name="occurredDate" label="实际发生日期" rules={[{required:true}]}><DatePicker maxDate={dayjs('2026-09-09')}/></Form.Item><Form.Item name="description" label="成本内容与凭证说明" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={3}/></Form.Item></Form></Modal>
 </>;
}
