import { useState } from 'react';
import { Alert, App, Button, Card, Col, DatePicker, Descriptions, Form, Input, InputNumber, Row, Select, Space, Steps, Table, Tag } from 'antd';
import { Link,useNavigate,useParams,useSearchParams } from 'react-router-dom';
import dayjs from 'dayjs';
import { useBusinessStore } from '@/mock/business';
import { canManageOpportunity,canViewOpportunity } from '@/mock/opportunities';
import { earlyApprovalRoute,EARLY_INVESTMENT_RULE } from '@/mock/early-investments';
import type { EarlyInvestmentInput,EarlyInvestmentRequest } from '@/models/early-investments';
import type { Opportunity } from '@/models/types';
import { useAppStore } from '@/store/useAppStore';
import { mockUsers } from '@/mock';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';
import { MoneyText } from '@/components/common/MoneyText';
import { PAGE_MANIFEST } from '@/routes/manifest';
export function EarlyInvestmentPage(){const {id}=useParams();const [params]=useSearchParams();const {data}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const o=data.opportunities.find(o=>o.id===id);if(!o)return <StateView type="404"/>;if(!canViewOpportunity(data,o,actor))return <StateView type="403"/>;const request=data.earlyInvestmentRequests.find(r=>r.id===params.get('requestId')&&r.opportunityId===o.id);if(params.has('requestId')&&!request)return <StateView type="404"/>;return <InvestmentApplication key={request?.id??`new-${o.id}`} opportunity={o} request={request}/>;}
function InvestmentApplication({opportunity:o,request}:{opportunity:Opportunity;request?:EarlyInvestmentRequest}){
 const {data,dispatch}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const navigate=useNavigate();const {message,modal}=App.useApp();const [form]=Form.useForm();const [reviewOpinion,setReviewOpinion]=useState('');const amount=Form.useWatch('amount',form)??request?.amount??0;const riskLevel=Form.useWatch('riskLevel',form)??request?.riskLevel??'一般';const estimateId=Form.useWatch('estimateId',form)??request?.estimateId;const route=earlyApprovalRoute(amount,riskLevel);const writable=canManageOpportunity(data,o,actor)&&(!request||request.status==='草稿')&&!['已转立项','已终止','暂缓'].includes(o.status);const estimates=data.estimates.filter(e=>e.opportunityId===o.id&&e.isFrozen);const estimate=request?.estimateSnapshot??estimates.find(e=>e.id===estimateId);const requests=data.earlyInvestmentRequests.filter(r=>r.opportunityId===o.id);
 const save=async(submit:boolean)=>{try{if(submit)await form.validateFields();const v=form.getFieldsValue();const input:EarlyInvestmentInput={reason:v.reason??'',amount:v.amount??0,resourceTypes:v.resourceTypes??[],department:v.department??'',people:v.people??[],startDate:v.period?.[0]?.format('YYYY-MM-DD')??'',endDate:v.period?.[1]?.format('YYYY-MM-DD')??'',signPlanDate:v.signPlanDate?.format('YYYY-MM-DD')??'',signPlan:v.signPlan??'',riskLevel:v.riskLevel??'一般',risks:v.risks??'',exitPlan:v.exitPlan??'',estimateId:v.estimateId??''};const action=()=>{dispatch({type:'save-early-investment',id:o.id,requestId:request?.id,input,submit},actor);const id=request?.id??useBusinessStore.getState().data.earlyInvestmentRequests.at(-1)!.id;navigate(`/opportunities/${o.id}/early-investment?requestId=${id}`);message.success(submit?'投入申请已提交至规则指定审批角色':'申请草稿已保存');};if(submit)modal.confirm({title:'提交提前投入申请？',content:`申请 ${amount} 万元。${route.reason}。批准只形成额度，实际成本由财务按原单据登记。`,onOk:()=>{try{action();}catch(e){message.error((e as Error).message);return Promise.reject(e);}}});else action();}catch(e){if(e instanceof Error)message.error(e.message);}};
 const review=(approve:boolean)=>modal.confirm({title:approve?'批准本次追加投入额度？':'驳回投入申请？',content:'审批将记录原申请与引用概算快照，不能重复处理。',onOk:()=>{try{dispatch({type:'review-early-investment',id:o.id,requestId:request!.id,approve,opinion:reviewOpinion},actor);message.success(approve?'投入额度已增加':'申请已驳回，原额度不变');}catch(e){message.error((e as Error).message);return Promise.reject(e);}}});
 return <><PageHeader item={PAGE_MANIFEST.find(p=>p.id==='GS-10')} breadcrumbs={[{title:'商机台账',href:'/opportunities'},{title:o.name,href:`/opportunities/${o.id}`},{title:'提前投入申请'}]} description={`${o.code} · ${request?request.id:'新增申请'} · 立项前投入按商机独立归集，正式立项后按来源单据继承一次。`} extra={<Space><Link to="/early-investments">提前投入台账</Link><Link to={`/opportunities/${o.id}/early-investment`}>新建申请</Link></Space>}/>
 <Alert style={{marginBottom:16}} type="info" showIcon message={`${EARLY_INVESTMENT_RULE.name} · ${EARLY_INVESTMENT_RULE.version}`} description="演示硬上限：累计批准额度不超过预计项目金额10%；单笔超过100万元或高风险进入管理层审批，其余PMO。未发生投入可以直接进入立项，无需申请额度。"/>
 <Row gutter={16}><Col span={16}><Card size="small" title="投入需求与资源申请"><Form form={form} layout="vertical" disabled={!writable} initialValues={{...request,amount:request?.amount??0,department:request?.department??o.departmentName,people:request?.people??[o.ownerId],riskLevel:request?.riskLevel??'一般',estimateId:request?.estimateId??o.currentEstimateVersionId,period:[dayjs(request?.startDate||'2026-09-09'),dayjs(request?.endDate||'2026-09-30')],signPlanDate:dayjs(request?.signPlanDate||o.expectedSignDate||'2026-10-15')}}>
 <Form.Item name="reason" label="提前投入原因与业务必要性" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={3} placeholder="客户验证、交付窗口、采购周期等，说明为什么必须立项前投入"/></Form.Item><Row gutter={16}><Col span={12}><Form.Item name="amount" label="本次申请追加额度（万元）" rules={[{required:true,type:'number',min:0.01}]}><InputNumber min={0} precision={2} style={{width:'100%'}}/></Form.Item></Col><Col span={12}><Form.Item name="resourceTypes" label="投入资源类型" rules={[{required:true,type:'array',min:1}]}><Select mode="multiple" options={['人力','采购','外包','费用'].map(value=>({value,label:value}))}/></Form.Item></Col><Col span={12}><Form.Item name="department" label="投入责任部门" rules={[{required:true,whitespace:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="people" label="投入人员 / 责任人" rules={[{required:true,type:'array',min:1}]}><Select mode="multiple" maxTagCount={2} options={mockUsers.map(u=>({value:u.id,label:u.name}))}/></Form.Item></Col><Col span={12}><Form.Item name="period" label="计划投入周期" rules={[{required:true}]}><DatePicker.RangePicker/></Form.Item></Col><Col span={12}><Form.Item name="estimateId" label="引用冻结概算" rules={[{required:true}]}><Select options={estimates.map(e=>({value:e.id,label:`${e.version} · ${e.totalCost.toFixed(2)}万元成本`}))}/></Form.Item></Col></Row>
 <Form.Item name="signPlanDate" label="预计签约日期" rules={[{required:true}]}><DatePicker/></Form.Item><Form.Item name="signPlan" label="签约推进计划" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={2}/></Form.Item><Form.Item name="riskLevel" label="投入风险级别" rules={[{required:true}]}><Select options={['一般','高风险'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="risks" label="主要风险与控制措施" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={3}/></Form.Item><Form.Item name="exitPlan" label="退出方案与成本处置" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={3}/></Form.Item>
 {writable&&<Space><Button onClick={()=>save(false)}>保存草稿</Button><Button type="primary" onClick={()=>save(true)}>提交申请</Button><Button onClick={()=>navigate(`/opportunities/${o.id}`)}>取消</Button></Space>}
 </Form></Card><Card size="small" title="本商机申请历史" style={{marginTop:16}}><Table size="small" rowKey="id" pagination={false} dataSource={[...requests].reverse()} columns={[{title:'申请单',render:(_,r)=><Link to={`/opportunities/${o.id}/early-investment?requestId=${r.id}`}>{r.id}</Link>},{title:'追加金额（万元）',render:(_,r)=><MoneyText value={r.amount}/>},{title:'状态',render:(_,r)=><Tag color={r.status==='通过'?'green':r.status==='驳回'?'red':'blue'}>{r.status}</Tag>},{title:'有效周期',render:(_,r)=>`${r.startDate} ～ ${r.endDate}`},{title:'审批意见',dataIndex:'opinion'}]}/></Card></Col>
 <Col span={8}><Card size="small" title="额度与审批规则"><Descriptions column={1} size="small" items={[{key:'amount',label:'预计项目金额',children:<><MoneyText value={o.estimatedAmount}/> 万元</>},{key:'cap',label:'演示累计硬上限',children:<><MoneyText value={o.estimatedAmount*0.1}/> 万元</>},{key:'quota',label:'已批准额度',children:<><MoneyText value={o.earlyInvestmentQuota}/> 万元</>},{key:'used',label:'已使用成本',children:<><MoneyText value={o.earlyInvestmentUsed}/> 万元</>},{key:'left',label:'剩余额度',children:<><MoneyText value={o.earlyInvestmentQuota-o.earlyInvestmentUsed}/> 万元</>},{key:'estimate',label:'引用概算快照',children:estimate?`${estimate.id} / ${estimate.version}`:'尚未选择'}]}/><Alert style={{marginTop:16}} type={amount+o.earlyInvestmentQuota>o.estimatedAmount*0.1?'error':'info'} message={request?.ruleReason??route.reason} description={`规则 ${request?.ruleVersion??EARLY_INVESTMENT_RULE.version}。超过累计10%上限不能通过高阶审批绕过。`}/><Steps direction="vertical" size="small" style={{marginTop:16}} current={!request||request.status==='草稿'?0:request.status==='待审批'?1:2} items={[{title:'主办提交申请'},{title:request?.requiredRole==='executive'?'管理层审批':'PMO审批'},{title:'批准额度 / 驳回留痕'}]}/>
 {request&&<><Tag color={request.status==='通过'?'green':'blue'}>{request.status}</Tag><p>{request.reviewedBy??request.createdBy} · {request.reviewedAt??request.createdAt}</p><p>{request.opinion}</p></>}
 {request?.status==='待审批'&&actor.role===request.requiredRole&&<><Input.TextArea aria-label="投入审批意见" rows={4} value={reviewOpinion} onChange={e=>setReviewOpinion(e.target.value)} placeholder="审批意见必填"/><Space style={{marginTop:12}}><Button type="primary" onClick={()=>review(true)}>批准额度</Button><Button danger onClick={()=>review(false)}>驳回</Button></Space></>}
 {request?.status==='通过'&&<p><Link to="/early-investments">到投入台账登记前期成本</Link></p>}
 </Card></Col></Row></>;
}
