import { useActionAccess } from '@/hooks/useActionAccess';
import { canViewSensitiveField } from '@/mock/configuration-access';
import { useState } from 'react';
import { Alert, App, Button, Col, Descriptions, Empty, Input, InputNumber, Modal, Row, Select, Space, Table, Tabs, Tag } from 'antd';
import { Link, useParams } from 'react-router-dom';
import { useBusinessStore } from '@/mock/business';
import { canViewOpportunity } from '@/mock/opportunities';
import { costLineAmount, presalesSubjects, presalesWorkspace } from '@/mock/presales';
import { estimateFreezeMissing, estimateTotals } from '@/mock/estimates';
import type { EstimateDraft } from '@/models/estimates';
import { useAppStore } from '@/store/useAppStore';
import { PageSection, PageToolbar } from '@/components/common/PageSection';
import { MetricStatCard } from '@/components/common/MetricStatCard';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';
import { MoneyText } from '@/components/common/MoneyText';
import { PAGE_MANIFEST } from '@/routes/manifest';
export function EstimatePage(){const {id}=useParams();return <EstimatePageContent key={id}/>;}
function EstimatePageContent(){
 const {canDo,canEditField}=useActionAccess();
 const {id}=useParams();const {data,dispatch}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const {message,modal}=App.useApp();const [draft,setDraft]=useState<EstimateDraft|undefined>(()=>data.estimateDrafts[id??'']);const [reviewId,setReviewId]=useState<string>();const [freezeId,setFreezeId]=useState<string>();const [opinion,setOpinion]=useState('');const o=data.opportunities.find(o=>o.id===id);if(!o)return <StateView type="404"/>;if(!canViewOpportunity(data,o,actor))return <StateView type="403"/>;
 const showMargin=canViewSensitiveField(data,actor,'margin');const showLaborRate=canViewSensitiveField(data,actor,'labor-rate');const w=presalesWorkspace(data,o.id);const versions=data.estimates.filter(e=>e.opportunityId===o.id);const subjects=presalesSubjects(data);const totals=draft?estimateTotals(draft):undefined;const domainEditable=['solution-tech','finance'].includes(actor.role)&&!['暂缓','已终止'].includes(o.status);const editable=domainEditable&&canDo('estimate-save-draft',o.id);const canGenerate=domainEditable&&canDo('estimate-create-draft',o.id);const canPublish=editable&&canDo('estimate-publish',o.id);const canFreeze=actor.role==='pmo'&&canDo('estimate-freeze',o.id);const freezeMissing=freezeId?estimateFreezeMissing(data,freezeId):[];const update=(patch:Partial<EstimateDraft>)=>setDraft(d=>d?{...d,...patch}:d);
 const generate=()=>{try{if(!canGenerate||!canDo('estimate-create-draft',o.id))throw new Error('当前策略禁止生成概算草稿');dispatch({type:'estimate-create-draft',id:o.id,reviewId:reviewId??w.reviews.filter(r=>r.status==='通过').at(-1)?.id??''},actor);setDraft(useBusinessStore.getState().data.estimateDrafts[o.id]);message.success('已从通过评审的双版本生成草稿');}catch(e){message.error((e as Error).message);}};
 const save=(publish=false)=>{try{if(!editable||!canDo('estimate-save-draft',o.id)||publish&&(!canPublish||!canDo('estimate-publish',o.id)))throw new Error('当前策略不允许保存或发布概算');if(!draft)throw new Error('请先生成概算草稿');dispatch({type:'estimate-save-draft',id:o.id,draft},actor);if(publish)dispatch({type:'estimate-publish',id:o.id},actor);message.success(publish?'已追加概算版本，等待PMO确认冻结':'概算草稿已保存');}catch(e){message.error((e as Error).message);}};
 const lineTable=(filter:(subject:string)=>boolean=()=>true)=><Table rowKey="id" size="small" pagination={false} scroll={{x:1100}} dataSource={draft?.lines.filter(l=>filter(l.subjectId))??[]} columns={[{title:'统一科目 / 成本项',width:180,render:(_,l)=><>{subjects.find(s=>s.id===l.subjectId)?.name}<div>{l.name}</div></>},{title:'关联范围',dataIndex:'scope',width:180},{title:'数量',width:95,render:(_,l)=><InputNumber aria-label={`${l.name}数量`} disabled={!editable} value={l.quantity} min={0.001} style={{width:80}} onChange={v=>update({lines:draft!.lines.map(x=>x.id===l.id?{...x,quantity:v??0}:x)})}/>},{title:'单价（万元）',width:120,render:(_,l)=>l.subjectId==='SUB-01'&&!showLaborRate?'已隐藏':<InputNumber aria-label={`${l.name}单价`} disabled={!editable||l.subjectId==='SUB-01'&&!canEditField('labor-rate')} value={l.unitPrice} min={0} precision={6} style={{width:100}} onChange={v=>update({lines:draft!.lines.map(x=>x.id===l.id?{...x,unitPrice:v??0}:x)})}/>},{title:'税率 / 口径',width:105,render:(_,l)=>`${l.taxRate}% ${l.taxBasis}`},{title:'含税金额（万元）',width:135,align:'right',render:(_,l)=><MoneyText value={costLineAmount(l)}/>},{title:'测算依据',dataIndex:'basis',width:190},{title:'风险说明',dataIndex:'risk',width:160}]}/>;
 return <><PageHeader item={PAGE_MANIFEST.find(p=>p.id==='GS-08')} breadcrumbs={[{title:'商机台账',href:'/opportunities'},{title:o.name,href:`/opportunities/${o.id}`},{title:'项目概算编制'}]} description="根据通过评审的方案与技术成本生成概算。版本追加留痕，冻结后作为立项输入；金额统一为含税万元。" extra={<Space><Link to={`/opportunities/${o.id}/review`}>来源专家评审</Link><Link to={`/opportunities/${o.id}/estimate/compare`}>版本对比</Link>{o.currentEstimateVersionId&&<Link to={`/initiation/apply?opportunityId=${o.id}`}>按当前冻结版发起立项</Link>}</Space>}/>
 <PageSection title="概算来源与当前引用" description="通过评审的方案与成本是草稿输入；PMO确认冻结后才成为立项依据。"><PageToolbar><Select disabled={!canGenerate} aria-label="通过评审来源" placeholder="选择通过的专家评审" style={{width:300}} value={reviewId??w.reviews.filter(r=>r.status==='通过').at(-1)?.id} onChange={setReviewId} options={w.reviews.filter(r=>r.status==='通过').map(r=>({value:r.id,label:`第${r.round}轮 · ${r.solutionVersionId}`}))}/><Button disabled={!canGenerate} type="primary" onClick={()=>draft?modal.confirm({okButtonProps:{disabled:!canGenerate},title:'从评审版本重新生成草稿？',content:'当前草稿将被来源版本替换，已生成的历史概算版本保留。',onOk:generate}):generate()}>从通过评审生成草稿</Button><span>当前商机指定概算：{o.currentEstimateVersionId??'尚未指定'}</span></PageToolbar></PageSection>
 {totals&&<PageSection className="pms-record-summary"><Row gutter={16}>{[
 {title:'概算收入',value:totals.income,unit:'万元'}, {title:'概算成本',value:totals.cost,unit:'万元'},
 {title:'预期毛利',value:showMargin?totals.margin:'已隐藏',unit:showMargin?'万元':''},
 {title:'预期毛利率',value:showMargin?(totals.rate===null?'—':`${totals.rate.toFixed(1)}%`):'已隐藏',unit:''},
 ].map(metric=><Col span={6} key={metric.title}><MetricStatCard variant="flat" {...metric}/></Col>)}</Row></PageSection>}
 <PageSection><Tabs items={[{key:'overview',label:'概算总览',children:draft?<><h3>本草稿引用的评审版本</h3><Descriptions column={2} size="small" items={[{key:'review',label:'来源评审',children:<Link to={`/opportunities/${o.id}/review?review=${draft.reviewId}`}>{draft.reviewId}</Link>},{key:'solution',label:'方案版本',children:<Link to={`/opportunities/${o.id}/solution?version=${draft.solutionVersionId}`}>{draft.solutionVersionId}</Link>},{key:'cost',label:'成本评估版本',children:<Link to={`/opportunities/${o.id}/tech-cost?version=${draft.costVersionId}`}>{draft.costVersionId}</Link>},{key:'dept',label:'责任部门',children:draft.responsibleDepartment}]}/><Alert style={{marginTop:16}} type="info" message="调整数量或单价可保存草稿，但偏离评审明细时不能冻结" description="先在技术成本评估完成调整及新轮次评审，再导入新的通过版本。PMO冻结确认只改变本商机当前概算，不修改历史项目绑定版本。"/><h3 style={{marginTop:24}}>版本说明与测算假设</h3><p>修改原因（生成版本必填）</p><Input.TextArea disabled={!editable} value={draft.changeReason} onChange={e=>update({changeReason:e.target.value})}/><p>关键测算假设（必填）</p><Input.TextArea disabled={!editable} rows={3} value={draft.assumptions} onChange={e=>update({assumptions:e.target.value})}/></>:<Empty description="尚无概算草稿，请先从通过的专家评审生成"/>},
 {key:'income',label:'收入',children:draft?<Space wrap><span>预计收入</span><InputNumber aria-label="概算收入" disabled={!editable} min={0} value={draft.income} onChange={v=>update({income:v??0})}/><span>税率%</span><InputNumber aria-label="收入税率" disabled={!editable} min={0} max={100} value={draft.incomeTaxRate} onChange={v=>update({incomeTaxRate:v??0})}/><Select disabled={!editable} value={draft.incomeTaxBasis} onChange={v=>update({incomeTaxBasis:v})} options={['含税','不含税'].map(value=>({value,label:value}))}/><span>含税收入 <MoneyText value={totals?.income}/> 万元</span></Space>:null},
 {key:'construction',label:'建设成本',children:lineTable(s=>s==='SUB-02'||s==='SUB-03')},{key:'labor',label:'人力成本',children:lineTable(s=>s==='SUB-01')},{key:'third',label:'第三方费用',children:lineTable(s=>s==='SUB-04-1')},{key:'expense',label:'期间费用',children:lineTable(s=>s.startsWith('SUB-04')&&s!=='SUB-04-1')},{key:'risk',label:'风险成本',children:<>{lineTable(s=>s==='SUB-05')}<p>风险准备与不确定性说明</p><Input.TextArea disabled={!editable||!draft} value={draft?.riskReserveNote} onChange={e=>update({riskReserveNote:e.target.value})}/>{draft?.lines.filter(l=>l.risk).map(l=><p key={l.id}><Tag>{l.name}</Tag>{l.risk}</p>)}</>},
 {key:'margin',label:'毛利分析',children:!showMargin?<Alert message="毛利信息已隐藏"/>:totals?<><Descriptions column={1} items={[{key:'income',label:'含税收入',children:<MoneyText value={totals.income}/>},{key:'cost',label:'含税成本',children:<MoneyText value={totals.cost}/>},{key:'margin',label:'预期毛利',children:<MoneyText value={totals.margin}/>},{key:'rate',label:'预期毛利率',children:totals.rate===null?'—（收入为零）':`${totals.rate.toFixed(1)}%`} ]}/>{totals.rate!==null&&totals.rate<20&&<Alert type="warning" message="低于初评演示毛利阈值20%，请核对范围与测算依据"/>}</>:null},
 {key:'versions',label:`版本记录（${versions.length}）`,children:<Table rowKey="id" size="small" dataSource={[...versions].reverse()} pagination={false} expandable={{expandedRowRender:e=><Descriptions size="small" column={1} items={[{key:'source',label:'来源评审/方案/成本',children:data.estimateMeta[e.id]?<Space wrap size={4}><Link to={`/opportunities/${o.id}/review?review=${data.estimateMeta[e.id].reviewId}`}>{data.estimateMeta[e.id].reviewId}</Link><Link to={`/opportunities/${o.id}/solution?version=${data.estimateMeta[e.id].solutionVersionId}`}>{data.estimateMeta[e.id].solutionVersionId}</Link><Link to={`/opportunities/${o.id}/tech-cost?version=${data.estimateMeta[e.id].costVersionId}`}>{data.estimateMeta[e.id].costVersionId}</Link></Space>:'历史导入版本未保留本次评审链'},{key:'reason',label:'版本原因',children:data.estimateMeta[e.id]?.changeReason??'历史版本'},{key:'binding',label:'立项项目引用',children:data.projects.filter(p=>p.frozenEstimateVersionId===e.id).map(p=><Link key={p.id} to={`/projects/${p.id}`}>{p.name} </Link>)}]}/>}} columns={[{title:'版本',dataIndex:'version'},{title:'状态',render:(_,e)=><Tag color={e.isFrozen?'green':'orange'}>{e.isFrozen?'已冻结':'待确认'}</Tag>},{title:'收入 / 成本（万元）',align:'right',render:(_,e)=><><MoneyText value={e.totalIncome}/> / <MoneyText value={e.totalCost}/></>},{title:'毛利率',render:(_,e)=>!showMargin?'已隐藏':e.totalIncome?`${e.grossMarginRate.toFixed(1)}%`:'—'},{title:'创建人 / 日期',render:(_,e)=>`${e.createdBy} / ${e.createdAt}`},{title:'操作',render:(_,e)=><Button disabled={!canFreeze||e.isFrozen||!data.estimateMeta[e.id]} onClick={()=>{setFreezeId(e.id);setOpinion('');}}>确认冻结</Button>} ]}/>} ]}/>
 {draft&&domainEditable&&<div className="pms-form-actions"><Space><Button disabled={!editable} onClick={()=>save()}>保存草稿</Button><Button type="primary" disabled={!canPublish} onClick={()=>modal.confirm({okButtonProps:{disabled:!canPublish},title:'生成新的概算版本？',content:'本次保存为独立版本；由PMO核对来源后冻结，旧版本不被覆盖。',onOk:()=>save(true)})}>生成概算版本</Button><Button onClick={()=>setDraft(data.estimateDrafts[o.id])}>取消修改</Button></Space></div>}
 </PageSection><Modal title="PMO确认冻结概算" open={!!freezeId} okButtonProps={{disabled:!canFreeze||!freezeId||!opinion.trim()||freezeMissing.length>0}} onCancel={()=>setFreezeId(undefined)} okText="确认冻结" onOk={()=>{try{dispatch({type:'estimate-freeze',id:o.id,estimateId:freezeId!,opinion},actor);setFreezeId(undefined);message.success('概算已冻结并设为本商机当前版本，历史项目引用保持不变');}catch(e){message.error((e as Error).message);}}}><Alert type={freezeMissing.length?'warning':'success'} message="冻结条件检查" description={freezeId?(freezeMissing.join('；')||'来源专家评审通过，逐行成本与通过版本一致'):''}/><p>冻结确认意见（必填）</p><Input.TextArea disabled={!canFreeze} rows={4} value={opinion} onChange={e=>setOpinion(e.target.value)}/></Modal></>;
}
