import { presalesWorkspace } from '@/mock/presales';
import { useState } from 'react';
import { Alert, App, Button, Card, Col, DatePicker, Descriptions, Empty, Form, Input, Modal, Progress, Row, Space, Table, Tabs, Tag, Timeline } from 'antd';
import { Link, useParams } from 'react-router-dom';
import dayjs from 'dayjs';
import { useBusinessStore } from '@/mock/business';
import { assessmentSummary, canManageOpportunity, canViewOpportunity, DIMENSIONS, initiationMissing, opportunityMeta } from '@/mock/opportunities';
import { useAppStore } from '@/store/useAppStore';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';
import { MoneyText } from '@/components/common/MoneyText';
import { PAGE_MANIFEST } from '@/routes/manifest';
import { OpportunityActions } from './OpportunityActions';
export function OpportunityDetailPage() {
  const {id}=useParams();const {data,dispatch}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const {message}=App.useApp();const [follow,setFollow]=useState(false);const [form]=Form.useForm();
  const o=data.opportunities.find(o=>o.id===id);if(!o)return <StateView type="404"/>;if(!canViewOpportunity(data,o,actor))return <StateView type="403"/>;
  const m=opportunityMeta(data,o);const presales=presalesWorkspace(data,o.id);const latestReview=presales.reviews.at(-1);const s=assessmentSummary(o,m);const missing=initiationMissing(data,o);const estimate=data.estimates.find(e=>e.id===o.currentEstimateVersionId);const project=data.projects.find(p=>p.opportunityId===o.id);const sensitive=actor.role!=='project-manager';
  const basic=<Descriptions size="small" column={3} items={[{key:'customer',label:'客户',children:o.customerName},{key:'owner',label:'商机负责人',children:o.ownerName},{key:'dept',label:'主办部门',children:o.departmentName},{key:'type',label:'项目类型',children:m.projectType},{key:'source',label:'商机来源',children:m.source},{key:'region',label:'区域 / 业务线',children:`${m.region} / ${m.businessLine}`},{key:'amount',label:'预计金额',children:<><MoneyText value={o.estimatedAmount}/> 万元</>},{key:'sign',label:'预计签约',children:o.expectedSignDate||'未确定'},{key:'rate',label:'赢单概率',children:`${o.winRate}%`},{key:'desc',label:'业务背景与需求',span:3,children:m.description},{key:'comp',label:'竞争情况',span:3,children:m.competition},{key:'files',label:'客户材料',span:3,children:m.attachments.join('、')||'尚未提交附件'}]}/>;
  const evaluation=<><Space style={{marginBottom:16}}><Link to={`/opportunities/${o.id}/evaluation`}>进入商机初步评估</Link><Tag>{m.assessments.length} 轮记录</Tag></Space>{m.assessments.length?<Table size="small" rowKey="id" pagination={false} dataSource={[...m.assessments].reverse()} columns={[{title:'评估版本',render:(_,r)=>`V${r.version}`},{title:'状态',dataIndex:'status'},{title:'综合结论',dataIndex:'conclusion',render:v=>v??'未确认'},{title:'评分',dataIndex:'score',render:v=>v??'—'},{title:'风险等级',dataIndex:'riskLevel'},{title:'原因 / 意见',dataIndex:'reason'},{title:'确认日期',dataIndex:'confirmedAt'}]}/>:<Empty description="尚无初步评估记录"/>}</>;
  const businessTab=(label:string,path:string,content:React.ReactNode)=><><Space style={{marginBottom:16}}><Link to={`/opportunities/${o.id}/${path}`}>进入{label}</Link></Space>{content}</>;
  return <><PageHeader item={PAGE_MANIFEST.find(p=>p.id==='GS-03')} title={o.name} breadcrumbs={[{title:'商机台账',href:'/opportunities'},{title:'商机详情'}]} description={`${o.code} · ${o.customerName} · 负责人 ${o.ownerName}`} tags={[<Tag color={o.status==='已终止'?'red':o.status==='暂缓'?'orange':'blue'}>{o.status}</Tag>]} extra={<OpportunityActions opportunity={o}/>}/>
    {m.termination&&<Alert style={{marginBottom:16}} showIcon type="warning" message={`已终止 · ${m.termination.reason}`} description={`成本处置：${m.termination.costDisposition||'无投入'}；退出复盘：${m.termination.retrospective||'无'}。历史投入 ${m.termination.costSnapshot} 万元继续保留。`}/>}
    {o.status==='暂缓'&&m.pauses.at(-1)&&<Alert style={{marginBottom:16}} type="warning" showIcon message={`暂缓原因：${m.pauses.at(-1)!.reason}`} description={`复评日期 ${m.pauses.at(-1)!.reviewDate} · 责任人 ${m.pauses.at(-1)!.ownerName}；台账按演示日提醒。`}/>}
    <Card size="small"><Tabs defaultActiveKey="overview" items={[
      {key:'overview',label:'概览',children:<><Card size="small" title="商机基础信息">{basic}</Card><Row gutter={16} style={{marginTop:16}}><Col span={12}><Card size="small" title="转立项条件"><Progress percent={Math.round((4-missing.length)/4*100)}/>{project?<Alert type="success" message={<Link to={`/projects/${project.id}`}>已转入项目：{project.name}</Link>}/>:missing.length?<Alert type="warning" showIcon message="尚未满足发起立项条件" description={missing.map(x=><div key={x}>• {x}</div>)}/>:<Alert type="success" message="立项输入检查完成"/>}<p>初评转“拟立项”后启动方案任务；方案评审与冻结概算完成后，方可发起正式立项。</p></Card></Col><Col span={12}><Card size="small" title="评估与经营摘要"><Descriptions column={1} size="small" items={[{key:'score',label:'初评综合评分',children:s.score??'—'},{key:'risk',label:'初评风险等级',children:s.round?s.riskLevel:'尚未初评'},{key:'estimate',label:'指定概算版本',children:estimate?<Link to={`/opportunities/${o.id}/estimate`}>{estimate.version} · {estimate.isFrozen?'冻结':'草稿'}</Link>:'尚未指定'},{key:'cost',label:'概算总成本',children:sensitive?<><MoneyText value={estimate?.totalCost}/> 万元</>:'无敏感字段权限'},{key:'margin',label:'初评预估毛利率',children:sensitive&&s.marginRate!==null?`${s.marginRate.toFixed(1)}%`:'—'},{key:'quota',label:'提前投入额度 / 已使用',children:<><MoneyText value={o.earlyInvestmentQuota}/> / <MoneyText value={o.earlyInvestmentUsed}/> 万元</>},{key:'solution',label:'当前方案版本',children:presales.solutionVersions.at(-1)?`V${presales.solutionVersions.at(-1)!.version}`:'尚未提交评审'},{key:'review',label:'最近专家评审',children:latestReview?.status??'尚无专家结论'}]}/></Card></Col></Row><Card size="small" title="主要风险" style={{marginTop:16}}>{DIMENSIONS.filter(d=>s.round?.opinions[d.key]?.risk).map(d=><p key={d.key}><Tag>{d.name}</Tag>{s.round!.opinions[d.key]!.risk}</p>)}{!Object.values(s.round?.opinions??{}).some(v=>v.risk)&&<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="当前评估尚未登记风险项"/>}</Card></>},
      {key:'follow',label:'跟进记录',children:<>{canManageOpportunity(data,o,actor)&&!['已转立项','已终止'].includes(o.status)&&<Button type="primary" style={{marginBottom:16}} onClick={()=>{form.resetFields();setFollow(true);}}>追加跟进</Button>}{m.followups.length?<Timeline items={[...m.followups].reverse().map(f=>({children:<><strong>{f.date} · {f.author}</strong><p>客户沟通：{f.communication}</p><p>需求变化：{f.requirementChange||'无'}；商务进展：{f.commercialProgress||'无'}</p><p>下一步：{f.nextPlan}</p></>}))}/>:<Empty description="尚无跟进记录"/>}</>},
      {key:'assessment',label:'商机评估',children:evaluation},
      {key:'solution',label:'需求与方案',children:businessTab('需求调研与解决方案','solution',m.solutionTask?<Descriptions column={1} items={[{key:'id',label:'自动创建方案任务',children:m.solutionTask.id},{key:'owner',label:'任务责任人',children:m.solutionTask.ownerName},{key:'due',label:'计划完成',children:m.solutionTask.dueDate},{key:'source',label:'来源评估',children:m.solutionTask.assessmentId},{key:'status',label:'任务状态',children:m.solutionTask.status}]}/>:<Empty description="尚无方案任务，拟立项后自动创建"/>)},
      {key:'tech',label:'技术成本评估',children:businessTab('技术与成本评估','tech-cost',<p>技术结论：{presales.costDraft?.feasibility??s.round?.opinions.technology?.conclusion??'尚无技术评估'}。{presales.costDraft?.architecture??s.round?.opinions.technology?.note??''}</p>)},
      {key:'review',label:'专家评审',children:businessTab('方案与成本专家评审','review',latestReview?<Descriptions column={1} items={[{key:'round',label:'评审轮次',children:`第${latestReview.round}轮 · ${latestReview.status}`},{key:'version',label:'引用方案 / 成本',children:`${latestReview.solutionVersionId} / ${latestReview.costVersionId}`},{key:'reason',label:'专家综合意见',children:latestReview.conclusionReason??'评审中'},{key:'correction',label:'整改事项',children:latestReview.corrections.map(c=>c.item).join('；')||'无'}]}/>:<Empty description="尚无可引用的专家评审记录"/>)},
      {key:'estimate',label:'项目概算',children:businessTab('项目概算编制','estimate',sensitive?<Table size="small" rowKey="id" dataSource={data.estimates.filter(e=>e.opportunityId===o.id)} pagination={false} columns={[{title:'版本',dataIndex:'version'},{title:'状态',render:(_,e)=><Tag color={e.isFrozen?'green':'default'}>{e.isFrozen?'已冻结':'草稿'}</Tag>},{title:'总成本（万元）',render:(_,e)=><MoneyText value={e.totalCost}/>},{title:'毛利率',render:(_,e)=>`${e.grossMarginRate.toFixed(1)}%`},{title:'创建日期',dataIndex:'createdAt'}]}/>:<Alert message="当前角色无权查看概算敏感明细"/>)},
      {key:'investment',label:'提前投入',children:businessTab('提前投入申请','early-investment',<Descriptions items={[{key:'quota',label:'批准额度',children:<><MoneyText value={o.earlyInvestmentQuota}/> 万元</>},{key:'used',label:'已使用',children:<><MoneyText value={o.earlyInvestmentUsed}/> 万元</>},{key:'rest',label:'剩余额度',children:<><MoneyText value={o.earlyInvestmentQuota-o.earlyInvestmentUsed}/> 万元</>}]}/>)},
      {key:'audit',label:'操作记录',children:<Timeline items={data.audit.filter(a=>a.target===o.id).map(a=>({children:`${a.date} · ${a.actor} · ${({'save-opportunity':'保存商机','start-opportunity-assessment':'发起初步评估','save-opportunity-dimension':'保存专业意见','conclude-opportunity':'确认商机决策','follow-opportunity':'追加跟进','presales-save-solution':'保存方案草稿','presales-research':'追加需求调研','presales-save-cost':'保存技术成本','presales-finance-check':'财务成本核对','presales-submit-review':'发起专家评审','presales-expert-opinion':'提交专家意见','presales-review-decision':'记录专家评审结论','presales-correction-reply':'追加整改回复'} as Record<string,string>)[a.action]??a.action}`}))}/>},
    ]}/></Card>
    <Modal title="追加商机跟进" open={follow} onCancel={()=>setFollow(false)} okText="保存跟进" onOk={async()=>{try{const v=await form.validateFields();dispatch({type:'follow-opportunity',id:o.id,...v,date:v.date.format('YYYY-MM-DD')},actor);setFollow(false);message.success('已追加跟进，历史记录保留');}catch(e){if(e instanceof Error)message.error(e.message);}}}><Form form={form} layout="vertical" initialValues={{date:dayjs('2026-09-09')}}><Form.Item name="date" label="跟进日期" rules={[{required:true}]}><DatePicker maxDate={dayjs('2026-09-09')}/></Form.Item>{[{key:'communication',label:'客户沟通',required:true},{key:'requirementChange',label:'需求变化'},{key:'commercialProgress',label:'商务进展'},{key:'nextPlan',label:'下一步计划',required:true}].map(x=><Form.Item key={x.key} name={x.key} label={x.label} rules={[{required:x.required,whitespace:true}]}><Input.TextArea rows={2}/></Form.Item>)}</Form></Modal>
  </>;
}
