import { useState } from 'react';
import { Alert, App, Button, Card, Col, DatePicker, Descriptions, Empty, Form, Input, Modal, Row, Select, Space, Steps, Table, Tabs, Tag, Timeline, Upload } from 'antd';
import { Link, useParams } from 'react-router-dom';
import dayjs from 'dayjs';
import { useBusinessStore } from '@/mock/business';
import { canViewOpportunity } from '@/mock/opportunities';
import { costLineAmount, presalesReady, presalesWorkspace } from '@/mock/presales';
import { useAppStore } from '@/store/useAppStore';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';
import { MoneyText } from '@/components/common/MoneyText';
import { PAGE_MANIFEST } from '@/routes/manifest';
export function PresalesReviewPage() {
 const {id}=useParams();const {data,dispatch}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const {message,modal}=App.useApp();const [selected,setSelected]=useState<string>();const [dialog,setDialog]=useState<'submit'|'opinion'|'decision'|'reply'>();const [correctionId,setCorrectionId]=useState<string>();const [form]=Form.useForm();const conclusion=Form.useWatch('conclusion',form);
 const o=data.opportunities.find(o=>o.id===id);if(!o)return <StateView type="404"/>;if(!canViewOpportunity(data,o,actor))return <StateView type="403"/>;
 const w=presalesWorkspace(data,o.id);const latest=w.reviews.at(-1);const review=w.reviews.find(r=>r.id===selected)??latest;const solution=w.solutionVersions.find(v=>v.id===review?.solutionVersionId);const cost=w.costVersions.find(v=>v.id===review?.costVersionId);const missing=presalesReady(data,o.id);const current=review?.id===latest?.id;const expert=review?.experts.find(e=>e.userId===actor.id&&e.role===actor.role);const pending=review?.status==='评审中';
 const open=(mode:typeof dialog)=>{form.resetFields();form.setFieldsValue(mode==='submit'?{method:'线上专家评审会',plannedDate:dayjs('2026-09-10'),expertIds:['U-005','U-004']}:mode==='decision'?{conclusion:'通过',corrections:[{ownerId:'U-005',dueDate:dayjs('2026-09-20')}]}:{conclusion:'通过'});setDialog(mode);};
 const submit=async()=>{try{const v=await form.validateFields();const execute=()=>{if(dialog==='submit')dispatch({type:'presales-submit-review',id:o.id,method:v.method,plannedDate:v.plannedDate.format('YYYY-MM-DD'),expertIds:v.expertIds},actor);else if(dialog==='opinion')dispatch({type:'presales-expert-opinion',id:o.id,reviewId:review!.id,conclusion:v.conclusion,opinion:v.opinion,attachment:v.files?.[0]?.name??''},actor);else if(dialog==='decision')dispatch({type:'presales-review-decision',id:o.id,reviewId:review!.id,conclusion:v.conclusion,reason:v.reason,corrections:v.conclusion==='整改后复审'?(v.corrections??[]).map((c:{item:string;ownerId:string;dueDate:dayjs.Dayjs})=>({...c,dueDate:c.dueDate.format('YYYY-MM-DD')})):[]},actor);else dispatch({type:'presales-correction-reply',id:o.id,reviewId:review!.id,correctionId:correctionId!,response:v.response,attachment:v.files?.[0]?.name??''},actor);setDialog(undefined);setSelected(undefined);message.success('评审业务记录已更新');};
 if(dialog==='decision'||dialog==='submit')modal.confirm({title:dialog==='submit'?'冻结当前方案与成本并发起评审？':'确认本轮专家评审结论？',content:dialog==='submit'?'将生成新的方案版本、成本版本及材料包快照。':'本轮结论记录后不可覆盖；整改通过新版本及新轮次复审。',onOk:()=>{try{execute();}catch(e){message.error((e as Error).message);return Promise.reject(e);}}});else execute();}catch(e){if(e instanceof Error)message.error(e.message);}};
 return <><PageHeader item={PAGE_MANIFEST.find(p=>p.id==='GS-07')} breadcrumbs={[{title:'商机台账',href:'/opportunities'},{title:o.name,href:`/opportunities/${o.id}`},{title:'方案与成本专家评审'}]} description={`${o.code} · 每位专家独立留痕，评审材料始终引用提交时方案及成本版本。`} extra={<Space><Link to={`/opportunities/${o.id}/solution`}>方案编制</Link><Link to={`/opportunities/${o.id}/tech-cost`}>成本测算</Link><Link to={`/opportunities/${o.id}/estimate`}>项目概算</Link></Space>}/>
 <Row gutter={16}><Col span={16}><Card title="评审材料包" size="small" extra={<Select aria-label="评审轮次" style={{width:210}} value={review?.id} placeholder="评审轮次" onChange={setSelected} options={[...w.reviews].reverse().map(r=>({value:r.id,label:`第${r.round}轮 · ${r.status}`}))}/>}>
 {!review?<Empty description="尚无专家评审轮次，请先完成方案、技术成本与财务核对"/>:<><Descriptions size="small" column={2} items={[{key:'sid',label:'冻结方案版本',children:solution?`V${solution.version} · ${solution.id}`:'—'},{key:'cid',label:'冻结成本版本',children:cost?`V${cost.version} · ${cost.id}`:'—'},{key:'method',label:'评审方式',children:review.method},{key:'date',label:'计划日期',children:review.plannedDate},{key:'income',label:'预计收入（万元）',children:<MoneyText value={o.estimatedAmount}/>},{key:'cost',label:'冻结成本（万元）',children:<MoneyText value={cost?.total}/>} ]}/><Tabs style={{marginTop:16}} items={[{key:'solution',label:'需求与方案快照',children:solution?<Descriptions bordered size="small" column={1} items={[{key:'background',label:'客户现状',children:solution.customerSituation},{key:'goals',label:'建设目标',children:solution.goals},{key:'scope',label:'交付范围',children:solution.scope},{key:'bounds',label:'交付边界',children:solution.boundaries},{key:'architecture',label:'技术架构',children:solution.architecture},{key:'impl',label:'实施思路',children:solution.implementation},{key:'deliverables',label:'交付物',children:solution.deliverables},{key:'depend',label:'依赖与假设',children:`${solution.dependencies}；${solution.assumptions}`},{key:'files',label:'冻结材料',children:solution.attachments.join('、')} ]}/>:null},
 {key:'cost',label:'技术与成本快照',children:cost?<><Alert type={cost.feasibility==='可行'?'success':'warning'} message={`技术结论：${cost.feasibility}`} description={`${cost.architecture}；风险：${cost.risk||'无'}`}/><Table size="small" rowKey="id" scroll={{x:700}} pagination={false} dataSource={cost.lines} columns={[{title:'测算项',dataIndex:'name'},{title:'关联范围',dataIndex:'scope'},{title:'数量',dataIndex:'quantity'},{title:'含税金额（万元）',render:(_,l)=><MoneyText value={costLineAmount(l)}/>},{title:'依据 / 风险',render:(_,l)=>`${l.basis} / ${l.risk||'无'}`} ]}/><p>财务核对：{cost.financeCheck?.by} · {cost.financeCheck?.opinion}</p><p>技术材料：{cost.attachments.join('、')||'无附件'}</p></>:null},
 {key:'opinions',label:`专家独立意见（${review.opinions.length}/${review.experts.length}）`,children:<Timeline items={review.experts.map(e=>{const opinion=review.opinions.find(v=>v.userId===e.userId);return {color:opinion?.conclusion==='通过'?'green':opinion?'orange':'gray',children:<><strong>{e.name} · {e.dimension}</strong><p>{opinion?<><Tag>{opinion.conclusion}</Tag>{opinion.opinion}</>:'尚未提交本人意见'}</p>{opinion&&<p>{opinion.date} · 材料：{opinion.attachment||'无'}</p>}</>};})}/>},
 {key:'corrections',label:`整改事项（${review.corrections.length}）`,children:<Table rowKey="id" size="small" dataSource={review.corrections} pagination={false} expandable={{expandedRowRender:c=><Timeline items={c.replies.map(r=>({children:`${r.date} · ${r.by} · ${r.response} · ${r.attachment||'无附件'}`}))}/>}} columns={[{title:'整改事项',dataIndex:'item'},{title:'责任人',dataIndex:'ownerName'},{title:'截止日期',dataIndex:'dueDate'},{title:'回复',render:(_,c)=>c.replies.at(-1)?.response??'待回复'},{title:'操作',render:(_,c)=><Button disabled={!current||review.status!=='整改后复审'||actor.id!==c.ownerId||actor.role!=='solution-tech'} onClick={()=>{setCorrectionId(c.id);open('reply');}}>追加回复</Button>} ]}/>} ]}/></>}
 </Card><Card size="small" title="历史评审与版本链" style={{marginTop:16}}><Table size="small" rowKey="id" pagination={false} dataSource={[...w.reviews].reverse()} columns={[{title:'轮次',render:(_,r)=><Button type="link" onClick={()=>setSelected(r.id)}>第{r.round}轮</Button>},{title:'方案 / 成本版本',render:(_,r)=><>{r.solutionVersionId}<br/>{r.costVersionId}</>},{title:'结论',dataIndex:'status'},{title:'综合意见',dataIndex:'conclusionReason'},{title:'时间',dataIndex:'decidedAt'}]}/></Card></Col>
 <Col span={8}><Card size="small" title="评审流程与办理"><Steps direction="vertical" size="small" current={!review?0:pending?review.opinions.length<review.experts.length?1:2:3} items={[{title:'材料校验与冻结',description:'PMO选择专家、评审方式和计划时间'},{title:'专家独立评审',description:'技术与财务分别填写专业意见'},{title:'PMO汇总结论',description:'通过 / 整改后复审 / 不通过'},{title:'结果承接',description:'通过进入概算；整改追加版本并复审'}]}/>
 {review&&<Alert style={{marginTop:16}} type={review.status==='通过'?'success':review.status==='不通过'?'error':'info'} message={`当前查看：第${review.round}轮 · ${review.status}`} description={review.conclusionReason}/>}
 {!pending&&<Alert style={{marginTop:16}} type={missing.length?'warning':'success'} message={missing.length?'新轮次材料校验':'具备发起评审条件'} description={missing.map(x=><div key={x}>• {x}</div>)}/>}
 <Space direction="vertical" style={{marginTop:16,width:'100%'}}>{actor.role==='pmo'&&<Button block type="primary" disabled={missing.length>0||!['拟立项','方案评审中'].includes(o.status)} onClick={()=>open('submit')}>{w.reviews.length?'发起新一轮评审':'发起专家评审'}</Button>}{expert&&current&&pending&&<Button block type="primary" disabled={review!.opinions.some(v=>v.userId===actor.id)} onClick={()=>open('opinion')}>提交本人专家意见</Button>}{actor.role==='pmo'&&current&&pending&&<Button block type="primary" onClick={()=>open('decision')}>形成综合评审结论</Button>}{latest?.status==='整改后复审'&&<><Link to={`/opportunities/${o.id}/solution`}>响应整改并修改方案</Link><Link to={`/opportunities/${o.id}/tech-cost`}>重新测算技术成本</Link></>}{latest?.status==='通过'&&<Link to={`/opportunities/${o.id}/estimate`}>承接通过版本编制概算</Link>}</Space>
 </Card></Col></Row>
 <Modal title={dialog==='submit'?'组织专家评审':dialog==='opinion'?'本人专家意见':dialog==='decision'?'综合评审结论':'整改回复'} open={!!dialog} onCancel={()=>setDialog(undefined)} onOk={submit} width={720} okText="确认提交"><Form form={form} layout="vertical">
 {dialog==='submit'?<><Form.Item name="method" label="评审方式" rules={[{required:true}]}><Select options={['线上专家评审会','现场专家评审会','书面联合评审'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="plannedDate" label="评审计划日期" rules={[{required:true}]}><DatePicker minDate={dayjs('2026-09-09')}/></Form.Item><Form.Item name="expertIds" label="专家组（须包含技术及财务）" rules={[{required:true}]}><Select mode="multiple" options={[{value:'U-005',label:'赵工 · 技术与交付'},{value:'U-004',label:'刘敏 · 财务与成本'}]}/></Form.Item><Alert message="本演示使用方案技术与财务角色作为两个指定专家，切换身份分别填写，PMO不能代填。"/></>:dialog==='reply'?<><Form.Item name="response" label="整改响应及落实结果" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={4}/></Form.Item></>:<><Form.Item name="conclusion" label="评审结论" rules={[{required:true}]}><Select options={(dialog==='decision'?['通过','整改后复审','不通过']:['通过','整改','不通过']).map(value=>({value,label:value}))}/></Form.Item><Form.Item name={dialog==='decision'?'reason':'opinion'} label={dialog==='decision'?'综合结论说明':'专家独立意见'} rules={[{required:true,whitespace:true}]}><Input.TextArea rows={4}/></Form.Item>{dialog==='decision'&&conclusion==='整改后复审'&&<Form.List name="corrections">{(fields,{add,remove})=><>{fields.map(f=><Card size="small" key={f.key} style={{marginBottom:12}}><Form.Item name={[f.name,'item']} label="整改事项" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={2}/></Form.Item><Row gutter={16}><Col span={12}><Form.Item name={[f.name,'ownerId']} label="责任人" rules={[{required:true}]}><Select options={[{value:'U-005',label:'赵工 · 方案技术'}]}/></Form.Item></Col><Col span={12}><Form.Item name={[f.name,'dueDate']} label="截止日期" rules={[{required:true}]}><DatePicker minDate={dayjs('2026-09-10')}/></Form.Item></Col></Row><Button danger onClick={()=>remove(f.name)}>删除事项</Button></Card>)}<Button onClick={()=>add({ownerId:'U-005'})}>新增整改项</Button></>}</Form.List>}</>}
 {(dialog==='opinion'||dialog==='reply')&&<Form.Item name="files" label="意见 / 整改附件" valuePropName="fileList" getValueFromEvent={e=>e.fileList}><Upload beforeUpload={()=>false} maxCount={1}><Button>选择附件</Button></Upload></Form.Item>}
 </Form></Modal></>;
}
