import { useState } from 'react';
import { Alert, App, Button, Card, Col, DatePicker, Descriptions, Form, Input, Modal, Row, Select, Space, Table, Tabs, Tag, Timeline, Upload } from 'antd';
import dayjs from 'dayjs';
import { Link, useParams } from 'react-router-dom';
import { useBusinessStore } from '@/mock/business';
import { canViewOpportunity, opportunityMeta } from '@/mock/opportunities';
import { presalesWorkspace } from '@/mock/presales';
import { useAppStore } from '@/store/useAppStore';
import { mockUsers } from '@/mock';
import type { SolutionDraft } from '@/models/presales';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';
import { PAGE_MANIFEST } from '@/routes/manifest';
export function SolutionPage() {
  const {id}=useParams();const {data,dispatch}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const {message}=App.useApp();const [form]=Form.useForm();const [researchForm]=Form.useForm();const [research,setResearch]=useState(false);const [version,setVersion]=useState<string>();
  const o=data.opportunities.find(o=>o.id===id);if(!o)return <StateView type="404"/>;if(!canViewOpportunity(data,o,actor))return <StateView type="403"/>;
  const w=presalesWorkspace(data,o.id);const m=opportunityMeta(data,o);const draft=w.solutionDraft;const last=w.reviews.at(-1);const writable=actor.role==='solution-tech'&&['拟立项','方案评审中'].includes(o.status)&&last?.status!=='评审中';const selected=w.solutionVersions.find(v=>v.id===version);
  const save=async()=>{try{const v=await form.validateFields();const d:SolutionDraft={...v,startDate:v.plan[0].format('YYYY-MM-DD'),endDate:v.plan[1].format('YYYY-MM-DD'),attachments:(v.files??[]).map((f:{name:string})=>f.name),participants:v.participants??[],changeReason:v.changeReason??''};dispatch({type:'presales-save-solution',id:o.id,draft:d},actor);message.success('方案草稿已保存，成本测算需引用本次范围');}catch(e){if(e instanceof Error)message.error(e.message);}};
  const textFields=[{key:'customerSituation',label:'客户现状',placeholder:'现有业务流程、系统、痛点与客户访谈结论'},{key:'goals',label:'建设目标',placeholder:'业务目标及可衡量的验收目标'},{key:'scope',label:'交付范围',placeholder:'软件、硬件、集成、服务、运维的建设范围'},{key:'boundaries',label:'交付边界与约束',placeholder:'本次交付包含 / 不包含项，客户配合责任'},{key:'architecture',label:'总体技术架构',placeholder:'产品版本、技术路线、部署与集成架构'},{key:'implementation',label:'实施思路',placeholder:'实施阶段、迁移、测试、培训与上线方式'},{key:'deliverables',label:'主要交付物',placeholder:'交付物清单与验收标准'},{key:'dependencies',label:'外部依赖',placeholder:'第三方接口、资源、现场与政策依赖'},{key:'assumptions',label:'关键假设',placeholder:'测算及范围成立的前提条件'}];
  return <><PageHeader item={PAGE_MANIFEST.find(p=>p.id==='GS-05')} breadcrumbs={[{title:'商机台账',href:'/opportunities'},{title:o.name,href:`/opportunities/${o.id}`},{title:'需求调研与解决方案'}]} description={`${o.code} · ${o.status} · 方案范围是后续成本测算与专家评审的输入。`} extra={<Space><Link to={`/opportunities/${o.id}/tech-cost`}>技术与成本评估</Link><Link to={`/opportunities/${o.id}/review`}>专家评审</Link></Space>}/>
    {!['拟立项','方案评审中'].includes(o.status)&&<Alert showIcon type="warning" style={{marginBottom:16}} message="商机尚未达到拟立项，或已转入正式项目，当前方案只读"/>}
    {last?.status==='评审中'&&<Alert showIcon type="info" style={{marginBottom:16}} message={`第 ${last.round} 轮评审中，方案与成本快照已锁定`} description="评审完成后如需修改，请保存新的方案草稿并重新评估成本。"/>}
    <Card size="small"><Tabs items={[{key:'draft',label:'方案编制',children:<Form form={form} layout="vertical" disabled={!writable} initialValues={{...draft,ownerId:draft?.ownerId??'U-005',participants:draft?.participants??['U-006'],plan:[dayjs(draft?.startDate??'2026-09-09'),dayjs(draft?.endDate??'2026-09-20')],customerSituation:draft?.customerSituation??m.description,files:draft?.attachments.map((name,i)=>({uid:String(i),name,status:'done'}))??[]}}>
      <Card size="small" title="调研任务与责任"><Row gutter={16}><Col span={8}><Form.Item name="ownerId" label="方案负责人" rules={[{required:true}]}><Select options={mockUsers.map(u=>({value:u.id,label:u.name}))}/></Form.Item></Col><Col span={8}><Form.Item name="participants" label="参与人"><Select mode="multiple" maxTagCount={2} options={mockUsers.map(u=>({value:u.id,label:u.name}))}/></Form.Item></Col><Col span={8}><Form.Item name="plan" label="计划时间" rules={[{required:true}]}><DatePicker.RangePicker/></Form.Item></Col></Row>{m.solutionTask&&<span>来源任务 {m.solutionTask.id} · 初评 {m.solutionTask.assessmentId}</span>}</Card>
      <Row gutter={16} style={{marginTop:16}}>{textFields.map(f=><Col span={f.key==='scope'||f.key==='architecture'?24:12} key={f.key}><Form.Item name={f.key} label={f.label} rules={[{required:true,whitespace:true}]}><Input.TextArea rows={f.key==='scope'||f.key==='architecture'?3:2} placeholder={f.placeholder}/></Form.Item></Col>)}</Row>
      <Form.Item name="files" label="正式方案附件" valuePropName="fileList" getValueFromEvent={e=>e.fileList} extra="保存草稿可暂不上传；PMO发起评审前必须有正式方案附件。仅记录文件名。"><Upload beforeUpload={()=>false} maxCount={5}><Button>选择方案文件</Button></Upload></Form.Item>
      <Form.Item name="changeReason" label="版本修改说明" rules={[{required:w.solutionVersions.length>0,whitespace:true}]}><Input.TextArea rows={2} placeholder="说明相对上一评审版本的范围、架构或交付调整"/></Form.Item><Space><Button type="primary" onClick={save}>保存方案草稿</Button><Button onClick={()=>form.resetFields()}>取消修改</Button></Space>
    </Form>},
    {key:'research',label:`需求调研记录（${w.research.length}）`,children:<><Button disabled={!['market','solution-tech'].includes(actor.role)||!['拟立项','方案评审中'].includes(o.status)||last?.status==='评审中'} onClick={()=>{researchForm.resetFields();setResearch(true);}} style={{marginBottom:16}}>追加客户调研</Button><Timeline items={[...w.research].reverse().map(r=>({children:<><strong>{r.date} · {r.by}</strong><p>{r.findings}</p><p>范围变化：{r.scopeChange||'无'}；材料：{r.attachment||'无'}</p></>}))}/></>},
    {key:'versions',label:`方案版本（${w.solutionVersions.length}）`,children:<><Table rowKey="id" size="small" dataSource={[...w.solutionVersions].reverse()} pagination={false} columns={[{title:'版本',render:(_,v)=><Button type="link" onClick={()=>setVersion(v.id)}>V{v.version}</Button>},{title:'版本ID',dataIndex:'id'},{title:'修改说明',dataIndex:'changeReason'},{title:'提交日期',dataIndex:'submittedAt'},{title:'提交人',dataIndex:'submittedBy'},{title:'状态',render:()=> <Tag>评审冻结快照</Tag>}]}/><p>提交评审时产生新版本；历史快照始终只读，编辑当前草稿不会覆盖历史。</p></>},
    {key:'corrections',label:'评审整改',children:<><Link to={`/opportunities/${o.id}/review`}>查看逐条整改、责任人与回复</Link><Table size="small" rowKey="id" pagination={false} dataSource={w.reviews.flatMap(r=>r.corrections)} columns={[{title:'整改事项',dataIndex:'item'},{title:'责任人',dataIndex:'ownerName'},{title:'截止日期',dataIndex:'dueDate'},{title:'最新回复',render:(_,c)=>c.replies.at(-1)?.response??'待回复'}]}/></>}]}/></Card>
    <Modal title="追加需求调研" open={research} onCancel={()=>setResearch(false)} onOk={async()=>{try{const v=await researchForm.validateFields();dispatch({type:'presales-research',id:o.id,findings:v.findings,scopeChange:v.scopeChange??'',attachment:v.files?.[0]?.name??''},actor);setResearch(false);message.success('调研记录已追加');}catch(e){if(e instanceof Error)message.error(e.message);}}}><Form form={researchForm} layout="vertical"><Form.Item name="findings" label="客户沟通与调研发现" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={4}/></Form.Item><Form.Item name="scopeChange" label="范围变化与约束"><Input.TextArea/></Form.Item><Form.Item name="files" label="调研纪要" valuePropName="fileList" getValueFromEvent={e=>e.fileList}><Upload beforeUpload={()=>false} maxCount={1}><Button>选择材料</Button></Upload></Form.Item></Form></Modal>
    <Modal title={`方案历史快照 V${selected?.version??''}`} width={860} open={!!selected} onCancel={()=>setVersion(undefined)} footer={<Button onClick={()=>setVersion(undefined)}>关闭</Button>}>{selected&&<Descriptions bordered column={1} size="small" items={textFields.map(f=>({key:f.key,label:f.label,children:selected[f.key as keyof SolutionDraft] as string}))}/>}</Modal>
  </>;
}
