import { canViewSensitiveField } from '@/mock/configuration-access';
import { useState } from 'react';
import { Alert, App, Button, Card, Col, DatePicker, Descriptions, Form, Input, InputNumber, Modal, Popconfirm, Row, Select, Space, Statistic, Table, Tabs, Tag, Upload } from 'antd';
import { Link, useParams } from 'react-router-dom';
import dayjs from 'dayjs';
import { useBusinessStore } from '@/mock/business';
import { canViewOpportunity } from '@/mock/opportunities';
import { costLineAmount, costTotal, presalesSubjects, presalesWorkspace, solutionFingerprint } from '@/mock/presales';
import { selectCostRate } from '@/mock/configuration-finance';
import type { CostDraft, PresalesCostLine } from '@/models/presales';
import { useAppStore } from '@/store/useAppStore';
import { mockUsers } from '@/mock';
import { PageHeader } from '@/components/common/PageHeader';
import { MoneyText } from '@/components/common/MoneyText';
import { StateView } from '@/components/common/StateView';
import { PAGE_MANIFEST } from '@/routes/manifest';
import { sumMoney } from '@/utils/money';
export function TechCostPage() {
 const {id}=useParams();const {data,dispatch}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const {message,modal}=App.useApp();const [form]=Form.useForm();const [lineForm]=Form.useForm();const [lines,setLines]=useState<PresalesCostLine[]>(()=>presalesWorkspace(data,id??'').costDraft?.lines??[]);const [lineId,setLineId]=useState<string>();const [financeNote,setFinanceNote]=useState('');const subject=Form.useWatch('subjectId',lineForm);const person=Form.useWatch('laborUserId',lineForm);
 const o=data.opportunities.find(o=>o.id===id);if(!o)return <StateView type="404"/>;if(!canViewOpportunity(data,o,actor))return <StateView type="403"/>;
 const showMargin=canViewSensitiveField(data,actor,'margin');const showLaborRate=canViewSensitiveField(data,actor,'labor-rate');const w=presalesWorkspace(data,o.id);const current=w.costDraft;const locked=w.reviews.at(-1)?.status==='评审中'||!['拟立项','方案评审中'].includes(o.status);const writable=actor.role==='solution-tech'&&!locked;const subjects=presalesSubjects(data);const currentRate=(userId:string)=>selectCostRate(data,{userId,orgId:o.departmentId,projectType:data.opportunityMeta[o.id]?.projectType??'all'});const laborDayRate=(userId:string)=>currentRate(userId).dayYuan/10000;const scopeChanged=!!current&&!!w.solutionDraft&&current.solutionFingerprint!==solutionFingerprint(w.solutionDraft);
 const save=async()=>{try{const v=await form.validateFields();const draft:CostDraft={...v,solutionFingerprint:'',lines,attachments:(v.files??[]).map((f:{name:string})=>f.name),risk:v.risk??''};dispatch({type:'presales-save-cost',id:o.id,draft},actor);setLines(useBusinessStore.getState().data.presales[o.id].costDraft!.lines);message.success('成本草稿已保存，请财务核对当前测算');}catch(e){if(e instanceof Error)message.error(e.message);}};
 const total=sumMoney(lines.map(costLineAmount));const financial=()=>modal.confirm({title:'确认当前已保存成本测算？',content:'财务核对将绑定当前明细和范围指纹；后续任何调整均需再次核对。',onOk:()=>{try{dispatch({type:'presales-finance-check',id:o.id,opinion:financeNote},actor);message.success('财务核对意见已记录');}catch(e){message.error((e as Error).message);return Promise.reject(e);}}});
 const openLine=(l?:PresalesCostLine)=>{lineForm.resetFields();lineForm.setFieldsValue(l?{...l,quotationExpiry:l.quotationExpiry?dayjs(l.quotationExpiry):undefined}:{subjectId:'SUB-01',quantity:1,unit:'人天',unitPrice:0,taxRate:0,taxBasis:'含税',laborUserId:'U-005',scope:w.solutionDraft?.scope});setLineId(l?.id??'new');};
 return <><PageHeader item={PAGE_MANIFEST.find(p=>p.id==='GS-06')} breadcrumbs={[{title:'商机台账',href:'/opportunities'},{title:o.name,href:`/opportunities/${o.id}`},{title:'技术与成本评估'}]} description="成本统一折算为含税金额（万元）；人力按统一基准的人天单价测算，采购保留询价有效期。" extra={<Space><Link to={`/opportunities/${o.id}/solution`}>需求与方案</Link><Link to={`/opportunities/${o.id}/review`}>专家评审</Link></Space>}/>
 <Row gutter={16} style={{marginBottom:16}}>{[{title:'预计收入（万元）',value:o.estimatedAmount},{title:'当前草稿成本（万元）',value:total},{title:'测算毛利（万元）',value:showMargin?o.estimatedAmount-total:'已隐藏'},{title:'测算毛利率',value:showMargin?(o.estimatedAmount?(o.estimatedAmount-total)/o.estimatedAmount*100:0):'已隐藏',suffix:showMargin?'%':''}].map(s=><Col span={6} key={s.title}><Card size="small"><Statistic precision={2} {...s}/></Card></Col>)}</Row>
 {!w.solutionDraft&&<Alert style={{marginBottom:16}} type="warning" showIcon message="请先保存方案范围，再编制成本测算"/>}{scopeChanged&&<Alert style={{marginBottom:16}} type="warning" showIcon message="方案范围已变化，当前成本失去最新范围关联" description="请核对各成本行对应范围，保存成本草稿并重新获得财务核对后再发起评审。"/>}{locked&&<Alert style={{marginBottom:16}} type="info" message="当前处于评审或只读阶段，不能覆盖方案与成本输入"/>}
 <Card size="small"><Tabs items={[{key:'technical',label:'技术可行性',children:<Form form={form} layout="vertical" disabled={!writable} initialValues={{...current,feasibility:current?.feasibility??'可行',files:current?.attachments.map((name,i)=>({uid:String(i),name,status:'done'}))??[]}}><Form.Item name="feasibility" label="技术可行性结论" rules={[{required:true}]}><Select style={{width:220}} options={['可行','有条件可行','不可行'].map(value=>({value,label:value}))}/></Form.Item><Row gutter={16}>{[{key:'architecture',label:'架构与产品版本'},{key:'reuse',label:'现有产品可复用程度'},{key:'customization',label:'定制开发与集成难度'},{key:'environment',label:'部署环境与资源可用性'},{key:'security',label:'安全合规与质量要求'},{key:'dependencies',label:'第三方依赖与交付条件'}].map(x=><Col span={12} key={x.key}><Form.Item name={x.key} label={x.label} rules={[{required:true,whitespace:true}]}><Input.TextArea rows={3}/></Form.Item></Col>)}</Row><Form.Item name="risk" label="技术风险与关键成本假设"><Input.TextArea rows={3}/></Form.Item><Form.Item name="files" label="技术评估 / 询价汇总附件" valuePropName="fileList" getValueFromEvent={e=>e.fileList}><Upload beforeUpload={()=>false} maxCount={5}><Button>选择附件</Button></Upload></Form.Item><Button type="primary" onClick={save}>保存技术与成本草稿</Button></Form>},
 {key:'lines',label:`成本明细（${lines.length}）`,children:<><Alert style={{marginBottom:16}} type="info" message={`人力基准 ${currentRate('U-001').versionId} · 单价由现有工时基准 × 8小时/人天换算；外包、采购、第三方及期间费用使用统一科目ID。`}/><Space style={{marginBottom:16}}><Button type="primary" disabled={!writable||!w.solutionDraft} onClick={()=>openLine()}>新增成本项</Button><Button disabled={!writable} onClick={save}>保存技术与成本草稿</Button></Space><Table size="small" rowKey="id" dataSource={lines} scroll={{x:1150}} pagination={false} columns={[{title:'科目 / 名称',width:170,render:(_,l)=><>{subjects.find(s=>s.id===l.subjectId)?.name}<div>{l.name}</div></>},{title:'关联方案范围',width:190,dataIndex:'scope'},{title:'数量',dataIndex:'quantity',width:80},{title:'单位',dataIndex:'unit',width:70},{title:'单价（万元）',width:120,align:'right',render:(_,l)=>l.subjectId==='SUB-01'&&!showLaborRate?'已隐藏':<MoneyText value={l.unitPrice}/>},{title:'税率 / 口径',width:110,render:(_,l)=>`${l.taxRate}% ${l.taxBasis}`},{title:'含税金额（万元）',width:135,align:'right',render:(_,l)=><MoneyText value={costLineAmount(l)}/>},{title:'依据 / 风险',width:200,render:(_,l)=><>{l.basis}{l.risk&&<div style={{color:'#d46b08'}}>{l.risk}</div>}{l.quotationExpiry&&<Tag color={l.quotationExpiry<'2026-09-09'?'red':'blue'}>询价至 {l.quotationExpiry}</Tag>}</>},{title:'操作',width:110,fixed:'right',render:(_,l)=><Space><Button type="link" size="small" disabled={!writable} onClick={()=>openLine(l)}>编辑</Button><Popconfirm title="移除当前草稿成本项？" onConfirm={()=>setLines(lines.filter(x=>x.id!==l.id))}><Button type="link" size="small" danger disabled={!writable}>删除</Button></Popconfirm></Space>}]} summary={()=> <Table.Summary.Row><Table.Summary.Cell index={0} colSpan={6}>含税成本合计</Table.Summary.Cell><Table.Summary.Cell index={6}><MoneyText value={total}/></Table.Summary.Cell><Table.Summary.Cell index={7} colSpan={2}/></Table.Summary.Row>}/><p>新增、删除仅修改当前页面草稿；保存后统一写入技术评估。财务核对始终针对已保存数据。</p></>},
 {key:'finance',label:'财务成本核对',children:<><Descriptions column={2} items={[{key:'total',label:'已保存成本（万元）',children:<MoneyText value={costTotal(current)}/>},{key:'status',label:'财务核对',children:current?.financeCheck?`${current.financeCheck.by} · ${current.financeCheck.date}`:'尚未核对'},{key:'opinion',label:'财务意见',span:2,children:current?.financeCheck?.opinion??'—'}]}/>{actor.role==='finance'&&!locked&&<><Input.TextArea style={{marginTop:16}} rows={4} value={financeNote} onChange={e=>setFinanceNote(e.target.value)} placeholder="确认成本口径、单价来源、询价有效期与范围覆盖"/><Button style={{marginTop:16}} type="primary" onClick={financial}>确认当前测算</Button></>}</>},
 {key:'history',label:`历史成本快照（${w.costVersions.length}）`,children:<Table size="small" rowKey="id" dataSource={[...w.costVersions].reverse()} pagination={false} expandable={{expandedRowRender:v=><Table size="small" pagination={false} rowKey="id" dataSource={v.lines} columns={[{title:'成本项',dataIndex:'name'},{title:'方案范围',dataIndex:'scope'},{title:'数量',dataIndex:'quantity'},{title:'含税金额（万元）',render:(_,l)=><MoneyText value={costLineAmount(l)}/>} ]}/>}} columns={[{title:'版本',render:(_,v)=>`V${v.version}`},{title:'引用方案',dataIndex:'solutionVersionId'},{title:'冻结成本（万元）',render:(_,v)=><MoneyText value={v.total}/>},{title:'提交人',dataIndex:'submittedBy'},{title:'提交日期',dataIndex:'submittedAt'}]}/>} ]}/></Card>
 <Modal title={lineId==='new'?'新增成本项':'编辑成本项'} width={760} open={!!lineId} onCancel={()=>setLineId(undefined)} onOk={async()=>{try{const v=await lineForm.validateFields();const l:PresalesCostLine={...v,id:lineId==='new'?`CL-${Date.now()}`:lineId!,quotationExpiry:v.quotationExpiry?.format('YYYY-MM-DD'),unitPrice:v.subjectId==='SUB-01'?laborDayRate(v.laborUserId):v.unitPrice,baselineVersion:v.subjectId==='SUB-01'?currentRate(v.laborUserId).versionId:undefined,risk:v.risk??''};setLines(prev=>lineId==='new'?[...prev,l]:prev.map(x=>x.id===lineId?l:x));setLineId(undefined);}catch(e){if(e instanceof Error)message.error(e.message);}}}><Form form={lineForm} layout="vertical"><Row gutter={16}><Col span={12}><Form.Item name="subjectId" label="统一成本科目" rules={[{required:true}]}><Select options={subjects.map(s=>({value:s.id,label:s.name}))}/></Form.Item></Col><Col span={12}><Form.Item name="name" label="测算项名称" rules={[{required:true,whitespace:true}]}><Input/></Form.Item></Col><Col span={24}><Form.Item name="scope" label="关联方案范围 / 外包边界" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={2}/></Form.Item></Col><Col span={8}><Form.Item name="quantity" label={subject==='SUB-01'?'投入人天':'数量'} rules={[{required:true,type:'number',min:0.001}]}><InputNumber min={0.001}/></Form.Item></Col><Col span={8}><Form.Item name="unit" label="单位" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={8}>{subject==='SUB-01'?<Form.Item label="基准单价（万元/人天）">{showLaborRate?<InputNumber disabled value={person?laborDayRate(person):0}/>:<span>已隐藏</span>}</Form.Item>:<Form.Item name="unitPrice" label="单价（万元）" rules={[{required:true,type:'number',min:0}]}><InputNumber min={0} precision={6}/></Form.Item>}</Col>
 {subject==='SUB-01'&&<><Col span={12}><Form.Item name="laborUserId" label="人员 / 成本岗位基准" rules={[{required:true}]}><Select options={mockUsers.map(u=>({value:u.id,label:showLaborRate?`${u.name} · ${laborDayRate(u.id)} 万/人天`:`${u.name} · 单价已隐藏`}))}/></Form.Item></Col><Col span={12}><Form.Item name="laborGrade" label="角色 / 职级" rules={[{required:true}]}><Input placeholder="例如：高级架构师 / P7"/></Form.Item></Col></>}
 {subject==='SUB-03'&&<><Col span={8}><Form.Item name="supplier" label="询价供应商" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={8}><Form.Item name="quotationSource" label="询价来源 / 编号" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={8}><Form.Item name="quotationExpiry" label="报价有效期" rules={[{required:true}]}><DatePicker/></Form.Item></Col></>}
 <Col span={12}><Form.Item name="taxRate" label="税率（%）" rules={[{required:true,type:'number',min:0,max:100}]}><InputNumber min={0} max={100}/></Form.Item></Col><Col span={12}><Form.Item name="taxBasis" label="单价口径" rules={[{required:true}]}><Select options={['含税','不含税'].map(value=>({value,label:value}))}/></Form.Item></Col><Col span={24}><Form.Item name="basis" label="测算依据 / 工期假设" rules={[{required:true,whitespace:true}]}><Input.TextArea rows={2}/></Form.Item><Form.Item name="risk" label="风险成本说明"><Input.TextArea rows={2}/></Form.Item></Col></Row></Form></Modal>
 </>;
}
