import { expect, test, type Page } from '@playwright/test';
import { join } from 'node:path';
import { navigate, role } from './helpers';
import { artifactDir, capturePageEvidence, collectBrowserErrors, prepareArtifacts, writeBrowserReport } from './evidence';
type BusinessModule=typeof import('../src/mock/business');
const errors=new WeakMap<Page,string[]>();
test.beforeEach(({page})=>{prepareArtifacts();errors.set(page,collectBrowserErrors(page));});
test.afterEach(({page},info)=>{const consoleErrors=errors.get(page)??[];writeBrowserReport(info,{url:page.url(),consoleErrors});expect(consoleErrors).toEqual([]);});
async function changeRole(page:Page,name:string){const close=page.locator('.ant-drawer:visible .ant-drawer-close');if(await close.count()){await close.click();await expect(page.locator('.ant-drawer-mask:visible')).toHaveCount(0);}await role(page,name);}
async function state(page:Page){return page.evaluate(async()=>{const path='/src/mock/business.ts';const b=await import(/* @vite-ignore */ path) as BusinessModule;return b.useBusinessStore.getState().data;});}
async function overlayShots(page:Page,name:string){await expect(page.locator('.ant-message-notice')).toHaveCount(0,{timeout:6000});for(const width of [1440,1280]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:join(artifactDir,`${name}-${width}.png`),fullPage:true});}await page.setViewportSize({width:1440,height:900});}
async function documentAction(page:Page,name:string,note:string,file?:string,success=true){await page.locator('.ant-drawer:visible').getByRole('button',{name,exact:true}).click();const dialog=page.getByRole('dialog',{name,exact:true});if(file)await dialog.getByLabel('模拟文件名',{exact:true}).fill(file);await dialog.getByLabel('交付物办理说明',{exact:true}).fill(note);await dialog.getByRole('button',{name:/确\s*定/}).click();if(success)await expect(dialog).toBeHidden();return dialog;}
async function quality(page:Page,passed:boolean){await navigate(page,'/projects/P-001/deliverables?tab=quality');await expect(page.getByRole('heading',{name:'质量目标及检查标准',exact:true})).toBeVisible();await page.getByRole('button',{name:'登记质量检查',exact:true}).click();const dialog=page.getByRole('dialog',{name:'登记质量检查',exact:true});if(!passed){await dialog.locator('.ant-select[aria-label="质量检查结论"] .ant-select-selector').click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({hasText:'不合格，形成整改问题'}).click();}await dialog.getByLabel('交付物办理说明',{exact:true}).fill(passed?'整改完成，复查通过':'缺少安全扫描报告');await dialog.getByRole('button',{name:/确\s*定/}).click();return dialog;}

test('报告 UI：无进展草稿提交、周报快照及独立来源',async({page})=>{
 test.setTimeout(120_000);await page.goto('/projects/P-001/daily-reports');await changeRole(page,'项目经理');await navigate(page,'/projects/P-001/daily-reports');const before=await state(page);const linked=[...before.issues,...before.risks].filter(r=>r.projectId==='P-001').slice(0,2).map(r=>r.id);expect(linked).toHaveLength(2);
 await page.getByRole('button',{name:'填报今日日报',exact:true}).click();let dialog=page.getByRole('dialog',{name:'2026-09-09 日报填报',exact:true});await dialog.getByRole('checkbox',{name:'当天有进展',exact:true}).uncheck();await dialog.getByLabel('报告下一步',{exact:true}).fill('确认下次客户联调时间');await dialog.getByRole('button',{name:'确认提交日报',exact:true}).click();await expect(dialog).toBeVisible();
 await dialog.getByLabel('无进展原因',{exact:true}).fill('等待客户确认联调窗口');await dialog.getByLabel('报告协调事项',{exact:true}).fill('请客户接口负责人协调');const association=dialog.locator('.ant-select[aria-label="日报关联问题风险"]');await association.locator('.ant-select-selector').click();for(const id of linked){const option=page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({hasText:id});if(await option.getAttribute('aria-selected')!=='true')await option.click();}await association.getByRole('combobox').press('Escape');await expect(association.locator('.ant-select-selection-item')).toHaveCount(2);await overlayShots(page,'UI-HS03-form');await dialog.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(dialog).toBeHidden();
 await page.getByRole('button',{name:'继续今日日报',exact:true}).click();dialog=page.getByRole('dialog',{name:'2026-09-09 日报填报',exact:true});await expect(dialog.getByLabel('无进展原因',{exact:true})).toHaveValue('等待客户确认联调窗口');const restored=dialog.locator('.ant-select[aria-label="日报关联问题风险"]');await expect(restored.locator('.ant-select-selection-item')).toHaveCount(2);for(const id of linked)await expect(restored).toContainText(id);await dialog.getByRole('button',{name:'确认提交日报',exact:true}).click();await expect(dialog).toBeHidden();await expect(page.getByRole('button',{name:'今日日报已提交',exact:true})).toBeDisabled();
 const after=await state(page);expect(after.dailyReports.find(r=>r.projectId==='P-001'&&r.date==='2026-09-09')?.linkedIds).toEqual(linked);expect(after.tasks).toEqual(before.tasks);expect(after.issues).toEqual(before.issues);expect(after.dailyReports.filter(r=>r.projectId==='P-001'&&r.date==='2026-09-09')).toHaveLength(1);await capturePageEvidence(page,'UI-HS03');
 await page.getByRole('button',{name:'查看项目周报',exact:true}).click();await page.getByRole('button',{name:'生成本周草稿',exact:true}).click();const weekly=(await state(page)).weeklyReports.find(r=>r.projectId==='P-001'&&r.weekStart==='2026-09-07')!;const snapshot=weekly.snapshot;expect(snapshot?.dailyIds).toContain(after.dailyReports.find(r=>r.projectId==='P-001'&&r.date==='2026-09-09')!.id);
 await page.locator('.ant-drawer:visible').getByRole('button',{name:'补充并上报周报',exact:true}).click();dialog=page.getByRole('dialog',{name:'补充本周报告',exact:true});await dialog.getByLabel('报告进展',{exact:true}).fill('本周完成联调准备');await dialog.getByLabel('报告下一步',{exact:true}).fill('下周开展客户验证');await dialog.getByRole('button',{name:'确认模拟上报',exact:true}).click();await expect(dialog).toBeHidden();await expect(page.locator('.ant-drawer:visible')).toContainText('已上报');await overlayShots(page,'UI-HS04-snapshot');const sourceId=snapshot!.issueIds[0];expect(sourceId).toBeTruthy();await page.locator('.ant-drawer:visible').getByRole('button',{name:sourceId,exact:true}).click();await expect(page).toHaveURL(`/issues-risks/${sourceId}`);await navigate(page,`/projects/P-001/weekly-reports?report=${weekly.id}`);await expect(page.locator('.ant-drawer:visible')).toContainText(weekly.id);await page.locator('.ant-drawer:visible .ant-drawer-close').click();await capturePageEvidence(page,'UI-HS04');
 // Mutate execution through its existing action; the report remains frozen.
 await page.evaluate(async()=>{const path='/src/mock/business.ts';const b=await import(/* @vite-ignore */ path) as BusinessModule;const data=b.useBusinessStore.getState().data;const task=data.tasks.find(t=>t.projectId==='P-001'&&t.progress===0)!;b.useBusinessStore.setState({data:b.transition(data,{type:'update-task',id:task.id,progress:50,actualStartDate:'2026-09-08',note:'报告提交后新增执行事实'},{id:'U-001',name:'张建国',role:'project-manager'})});});expect((await state(page)).weeklyReports.find(r=>r.id===weekly.id)?.snapshot).toEqual(snapshot);
});

test('交付 UI：质量整改、文件退回新版本与里程碑门禁',async({page})=>{
 test.setTimeout(180_000);await page.goto('/projects/P-001/daily-reports');await changeRole(page,'项目经理');const initial=await state(page);const milestone=initial.milestones.find(m=>m.projectId==='P-001'&&m.status!=='已达成')!;const material=initial.materials.find(m=>m.projectId==='P-001'&&milestone.requiredDeliverables.includes(m.name))!;
 await navigate(page,'/projects/P-001/daily-reports');await page.locator(`tr[data-row-key="${milestone.id}"]`).getByRole('button',{name:'登记实际达成',exact:true}).click();await page.getByRole('dialog',{name:/^登记里程碑实际达成/}).getByLabel('里程碑达成说明',{exact:true}).fill('核对必交材料');await page.getByRole('dialog',{name:/^登记里程碑实际达成/}).getByRole('button',{name:/确\s*定/}).click();await expect(page.getByRole('dialog',{name:/^登记里程碑实际达成/})).toBeVisible();await page.getByRole('dialog',{name:/^登记里程碑实际达成/}).getByRole('button',{name:/取\s*消/}).click();
 await navigate(page,`/projects/P-001/deliverables?document=${material.id}`);await expect(page.locator('.ant-drawer:visible')).toContainText(material.name);await documentAction(page,'登记文件新版本','首版材料','首版报告.pdf');await documentAction(page,'提交当前版本审核','申请审核',undefined,false);await expect(page.getByRole('dialog',{name:'提交当前版本审核',exact:true})).toBeVisible();await page.getByRole('dialog',{name:'提交当前版本审核',exact:true}).getByRole('button',{name:/取\s*消/}).click();await page.locator('.ant-drawer:visible .ant-drawer-close').click();
 await quality(page,false);await expect(page.getByRole('dialog',{name:'登记质量检查',exact:true})).toBeHidden();const issueId=(await state(page)).qualityPlans['P-001'].checks.at(-1)!.issueId!;
 await quality(page,true);await expect(page.getByRole('dialog',{name:'登记质量检查',exact:true})).toBeVisible();await page.getByRole('dialog',{name:'登记质量检查',exact:true}).getByRole('button',{name:/取\s*消/}).click();
 await navigate(page,`/issues-risks/${issueId}`);for(const name of ['提交解决结果','最终确认关闭']){await page.getByRole('button',{name,exact:true}).click();const dialog=page.getByRole('dialog',{name,exact:true});await dialog.getByLabel('处理说明',{exact:true}).fill('报告已补齐并由主PM复核');await dialog.getByRole('button',{name:/确\s*定/}).click();await expect(dialog).toBeHidden();}
 await quality(page,true);await expect(page.getByRole('dialog',{name:'登记质量检查',exact:true})).toBeHidden();await capturePageEvidence(page,'UI-HS17-quality');
 await navigate(page,`/projects/P-001/deliverables?document=${material.id}`);await documentAction(page,'提交当前版本审核','质量已通过');await changeRole(page,'PMO负责人');await navigate(page,`/projects/P-001/deliverables?document=${material.id}`);await documentAction(page,'退回补充','补充测试结论');
 await changeRole(page,'项目经理');await navigate(page,`/projects/P-001/deliverables?document=${material.id}`);await documentAction(page,'登记文件新版本','完成整改','修订报告.pdf');await documentAction(page,'提交当前版本审核','重新送审');await changeRole(page,'PMO负责人');await navigate(page,`/projects/P-001/deliverables?document=${material.id}`);await documentAction(page,'审核通过','第二版符合要求');expect((await state(page)).materials.find(m=>m.id===material.id)?.versions?.map(v=>v.status)).toEqual(['驳回','通过']);await overlayShots(page,'UI-HS17-versions');await page.locator('.ant-drawer:visible .ant-drawer-close').click();await capturePageEvidence(page,'UI-HS17');
 // Other required documents use the same already-exercised domain sequence.
 await page.evaluate(async({projectId,except})=>{const path='/src/mock/business.ts';const b=await import(/* @vite-ignore */ path) as BusinessModule;let data=b.useBusinessStore.getState().data;for(const m of data.materials.filter(m=>m.projectId===projectId&&m.id!==except&&m.status!=='通过'))for(const operation of ['upload','submit','approve'] as const)data=b.transition(data,{type:'document-action',id:m.id,operation,filename:'其他必交材料.pdf',note:'完成其余材料前置'},operation==='approve'?{id:'U-002',name:'李主任',role:'pmo'}:{id:'U-001',name:'张建国',role:'project-manager'});b.useBusinessStore.setState({data});},{projectId:'P-001',except:material.id});
 await changeRole(page,'项目经理');await navigate(page,'/projects/P-001/daily-reports');await page.locator(`tr[data-row-key="${milestone.id}"]`).getByRole('button',{name:'登记实际达成',exact:true}).click();await page.getByRole('dialog',{name:/^登记里程碑实际达成/}).getByLabel('里程碑达成说明',{exact:true}).fill('必交材料全部通过，登记实际达成');await page.getByRole('dialog',{name:/^登记里程碑实际达成/}).getByRole('button',{name:/确\s*定/}).click();await expect(page.getByRole('dialog',{name:/^登记里程碑实际达成/})).toBeHidden();expect((await state(page)).milestones.find(m=>m.id===milestone.id)).toMatchObject({status:'已达成',plannedDate:milestone.plannedDate});
});

test('报告交付 UI：只读、错误深链与收尾归档',async({page})=>{
 test.setTimeout(90_000);await page.goto('/projects/P-001/daily-reports');await changeRole(page,'财务专员');await navigate(page,'/projects/P-001/daily-reports');await expect(page.getByRole('button',{name:'填报今日日报',exact:true})).toBeDisabled();await navigate(page,'/projects/P-001/daily-reports?report=NOT-FOUND');await expect(page.locator('.ant-drawer:visible')).toContainText('报告不存在');await page.locator('.ant-drawer:visible .ant-drawer-close').click();await navigate(page,'/projects/P-001/deliverables?document=NOT-FOUND');await expect(page.locator('.ant-drawer:visible')).toContainText('文档不存在');await page.locator('.ant-drawer:visible .ant-drawer-close').click();
 await changeRole(page,'PMO负责人');const data=await state(page);const material=data.materials.find(m=>m.projectId==='P-006'&&m.status==='通过'&&!m.archived)!;expect(material).toBeTruthy();await navigate(page,`/projects/P-006/deliverables?document=${material.id}`);await expect(page.locator('.ant-drawer:visible')).toContainText(material.name);await documentAction(page,'确认归档','收尾材料确认归档');await expect(page.locator('.ant-drawer:visible')).toContainText('已归档，不可修改');expect((await state(page)).materials.find(m=>m.id===material.id)?.versions).toEqual(material.versions);await expect(page.locator('.ant-drawer:visible').getByRole('button',{name:'登记文件新版本',exact:true})).toBeDisabled();await overlayShots(page,'UI-HS17-archived');
});
