import { useState } from 'react';
import { App, Button, Card, Col, Form, Input, InputNumber, Modal, Row, Select, Space, Table, Tabs } from 'antd';
import { useNavigate } from 'react-router-dom';
import { StateView } from '@/components/common/StateView';
import { usePlanning } from './usePlanning';
import { PlanningHeader } from './PlanningLayout';
import { BudgetSummary, BudgetComparisonTable } from './BudgetSummary';
import { BUDGET_SUBJECTS, getBudgetDraft, lineAmount, toBudgetVersion } from '@/mock/budget-drafts';
import { projectEstimate } from '@/mock/versions';
import { hourlyRate } from '@/mock/labor';
import type { BudgetDraft, BudgetLine } from '@/models/budget';
export function BudgetEditorPage(){
 const c=usePlanning(),{message,modal}=App.useApp(),navigate=useNavigate();const [local,setLocal]=useState<BudgetDraft>();const [editing,setEditing]=useState<string>();const [form]=Form.useForm<BudgetLine>();
 if(!c.project||!c.plan)return <StateView type="404"/>;if(!c.allowed||!['project-manager','pmo','finance','executive','admin'].includes(c.actor.role))return <StateView type="403"/>;const p=c.project,estimate=projectEstimate(p,c.data.estimates);if(!estimate)return <StateView type="empty" title="缺少项目绑定冻结概算"/>;
 const draft=local?.projectId===p.id?local:getBudgetDraft(c.data,p.id);const budget=toBudgetVersion(draft,c.actor);const canEdit=c.actor.role==='project-manager'&&c.actor.id===p.pmId&&!c.data.approvals.some(a=>a.projectId===p.id&&(a.status==='待审批'||a.kind==='budget'&&a.status==='通过'&&!a.baselineConfirmedAt));
 const save=()=>{try{c.dispatch({type:'save-budget-draft',draft,expectedRevision:c.data.budgetDrafts[p.id]?.revision??0},c.actor);setLocal(undefined);message.success('预算草稿已保存');return true;}catch(e){message.error((e as Error).message);return false;}};
 const open=(line?:BudgetLine)=>{form.setFieldsValue(line??{id:`LINE-${p.id}-${draft.revision}-${draft.lines.length+1}`,name:'',kind:'procurement',subjectId:'SUB-03',amount:0,plannedDays:1,travelDays:0,userId:p.pmId,grade:'项目岗位基准',taskId:c.plan?.tasks[0]?.id,stage:'开发实施',sourceEstimateItemId:'SUB-03',justification:'',department:p.departmentName,supplyMode:'采购'});setEditing(line?.id??'new');};
 const columns=[{title:'预算事项',dataIndex:'name',width:170},{title:'WBS / 来源概算',width:170,render:(_:unknown,l:BudgetLine)=><>{c.plan?.tasks.find(t=>t.id===l.taskId)?.name??'独立费用'}<div>{l.sourceEstimateItemId?`${estimate.version} / ${l.sourceEstimateItemId}`:'新增测算项'}</div></>},{title:'测算依据',width:200,render:(_:unknown,l:BudgetLine)=>l.kind==='labor'?`${l.plannedDays}人天 × 8小时 × ${hourlyRate(l.userId??'')}元/小时`:`${l.supplyMode} · ${l.stage}`},{title:'预算（万元）',width:120,render:(_:unknown,l:BudgetLine)=>lineAmount(l).toFixed(2)},{title:'范围与调整说明',dataIndex:'justification',width:220},{title:'操作',width:140,render:(_:unknown,l:BudgetLine)=><Space><Button size="small" disabled={!canEdit} onClick={()=>open(l)}>编辑</Button><Button size="small" danger disabled={!canEdit} onClick={()=>setLocal({...draft,lines:draft.lines.filter(x=>x.id!==l.id)})}>删除</Button></Space>}];
 return <><PlanningHeader title="YS-09 项目预算编制" context={c}/><BudgetSummary budget={budget} estimate={estimate} income={p.revenueAmount??p.contractAmount}/><Card size="small" title={`预算草稿 R${draft.revision} · 引用概算 ${estimate.version}`} extra={<Space><Button onClick={()=>{setLocal(undefined);navigate(`/projects/${p.id}/plan-review`);}}>取消 / 返回计划</Button><Button disabled={!canEdit} onClick={save}>保存草稿</Button><Button type="primary" disabled={!canEdit} onClick={()=>modal.confirm({title:'确认保存并提交预算审批',content:`预算${budget.totalAmount.toFixed(2)}万元；提交后绑定当前概算、计划、资源和预算明细版本。`,onOk:()=>{if(!save())return;try{c.dispatch({type:'submit-budget-draft',projectId:p.id},c.actor);navigate(`/projects/${p.id}/budget/review`);}catch(e){message.error((e as Error).message);}}})}>提交审批</Button></Space>}><Tabs items={[{key:'base',label:'项目与计划',children:<><p>客户：{p.customerName} · 项目收入：{p.revenueAmount??p.contractAmount}万元</p><p>范围：{c.plan.scope}</p><p>WBS {c.plan.tasks.length}项 / 里程碑 {c.plan.milestones.length}项 / 资源 {c.plan.resources.length}人</p><Button onClick={()=>navigate(`/projects/${p.id}/wbs`)}>核对WBS与资源</Button></>},...([['labor','交付人力'],['procurement','建设采购'],['expense','期间费用'],['third-party','第三方费用'],['outsource','外包预算'],['reserve','准备金']] as const).map(([kind,label])=>({key:kind,label,children:<><Button disabled={!canEdit} onClick={()=>{open();form.setFieldsValue({kind,subjectId:kind==='labor'?'SUB-01':kind==='outsource'?'SUB-02':kind==='procurement'?'SUB-03':kind==='reserve'?'SUB-05':'SUB-04-4'});}}>新增{label}</Button><Table rowKey="id" size="small" dataSource={draft.lines.filter(l=>l.kind===kind)} columns={columns} pagination={false} scroll={{x:1120}}/></>})),{key:'summary',label:'预算汇总与对比',children:<BudgetComparisonTable budget={budget} estimate={estimate}/>} ]}/><Row gutter={16} style={{marginTop:20}}>{[['reason','超概算原因'],['mitigation','应对措施与毛利影响'],['responsibility','责任说明']] .map(([key,label])=><Col span={8} key={key}><label>{label}<Input.TextArea aria-label={label} disabled={!canEdit} rows={3} value={draft[key as 'reason']} onChange={e=>setLocal({...draft,[key]:e.target.value})}/></label></Col>)}</Row></Card>
 <Modal width={800} title="预算明细测算" open={!!editing} onCancel={()=>setEditing(undefined)} onOk={()=>form.validateFields().then(values=>{const line={...form.getFieldsValue(true),...values};setLocal({...draft,lines:editing==='new'?[...draft.lines,line]:draft.lines.map(l=>l.id===editing?line:l)});setEditing(undefined);}).catch(()=>{})}><Form form={form} layout="vertical"><Row gutter={16}><Col span={12}><Form.Item name="name" label="预算事项" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="kind" label="成本类型"><Select options={['labor','procurement','outsource','expense','third-party','reserve'].map((value,i)=>({value,label:['人力','采购','外包','期间费用','第三方费用','准备金'][i]}))}/></Form.Item></Col><Col span={12}><Form.Item name="subjectId" label="财务统一科目"><Select options={BUDGET_SUBJECTS.map(s=>({value:s.id,label:s.name}))}/></Form.Item></Col><Col span={12}><Form.Item name="taskId" label="关联WBS范围"><Select options={c.plan.tasks.map(t=>({value:t.id,label:t.name}))}/></Form.Item></Col><Col span={12}><Form.Item name="userId" label="人力成员（按成本基准计价）"><Select options={c.plan.resources.filter(r=>r.active).map(r=>({value:r.userId,label:`${r.name} · ${hourlyRate(r.userId)}元/小时`}))}/></Form.Item></Col><Col span={12}><Form.Item name="plannedDays" label="人力计划人天"><InputNumber min={0} precision={2}/></Form.Item></Col><Col span={12}><Form.Item name="travelDays" label="出差天数"><InputNumber min={0}/></Form.Item></Col><Col span={12}><Form.Item name="amount" label="非人力金额（万元，人力按基准自动计算）"><InputNumber min={0} precision={2}/></Form.Item></Col><Col span={12}><Form.Item name="stage" label="计划发生阶段"><Select options={['方案确认','开发实施','系统联调','内部初验','客户终验'].map(value=>({value,label:value}))}/></Form.Item></Col><Col span={12}><Form.Item name="supplyMode" label="供应方式"><Input/></Form.Item></Col><Col span={12}><Form.Item name="department" label="责任部门"><Input/></Form.Item></Col><Col span={12}><Form.Item name="sourceEstimateItemId" label="来源概算科目"><Select allowClear options={estimate.items.map(i=>({value:i.subjectId,label:i.subjectName}))}/></Form.Item></Col><Col span={24}><Form.Item name="justification" label="交付范围 / 调整原因"><Input.TextArea/></Form.Item></Col></Row></Form></Modal></>;
}
