import { useState } from 'react';
import { App, Button, Card, Col, Form, Input, InputNumber, Modal, Row, Select, Space, Table, Tag, Timeline } from 'antd';
import { mockUsers } from '@/mock';
import { usePlanning } from './usePlanning';
import { PlanningHeader } from './PlanningLayout';
import { StateView } from '@/components/common/StateView';
import type { TeamResource } from '@/models/budget';
export function TeamPage(){
 const c=usePlanning(),{message}=App.useApp();const [form]=Form.useForm<TeamResource>();const [memberOpen,setMemberOpen]=useState(false);const [appoint,setAppoint]=useState(false);const [candidate,setCandidate]=useState('U-001');const [reason,setReason]=useState('');const [exit,setExit]=useState<string>();const [exitDate,setExitDate]=useState('2026-09-09');const [response,setResponse]=useState<boolean>();
 if(!c.project)return <StateView type="404"/>;if(!c.allowed)return <StateView type="403"/>;const p=c.project,team=c.data.projectTeams[p.id];if(!team)return <StateView type="empty" title="尚未建立团队关系"/>;const pm=c.actor.role==='project-manager'&&c.actor.id===p.pmId;const pending=team.appointments.find(a=>a.status==='待接受');
 const run=(a:Parameters<typeof c.dispatch>[0])=>{try{c.dispatch(a,c.actor);message.success('团队关系已更新，历史执行记录保留');return true;}catch(e){message.error((e as Error).message);return false;}};
 const edit=(m?:TeamResource)=>{form.setFieldsValue(m??{userId:'U-005',name:'',role:'技术经理',departmentId:'',active:true,startDate:p.plannedStartDate,endDate:p.plannedEndDate,allocation:100,plannedHours:160,keyPosition:false});setReason('');setMemberOpen(true);};
 return <><PlanningHeader title="YS-05 项目团队" context={c}/><Row gutter={16}><Col span={17}><Card size="small" title={`唯一主PM：${p.pmName}`} extra={<Space><Button disabled={c.actor.role!=='pmo'||!!pending} onClick={()=>{setReason('');setAppoint(true);}}>推荐与任命主PM</Button><Button type="primary" disabled={!pm} onClick={()=>edit()}>加入成员</Button></Space>}><p>有效成员 {team.members.filter(m=>m.active).length} 人 · PM接受后切换主责任；退出仅收回当前关系，不回写历史任务、工时或成本。</p><Table rowKey="userId" size="small" dataSource={team.members} pagination={false} scroll={{x:950}} columns={[{title:'成员 / 人才库ID',render:(_,m)=><>{m.name}<div>{m.userId}</div></>},{title:'项目角色',dataIndex:'role'},{title:'参与周期',render:(_,m)=>`${m.startDate} ~ ${m.endDate}`},{title:'资源投入',render:(_,m)=>`${m.allocation}% / ${m.plannedHours}小时`},{title:'权限关系',render:(_,m)=><Tag color={m.active?'green':'default'}>{m.active?'项目成员可见':'已退出，当前权限收回'}</Tag>},{title:'操作',render:(_,m)=><Space><Button size="small" disabled={!pm} onClick={()=>edit(m)}>编辑</Button><Button size="small" danger disabled={!pm||!m.active||m.userId===p.pmId} onClick={()=>{setExit(m.userId);setReason('');}}>退出</Button></Space>} ]}/></Card><Card size="small" title="任命与接收记录" style={{marginTop:16}}><Table rowKey="id" size="small" pagination={false} dataSource={team.appointments} columns={[{title:'候选PM',dataIndex:'name'},{title:'任命日期',dataIndex:'nominatedAt'},{title:'任命人',dataIndex:'nominatedBy'},{title:'接收状态',dataIndex:'status'},{title:'说明',dataIndex:'opinion'},{title:'操作',render:(_,a)=>a.status==='待接受'?<Space><Button disabled={c.actor.id!==a.userId} onClick={()=>{setResponse(true);setReason('');}}>接受</Button><Button danger disabled={c.actor.id!==a.userId} onClick={()=>{setResponse(false);setReason('');}}>拒绝</Button></Space>:'已留存'}]}/></Card></Col><Col span={7}><Card title="人员变更记录" size="small"><Timeline items={team.history.map((h,i)=>({key:i,children:<>{h.date} · {h.actor}<p>{h.description}</p></>}))}/>{!team.history.length&&<p>暂无新增人员变更</p>}</Card><Card size="small" title="推荐依据 · 演示" style={{marginTop:16}}><p>当前项目：{p.type} / {p.level}</p><p>优先推荐当前主PM及参与技术人员；候选来源统一人才库，推荐不替代PMO任命。</p></Card></Col></Row>
 <Modal title="维护团队与资源" open={memberOpen} onCancel={()=>setMemberOpen(false)} onOk={()=>form.validateFields().then(m=>{if(run({type:'save-team-member',projectId:p.id,member:{...form.getFieldsValue(true),...m},reason}))setMemberOpen(false);}).catch(()=>{})}><Form form={form} layout="vertical"><Form.Item name="userId" label="人才库成员" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={mockUsers.map(u=>({value:u.id,label:`${u.name} · ${u.role} · ${u.id}`}))}/></Form.Item><Form.Item name="role" label="项目角色" rules={[{required:true}]}><Select options={['项目经理','技术经理','交付成员','方案协同','商务协同','财务协同'].map(value=>({value,label:value}))}/></Form.Item><Space><Form.Item name="startDate" label="参与开始"><Input type="date"/></Form.Item><Form.Item name="endDate" label="参与结束"><Input type="date"/></Form.Item></Space><Space><Form.Item name="allocation" label="投入比例%"><InputNumber min={1} max={100}/></Form.Item><Form.Item name="plannedHours" label="计划工时"><InputNumber min={1}/></Form.Item></Space></Form><Input.TextArea aria-label="团队变更原因" placeholder="变更原因（必填）" value={reason} onChange={e=>setReason(e.target.value)}/></Modal>
 <Modal title="PMO主PM任命" open={appoint} onCancel={()=>setAppoint(false)} onOk={()=>{if(run({type:'nominate-pm',projectId:p.id,userId:candidate,reason}))setAppoint(false);}}><Select style={{width:'100%'}} value={candidate} onChange={setCandidate} showSearch optionFilterProp="label" options={mockUsers.map(u=>({value:u.id,label:`${u.name} / ${u.role}`}))}/><Input.TextArea style={{marginTop:12}} aria-label="任命原因" placeholder="任命依据与交接安排" value={reason} onChange={e=>setReason(e.target.value)}/></Modal>
 <Modal title="确认人员退出" open={!!exit} onCancel={()=>setExit(undefined)} onOk={()=>{if(run({type:'exit-team-member',projectId:p.id,userId:exit!,date:exitDate,reason}))setExit(undefined);}}><Input type="date" value={exitDate} onChange={e=>setExitDate(e.target.value)}/><Input.TextArea placeholder="退出原因" value={reason} onChange={e=>setReason(e.target.value)}/></Modal><Modal title={response?'接受主PM任命':'拒绝主PM任命'} open={response!==undefined} onCancel={()=>setResponse(undefined)} onOk={()=>{if(run({type:'respond-pm',projectId:p.id,accept:response!,opinion:reason}))setResponse(undefined);}}><Input.TextArea aria-label="任命接收说明" value={reason} onChange={e=>setReason(e.target.value)}/></Modal></>;
}
