import { useState } from 'react';
import { Alert, App, Button, Card, Col, Form, Input, InputNumber, Modal, Popconfirm, Row, Select, Space, Table, Tag } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { StateView } from '@/components/common/StateView';
import { PlanningHeader } from './PlanningLayout';
import { usePlanning } from './usePlanning';
import type { WbsTask } from '@/models/types';
import { validatePlanning } from '@/mock/budget';
interface TreeTask extends WbsTask { children?:TreeTask[] }
export function WbsPlanningPage(){
 const c=usePlanning();const {message}=App.useApp();const [form]=Form.useForm<WbsTask>();const [editing,setEditing]=useState<string>();const [importOpen,setImportOpen]=useState(false);const [importText,setImportText]=useState('');const [scope,setScope]=useState<string>();
 if(!c.project||!c.plan)return <StateView type="404"/>;if(!c.allowed)return <StateView type="403"/>;
 const p=c.project,plan=c.plan,tasks=plan.tasks;
 const save=(next:typeof plan)=>{try{c.dispatch({type:'save-planning',projectId:p.id,plan:next,expectedRevision:c.draft!.revision},c.actor);message.success('计划草稿已保存，版本已更新');return true;}catch(e){message.error((e as Error).message);return false;}};
 const open=(task?:WbsTask)=>{setEditing(task?.id??'new');form.setFieldsValue(task??{id:`TASK-${p.id}-${c.draft?.revision??1}-${tasks.length+1}`,projectId:p.id,taskCode:`${tasks.length+1}`,name:'',ownerId:p.pmId,ownerName:p.pmName,plannedDays:1,plannedHours:8,startDate:p.plannedStartDate,endDate:p.plannedStartDate,progress:0,isMilestone:false,status:'未开始',predecessorIds:[],completionCondition:'',parentId:undefined,milestoneId:undefined,description:''});};
 const tree=(parentId?:string):TreeTask[]=>tasks.filter(t=>t.parentId===parentId).map(t=>({...t,children:tasks.some(x=>x.parentId===t.id)?tree(t.id):undefined}));
 const duration=Math.max(86400000,Date.parse(p.plannedEndDate)-Date.parse(p.plannedStartDate));
 const columns:ColumnsType<TreeTask>=[{title:'项目 / WBS工作包',dataIndex:'name',width:260,fixed:'left',render:(_,t)=><><b>{t.taskCode} {t.name}</b><div style={{fontSize:12,color:'#777'}}>{t.completionCondition??'历史计划未记录完成条件'}</div></>},{title:'责任人',dataIndex:'ownerName',width:95},{title:'计划日期',width:185,render:(_,t)=><>{t.startDate}<br/>{t.endDate}</>},{title:'人天 / 工时',width:100,render:(_,t)=><>{t.plannedDays} 天<br/>{t.plannedHours??'—'} 小时</>},{title:'前置任务',width:130,render:(_,t)=>(t.predecessorIds??[]).map(id=>tasks.find(t=>t.id===id)?.taskCode).join('、')||'无'},{title:'计划甘特',width:260,render:(_,t)=><div title={`${t.startDate} 至 ${t.endDate}`} style={{height:18,width:230,background:'#f0f5ff',position:'relative',overflow:'hidden'}}><div style={{position:'absolute',height:18,borderRadius:2,background:'#4096ff',left:`${Math.max(0,(Date.parse(t.startDate)-Date.parse(p.plannedStartDate))/duration*100)}%`,width:`${Math.max(2,(Date.parse(t.endDate)-Date.parse(t.startDate))/duration*100)}%`}}/></div>},{title:'里程碑',width:100,render:(_,t)=>plan.milestones.find(m=>m.id===t.milestoneId)?.name??'—'},{title:'操作',fixed:'right',width:150,render:(_,t)=><Space><Button size="small" disabled={!c.canEdit} onClick={()=>open(t)}>编辑</Button><Popconfirm title="删除此工作包？" onConfirm={()=>{if(t.isMilestone||tasks.some(x=>x.parentId===t.id||(x.predecessorIds??[]).includes(t.id))){message.error('含子任务、里程碑或被依赖的任务不可删除');return;}save({...plan,tasks:tasks.filter(x=>x.id!==t.id)});}}><Button size="small" danger disabled={!c.canEdit}>删除</Button></Popconfirm></Space>}];
 const imported:WbsTask[]=importText.trim()?importText.trim().split('\n').slice(1).map((line,i)=>{const [taskCode,name,parentCode,ownerId,startDate,endDate,hours,previous,completionCondition]=line.split('\t');const idFor=(code:string)=>`IMPORT-${p.id}-${code}`;return {id:idFor(taskCode||String(i)),projectId:p.id,taskCode:taskCode??'',name:name??'',parentId:parentCode?idFor(parentCode):undefined,ownerId:ownerId??'',ownerName:plan.resources.find(r=>r.userId===ownerId)?.name??'',startDate:startDate??'',endDate:endDate??'',plannedHours:Number(hours),plannedDays:Math.max(1,(Date.parse(endDate)-Date.parse(startDate))/86400000+1),predecessorIds:previous?previous.split(',').map(idFor):[],completionCondition:completionCondition??'',progress:0,isMilestone:false,status:'未开始'};}):[];
 const importErrors=validatePlanning({...plan,tasks:imported},p.id);
 return <><PlanningHeader title="YS-06 WBS计划编制" context={c}/><Card size="small" title="范围与工作分解" extra={<Tag>根节点：{p.name}</Tag>}><Space.Compact style={{width:'100%',marginBottom:16}}><Input aria-label="计划范围" value={scope??plan.scope} disabled={!c.canEdit} onChange={e=>setScope(e.target.value)}/><Button disabled={!c.canEdit} onClick={()=>{if(save({...plan,scope:scope??plan.scope}))setScope(undefined);}}>保存范围</Button></Space.Compact><Space wrap style={{marginBottom:16}}><Button type="primary" disabled={!c.canEdit} onClick={()=>open()}>新增工作包</Button><Button disabled={!c.canEdit} onClick={()=>setImportOpen(true)}>Excel模板导入</Button><Button onClick={()=>{const text=['编码\t名称\t责任人\t开始\t结束',...tasks.map(t=>`${t.taskCode}\t${t.name}\t${t.ownerName}\t${t.startDate}\t${t.endDate}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/tab-separated-values'}));a.download=`${p.id}-WBS.tsv`;a.click();URL.revokeObjectURL(a.href);}}>导出计划表</Button><span>{tasks.length} 个工作包 · 叶子任务计划 {tasks.filter(t=>!tasks.some(x=>x.parentId===t.id)).reduce((n,t)=>n+(t.plannedHours??0),0)} 小时</span></Space><Table<TreeTask> rowKey="id" size="small" dataSource={tree()} columns={columns} pagination={false} expandable={{defaultExpandAllRows:true}} scroll={{x:1380}}/></Card>
 <Modal title={editing==='new'?'新增工作包':'编辑工作包'} open={!!editing} width={780} onCancel={()=>setEditing(undefined)} onOk={()=>form.validateFields().then(values=>{const value={...form.getFieldsValue(true),...values,ownerName:plan.resources.find(r=>r.userId===values.ownerId)?.name??'',plannedDays:Math.max(1,(Date.parse(values.endDate)-Date.parse(values.startDate))/86400000+1)};if(save({...plan,tasks:editing==='new'?[...tasks,value]:tasks.map(t=>t.id===editing?value:t)}))setEditing(undefined);})}><Form form={form} layout="vertical"><Row gutter={16}><Col span={8}><Form.Item name="taskCode" label="WBS编码" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={16}><Form.Item name="name" label="任务名称" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="parentId" label="父任务（空为项目根节点）"><Select allowClear options={tasks.filter(t=>t.id!==editing).map(t=>({value:t.id,label:`${t.taskCode} ${t.name}`}))}/></Form.Item></Col><Col span={12}><Form.Item name="ownerId" label="有效团队责任人" rules={[{required:true}]}><Select options={plan.resources.filter(r=>r.active).map(r=>({value:r.userId,label:r.name}))}/></Form.Item></Col><Col span={12}><Form.Item name="startDate" label="计划开始" rules={[{required:true}]}><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="endDate" label="计划结束" rules={[{required:true}]}><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="plannedHours" label="计划工时（小时）" rules={[{required:true}]}><InputNumber min={1}/></Form.Item></Col><Col span={12}><Form.Item name="milestoneId" label="对应里程碑"><Select allowClear options={plan.milestones.map(m=>({value:m.id,label:m.name}))}/></Form.Item></Col><Col span={24}><Form.Item name="predecessorIds" label="前置任务"><Select mode="multiple" options={tasks.filter(t=>t.id!==editing).map(t=>({value:t.id,label:`${t.taskCode} ${t.name}`}))}/></Form.Item></Col><Col span={24}><Form.Item name="completionCondition" label="完成条件" rules={[{required:true}]}><Input.TextArea/></Form.Item><Form.Item name="description" label="说明"><Input.TextArea/></Form.Item></Col></Row></Form></Modal>
 <Modal title="Excel模板导入 · 本地模拟校验" open={importOpen} width={900} onCancel={()=>setImportOpen(false)} okText="校验通过，替换草稿任务" okButtonProps={{disabled:!imported.length||!!importErrors.length}} onOk={()=>{if(save({...plan,tasks:imported}))setImportOpen(false);}}><Alert type="info" message="将Excel模板含表头的9列复制到下方，制表符分隔。仅替换草稿任务，生效计划不受影响。"/><p>编码｜名称｜父编码｜责任人ID｜开始｜结束｜工时｜前置编码（英文逗号分隔）｜完成条件</p><Button onClick={()=>setImportText('编码\t名称\t父编码\t责任人ID\t开始\t结束\t工时\t前置编码\t完成条件\n1\t平台交付\t\tU-001\t2026-09-10\t2026-12-31\t160\t\t交付培训与验收资料')}>载入模板样例</Button><Input.TextArea aria-label="WBS导入内容" rows={7} value={importText} onChange={e=>setImportText(e.target.value)}/><Alert style={{marginTop:12}} type={importErrors.length?'warning':'success'} message={importErrors.length?`发现 ${importErrors.length} 项错误`:`${imported.length} 行校验通过`} description={importErrors.join('；')}/><Table size="small" rowKey={(_,i)=>String(i)} dataSource={imported} pagination={{pageSize:5}} columns={[{title:'编码',dataIndex:'taskCode'},{title:'任务',dataIndex:'name'},{title:'责任人',dataIndex:'ownerName'},{title:'开始',dataIndex:'startDate'},{title:'结束',dataIndex:'endDate'}]}/></Modal></>;
}
