import { useActionAccess } from '@/hooks/useActionAccess';
import {canViewInitiation} from '@/mock/initiation';
import {useState} from 'react';
import {Alert,App,Button,Card,Input,InputNumber,Select,Space,Table,Tag} from 'antd';
import {useNavigate,useParams} from 'react-router-dom';
import {useBusinessStore} from '@/mock/business';
import {useAppStore} from '@/store/useAppStore';
import {mockUsers} from '@/mock';
import {riskScore} from '@/mock/initiation';
import type {InitiationRisk} from '@/models/initiation';
import {StateView} from '@/components/common/StateView';
import {InitiationHeader,SourceSummary} from './InitiationShared';
export function InitiationRiskPage(){
 const {canDo}=useActionAccess();const {id}=useParams();const {data,dispatch}=useBusinessStore();const actor=useAppStore(s=>s.currentUser);const app=data.initiations.find(a=>a.id===id);const round=app?.rounds.at(-1);const [risks,setRisks]=useState<InitiationRisk[]>(structuredClone(round?.risks??[]));const [level,setLevel]=useState<'低'|'中'|'高'>(round?.riskLevel??riskScore(risks));const [explanation,setExplanation]=useState(round?.riskExplanation??'');const {message}=App.useApp();const go=useNavigate();if(!app)return <StateView type="404"/>;if(!canViewInitiation(data,app,actor))return <StateView type="403"/>;if(!round)return <><InitiationHeader app={app} title="综合风险报告"/><Alert message="请先提交立项申请"/></>;const editable=canDo('assess-initiation-risk',app.id)&&actor.role==='pmo'&&['待风险评估','待分级'].includes(round.status);const patch=(id:string,p:Partial<InitiationRisk>)=>setRisks(rows=>rows.map(r=>r.id===id?{...r,...p}:r));const save=()=>{try{if(!editable)throw new Error('当前策略不允许风险评估');dispatch({type:'assess-initiation-risk',id:app.id,risks,level,explanation},actor);message.success('风险报告已确认');go(`/initiation/${app.id}/decision`);}catch(e){message.error((e as Error).message);}};
 return <><InitiationHeader app={app} title="综合风险报告"/><SourceSummary source={round.source}/><Card title="风险矩阵与责任措施" style={{marginTop:16}} extra={<Button disabled={!editable} onClick={()=>setRisks([...risks,{id:`MANUAL-${risks.length+1}`,domain:'交付',description:'',sourceId:app.id,sourceRoute:`/initiation/apply?id=${app.id}`,probability:2,impact:3,mitigation:'',ownerId:''}])}>补充风险</Button>}><Alert showIcon message={`矩阵最高等级：${riskScore(risks)}；概率 × 影响：1–8 低、9–15 中、16–25 高。综合判断不可低于最高单项等级。`} style={{marginBottom:16}}/><div style={{display:'grid',gridTemplateColumns:'repeat(5, 1fr)',gap:4,marginBottom:16}}>{[5,4,3,2,1].flatMap(probability=>[1,2,3,4,5].map(impact=><div key={`${probability}-${impact}`} style={{background:probability*impact>=16?'#fff1f0':probability*impact>=9?'#fffbe6':'#f6ffed',padding:10,border:'1px solid #eee'}}><b>{probability} × {impact}</b><span style={{float:'right'}}>{risks.filter(r=>r.probability===probability&&r.impact===impact).length} 项</span></div>))}</div><Table rowKey="id" scroll={{x:1400}} pagination={false} dataSource={risks} columns={[{title:'领域',dataIndex:'domain',width:110,render:(v,r)=><Select disabled={!editable} value={v} onChange={domain=>patch(r.id,{domain})} options={['商务','技术','交付','财务','法务'].map(value=>({value,label:value}))}/>},{title:'风险及来源',width:260,render:(_,r)=><><Input.TextArea disabled={!editable} value={r.description} onChange={e=>patch(r.id,{description:e.target.value})}/><Button type="link" onClick={()=>go(r.sourceRoute)}>{r.sourceId}</Button></>},{title:'概率',width:90,render:(_,r)=><InputNumber disabled={!editable} min={1} max={5} value={r.probability} onChange={v=>patch(r.id,{probability:v??1})}/>},{title:'影响',width:90,render:(_,r)=><InputNumber disabled={!editable} min={1} max={5} value={r.impact} onChange={v=>patch(r.id,{impact:v??1})}/>},{title:'评分',width:70,render:(_,r)=><Tag color={r.probability*r.impact>=16?'red':'blue'}>{r.probability*r.impact}</Tag>},{title:'应对措施',width:300,render:(_,r)=><Input.TextArea disabled={!editable} value={r.mitigation} onChange={e=>patch(r.id,{mitigation:e.target.value})}/>},{title:'责任人',width:140,render:(_,r)=><Select style={{width:120}} disabled={!editable} value={r.ownerId||undefined} options={mockUsers.map(u=>({value:u.id,label:u.name}))} onChange={ownerId=>patch(r.id,{ownerId})}/>} ]}/><Space style={{marginTop:16}}><span>综合等级</span><Select disabled={!editable} value={level} onChange={setLevel} options={['低','中','高'].map(value=>({value,label:value}))}/></Space><p>综合判断与人工调整依据</p><Input.TextArea disabled={!editable} rows={3} value={explanation} onChange={e=>setExplanation(e.target.value)}/><Button style={{marginTop:16}} type="primary" disabled={!editable} onClick={save}>确认报告并进入项目分级</Button></Card></>;
}
