import { stageChecks, stageSnapshot } from '@/mock/stage';
import { useState } from 'react';
import { Alert, App, Button, Card, Descriptions, Input, InputNumber, Modal, Space, Table } from 'antd';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useBusinessStore } from '@/mock/business';
import { visibleProjects } from '@/mock/selectors';
import { useAppStore } from '@/store/useAppStore';
import { PageHeader } from '@/components/common/PageHeader';
import { StateView } from '@/components/common/StateView';

export function PlanRequestPage({ stageEntry = false }: { stageEntry?: boolean }) {
  const { id, requestId: routeRequestId } = useParams(); const [params] = useSearchParams(); const requestId = routeRequestId ?? params.get('request') ?? 'new'; const navigate = useNavigate(); const { message } = App.useApp();
  const { data, dispatch } = useBusinessStore(); const { currentRole, currentUser } = useAppStore();
  const [reason, setReason] = useState(params.get('reason') ?? ''); const [days, setDays] = useState(7); const [opinion, setOpinion] = useState(''); const [decision, setDecision] = useState<boolean>();
  const p = data.projects.find((p) => p.id === id); const request = data.planRequests.find((r) => r.id === requestId && r.projectId === id); const isNew = requestId === 'new';
  if (!p || !isNew && !request) return <StateView type="404" />;
  if (!visibleProjects(currentRole, data.projects).some((p) => p.id === id)) return <StateView type="403" />;
  const kind = request?.kind ?? (stageEntry || params.get('kind') === 'stage' ? 'stage' : 'schedule');
  const canSubmit = currentRole === 'project-manager' && currentUser.id === p.pmId && !data.lockedProjects.includes(p.id) && p.phase === '执行';
  const canReview = request?.status === '待审批' && request.requiredRoles.some((r) => r === currentRole) && !request.reviews.some((r) => r.role === currentRole);
  const sourceRequirementId = request?.sourceRequirementId ?? params.get('sourceRequirementId');
  const actor = { id: currentUser.id, name: currentUser.name, role: currentRole };
  return <><PageHeader title={kind === 'schedule' ? '项目计划变更原单' : 'HS-16 阶段切换申请'} description={`${p.id} · ${p.name} · ${request?.id ?? '新申请'}`} breadcrumbs={[{ title: '首页', href: '/' }, { title: '原业务申请' }]} extra={<Button onClick={() => navigate(-1)}>返回来源</Button>} />
    <Descriptions bordered column={2} items={[{ key: 'baseline', label: '引用基线', children: request?.baselineId ?? data.baselines.find((b) => b.projectId === id && b.status === '已生效')?.id }, { key: 'node', label: '节点 / 状态', children: `${request?.requiredRoles.map((role) => role === 'pmo' ? 'PMO' : '财务').join(' + ') ?? (days > 30 && kind === 'schedule' ? 'PMO + 财务会签' : 'PMO')} · ${request?.status ?? '待提交'}` }, { key: 'reason', label: '申请理由', span: 2, children: request?.reason ?? '请填写下方申请' }, { key: 'opinion', label: '审批意见', span: 2, children: request?.opinion ?? '尚未审批' }]} />
    {sourceRequirementId && <Button type="link" onClick={() => navigate(`/requirements-bugs/${sourceRequirementId}`)}>查看来源需求 {sourceRequirementId}</Button>}
    <Alert style={{ margin: '16px 0' }} showIcon type="info" message={kind === 'schedule' ? '演示支持未完成任务和未达成里程碑整体顺延1至90天；通过后追加计划基线，已完成任务和执行事实保留。' : '阶段门检查执行完成率、开发完成里程碑、必交材料及未关闭重大问题；条件不足不能通过。'} />
    {kind === 'stage' && <><Alert style={{margin:'16px 0'}} message={`演示规则 ${request?.stageSnapshot?.rule??stageSnapshot(data,p.id).rule}：执行→收尾/客户终验，PMO批准后阶段累计人力预算释放至${request?.stageSnapshot?.releasePercent??stageSnapshot(data,p.id).releasePercent}%，不改预算总额，不等于客户验收通过。`} /><Descriptions bordered size="small" column={2} items={[{key:'current',label:'申请来源阶段',children:request?.stageSnapshot ? `${request.stageSnapshot.fromPhase}/${request.stageSnapshot.fromSubPhase}` : `${p.phase}/${p.subPhase}`},{key:'target',label:'目标阶段',children:'收尾 / 客户终验'},{key:'milestone',label:'对应里程碑',children:'开发完成'},{key:'actual',label:'计划 / 实际完成',children:`${request?.stageSnapshot?.plannedDate ?? data.milestones.find((m)=>m.projectId===id&&m.type==='开发完成')?.plannedDate} / ${request?.stageSnapshot?.actualDate ?? data.milestones.find((m)=>m.projectId===id&&m.type==='开发完成')?.actualDate ?? '未达成'}`}]} /><Table rowKey="key" size="small" pagination={false} dataSource={request?.status==='通过' ? request.approvalSnapshot?.checks ?? request.stageSnapshot?.checks : stageChecks(data,p.id)} columns={[{title:'校验条件',dataIndex:'name'},{title:'状态',render:(_,r)=>r.passed?'通过':'阻断'},{title:'校验依据',dataIndex:'detail'}]} /><Space style={{margin:'12px 0'}}><Button onClick={()=>navigate(`/projects/${p.id}/daily-reports`)}>查看里程碑实际达成</Button><Button onClick={()=>navigate(`/projects/${p.id}/deliverables`)}>补充材料及质量评审</Button><Button onClick={()=>navigate(`/projects/${p.id}/progress`)}>查看执行任务</Button></Space><Card size="small" title="阶段申请历史" style={{marginTop:16}}><Button disabled={!canSubmit} onClick={()=>navigate(`/projects/${p.id}/stage-switch`)}>新建阶段申请</Button><Table rowKey="id" size="small" pagination={false} dataSource={data.planRequests.filter((r)=>r.projectId===p.id&&r.kind==='stage')} columns={[{title:'原申请',render:(_,r)=><Button type="link" onClick={()=>navigate(`/projects/${p.id}/stage-switch?request=${r.id}`)}>{r.id}</Button>},{title:'提交日',dataIndex:'submittedAt'},{title:'结论',dataIndex:'status'},{title:'审批日',render:(_,r)=>r.reviewedAt??'待处理'},{title:'意见',dataIndex:'opinion'}]} /></Card></>}
    {kind === 'schedule' && <Card title={`申请计划 · 顺延${request?.shiftDays ?? days}天`} size="small"><Table rowKey="id" size="small" pagination={false} dataSource={request?.tasks ?? data.tasks.filter((t) => t.projectId === id)} columns={[{ title: '任务', dataIndex: 'name' }, { title: '原计划开始', dataIndex: 'startDate' }, { title: '原计划完成', dataIndex: 'endDate' }, { title: '提交时完成率', dataIndex: 'progress' }]} /></Card>}
    {request && <Card size="small" title="审批轨迹 · 演示规则 PLAN-1"><p>计划顺延超过30天时须PMO与财务全通过，其余由PMO审批；单个节点通过不生效。</p>{request.requiredRoles.map((role) => <p key={role}>{role === 'pmo' ? 'PMO' : '财务'}：{request.reviews.find((r) => r.role === role)?.opinion ?? '等待处理'}</p>)}</Card>}
    {isNew ? <Card title="提交申请" size="small" style={{ marginTop: 16 }}><Space direction="vertical" style={{ width: '100%' }}>{kind === 'schedule' && <label>顺延天数 <InputNumber aria-label="顺延天数" min={1} max={90} value={days} onChange={(value) => setDays(value ?? 1)} disabled={!canSubmit} /></label>}<Input.TextArea aria-label="申请理由" placeholder="申请理由、影响与应对措施（必填）" value={reason} onChange={(e) => setReason(e.target.value)} disabled={!canSubmit} /><Button type="primary" disabled={!canSubmit} onClick={() => { try { const newId = `PLAN-${data.planRequests.length + 1}`; dispatch({ type: 'request-plan', projectId: p.id, kind, sourceRequirementId: params.get('sourceRequirementId') ?? undefined, shiftDays: kind === 'stage' ? 0 : days, reason }, actor); navigate(kind === 'stage' ? `/projects/${p.id}/stage-switch?request=${newId}` : `/projects/${p.id}/plan-requests/${newId}`, { replace: true }); message.success('原申请已提交PMO'); } catch (error) { message.error((error as Error).message); } }}>提交PMO审批</Button></Space></Card> : request?.status === '待审批' && <Card title="当前节点审批" size="small" style={{ marginTop: 16 }}><Input.TextArea aria-label="审批意见" value={opinion} disabled={!canReview} onChange={(e) => setOpinion(e.target.value)} /><Space style={{ marginTop: 12 }}><Button type="primary" disabled={!canReview} onClick={() => opinion.trim() ? setDecision(true) : message.error('审批意见必填')}>通过申请</Button><Button danger disabled={!canReview} onClick={() => opinion.trim() ? setDecision(false) : message.error('审批意见必填')}>驳回申请</Button></Space></Card>}
    <Modal zIndex={1200} title={decision ? '确认通过申请' : '确认驳回申请'} open={decision !== undefined} onCancel={() => setDecision(undefined)} onOk={() => { try { dispatch({ type: 'review-plan', id: request!.id, approve: decision!, opinion }, actor); setDecision(undefined); message.success('审批状态已更新'); } catch (error) { message.error((error as Error).message); } }}><p>{p.name}</p><p>{opinion}</p></Modal>
  </>;
}
